In [ ]:
!pip install tqdm

## **1_1~2. S.com Traffic by Division**

#### **S.com DA Traffic & Order (App)**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
import pandas as pd

json_file_name = "1_1_scom_da_traffic_app.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 13:56:13
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_app_20260326_1356.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_app_20260326_1356.csv
총 데이터 row(FAILED row 제외, header 제외): 27
⏱ Elapsed: 0:02:12.647461
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_app_20260326_1356.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,2531.0,1999.0,...,6.0,0.0,21.0,13.0,8.0,19591.56,12119.79,7471.77,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,748.0,556.0,...,0.0,0.0,8.0,5.0,3.0,7946.89,6249.92,1696.97,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,3638.0,2986.0,...,0.0,1.0,72.0,57.0,8.0,59332.11,47275.78,7430.36,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,2023.0,1478.0,...,0.0,0.0,77.0,50.0,16.0,63183.02,42839.79,7663.28,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,2699.0,1860.0,...,2.0,12.0,89.0,55.0,24.0,88102.93,61577.67,21550.83,OK,NaN

#### **S.com DA Traffic & Order (Web)**

In [11]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_da_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 13:58:46
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_web_20260326_1358.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_web_20260326_1358.csv
총 데이터 row(FAILED row 제외, header 제외): 42
⏱ Elapsed: 0:00:25.055872
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_web_20260326_1358.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,101729.0,79967.0,...,89450.0,66692.0,61094.0,40543.0,122.0,128.0,86425.40,86072.23,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,5572.0,9938.0,...,3317.0,7793.0,972.0,4803.0,6.0,15.0,3854.96,10097.36,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,16679.0,24826.0,...,11374.0,18157.0,4534.0,6300.0,177.0,186.0,158003.70,165954.11,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,8907.0,17537.0,...,5509.0,12632.0,698.0,2918.0,108.0,138.0,89759.07,120823.04,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,9304.0,12662.0,...,6698.0,9260.0,2026.0,3346.0,114.0,70.0,104963.02,60377.79,OK,NaN

#### **S.com MX Traffic & Order (App)**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_mx_traffic_app.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 13:59:28
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_app_20260326_1359.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_app_20260326_1359.csv
총 데이터 row(FAILED row 제외, header 제외): 29
⏱ Elapsed: 0:04:29.158386
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_app_20260326_1359.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,42648.0,34638.0,...,16.0,15.0,480.0,423.0,30.0,320663.53,260951.71,38624.75,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,5696.0,4795.0,...,5.0,2.0,109.0,90.0,6.0,61975.65,47437.87,4652.94,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,29365.0,24677.0,...,8.0,1.0,653.0,558.0,40.0,377089.92,308100.15,30474.73,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,17945.0,14001.0,...,5.0,0.0,329.0,282.0,11.0,211733.72,172506.35,10627.74,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,13436.0,10596.0,...,9.0,1.0,321.0,255.0,16.0,352382.48,276109.26,19048.38,OK,NaN

#### **S.com MX Traffic & Order (Web)**

In [13]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_mx_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:06:27
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_web_20260326_1406.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_web_20260326_1406.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:34.651864
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_web_20260326_1406.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,135721.0,457483.0,...,88403.0,387323.0,26930.0,239219.0,1295.0,1387.0,1306847.57,1004438.70,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,13939.0,41399.0,...,8907.0,34621.0,2388.0,19983.0,129.0,121.0,87588.66,69748.61,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,62496.0,199872.0,...,44491.0,162635.0,13189.0,65002.0,929.0,1395.0,686816.57,920623.86,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,49347.0,154424.0,...,32688.0,126104.0,5775.0,32211.0,433.0,630.0,452684.15,442721.72,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,30386.0,90230.0,...,21453.0,72639.0,5756.0,30282.0,262.0,332.0,283839.93,423952.19,OK,NaN

#### **S.com VD Traffic & Order (App)**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_vd_traffic_app.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:07:26
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_app_20260326_1407.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_app_20260326_1407.csv
총 데이터 row(FAILED row 제외, header 제외): 27
⏱ Elapsed: 0:06:12.544425
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_app_20260326_1407.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,10313.0,7500.0,...,73.0,73.0,82.0,65.0,16.0,90537.01,77018.27,12718.75,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,1924.0,1350.0,...,24.0,15.0,18.0,14.0,4.0,21803.00,15428.84,6374.16,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,6383.0,5295.0,...,2.0,0.0,123.0,86.0,26.0,107732.39,77946.85,21920.60,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,3631.0,2554.0,...,0.0,1.0,55.0,39.0,7.0,59375.43,36122.22,12330.10,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,5893.0,3884.0,...,4.0,9.0,254.0,151.0,85.0,280773.39,149261.02,113477.81,OK,NaN

#### **S.com VD Traffic & Order (Web)**

In [15]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_vd_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" /  json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:14:31
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_web_20260326_1414.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_web_20260326_1414.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:27.296171
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_web_20260326_1414.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,177288.0,321286.0,...,156050.0,299119.0,112040.0,182872.0,352.0,230.0,439429.64,270269.98,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,8558.0,16055.0,...,5841.0,13639.0,2010.0,7584.0,30.0,22.0,37969.12,22951.41,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,24792.0,38284.0,...,17201.0,28798.0,5121.0,9482.0,240.0,235.0,283914.12,212040.78,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,24101.0,37840.0,...,14680.0,28654.0,2057.0,6459.0,138.0,147.0,188807.27,176248.71,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,15518.0,26535.0,...,10852.0,20851.0,2966.0,9028.0,205.0,128.0,213117.59,144474.77,OK,NaN

## **2_1~4. Basic Traffic**

## Basic Traffic - Campaign Page (w. CID) (Web & App)

In [16]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "2_1_basic_traffic_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:16:05
▶ Output: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_cmp_20260326_1416.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30', 'value31', 'value32', 'value33', 'value34', 'value35']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_cmp_20260326_1416.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:01:28.770457
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_cmp_20260326_1416.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value28,value29,value30,value31,value32,value33,value34,value35,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),3597.0,47847.0,...,741.0,77.0,291.0,232.0,40.0,0.0,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),955.0,12046.0,...,225.0,20.0,70.0,52.0,8.0,0.0,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),1068.0,1792.0,...,319.0,47.0,18.0,0.0,18.0,0.0,0.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),11968.0,30801.0,...,23.0,120.0,79.0,1.0,78.0,0.0,0.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),6099.0,25735.0,...,553.0,95.0,502.0,470.0,32.0,0.0,0.0,0.0,OK,NaN

#### **Basic Traffic - S.com (Web & App)**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "2_1_basic_traffic_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:19:47
▶ Output: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_scom_20260326_1419.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_scom_20260326_1419.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:03:59.561093
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_scom_20260326_1419.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,562632.0,1513564.0,...,1689491.0,56658.0,166838.0,140329.0,10669.0,59553.0,49198.0,5440.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,45006.0,117645.0,...,307368.0,16205.0,42570.0,37111.0,1630.0,22111.0,19454.0,812.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,141364.0,409600.0,...,2368162.0,79133.0,124384.0,107853.0,9415.0,38493.0,31583.0,6116.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,120960.0,362153.0,...,932749.0,39378.0,89343.0,76171.0,4922.0,28007.0,24070.0,3039.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,72023.0,201033.0,...,1417068.0,59501.0,91850.0,72716.0,10166.0,32863.0,24909.0,6620.0,OK,NaN

## Basic Traffic  - Campaign Page Time Spent per Visit (Web & App)

In [18]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "2_1_basic_traffic_time_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:26:01
▶ Output: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_cmp_20260326_1426.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_cmp_20260326_1426.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:17.599849
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_cmp_20260326_1426.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),262.005164,270.270961,266.408552,211.945593,211.176878,281.012172,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),210.874496,250.636858,186.302535,227.455499,210.596072,331.937673,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),300.829985,412.216835,265.329958,275.831504,263.674406,406.252762,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),310.974821,351.188070,311.123176,223.710963,214.757414,358.128766,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),284.848332,373.372557,250.927068,276.992889,259.486520,411.874601,OK,NaN

#### **Basic Traffic  - S.com Time Spent per Visit (Web & App)**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "2_1_basic_traffic_time_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:27:38
▶ Output: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_scom_20260326_1427.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_scom_20260326_1427.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:13.114339
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_scom_20260326_1427.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),262.005164,270.270961,266.408552,211.945593,211.176878,281.012172,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),210.874496,250.636858,186.302535,227.455499,210.596072,331.937673,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),300.829985,412.216835,265.329958,275.831504,263.674406,406.252762,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),310.974821,351.188070,311.123176,223.710963,214.757414,358.128766,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),284.848332,373.372557,250.927068,276.992889,259.486520,411.874601,OK,NaN

## **3. Traffic by Channel**

#### **Internal Traffic (Web)**

In [20]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "3_1_channel_internal.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:28:44
▶ Output: C:\api\AA_Exporter\aa_exports\3_1_channel_internal_20260326_1428.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\3_1_channel_internal_20260326_1428.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:02:20.647198
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\3_1_channel_internal_20260326_1428.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),55.0,284.0,...,0.0,0.0,2.0,550.0,227.0,0.0,0.0,2.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),7.0,34.0,...,0.0,0.0,1.0,256.0,116.0,0.0,0.0,1.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),42.0,549.0,...,0.0,0.0,1.0,366.0,55.0,0.0,0.0,1.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),46.0,582.0,...,29.0,0.0,322.0,636.0,3218.0,2.0,10.0,322.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),40.0,164.0,...,10.0,0.0,1.0,418.0,374.0,0.0,0.0,1.0,OK,NaN

#### **External Traffic by Channel - Campaign Page (Web & App)**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "3_2_channel_external_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:33:06
▶ Output: C:\api\AA_Exporter\aa_exports\3_2_channel_external_cmp_20260326_1433.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\3_2_channel_external_cmp_20260326_1433.csv
총 데이터 row(FAILED row 제외, header 제외): 572
⏱ Elapsed: 0:00:21.707861
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\3_2_channel_external_cmp_20260326_1433.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,14,Push,1287.0,922.0,43490.0,34791.0,79.0,7.0,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,4,Email,796.0,239.0,1764.0,704.0,22.0,3.0,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,21,Pmax,575.0,47.0,1092.0,108.0,2.0,1.0,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,5,Direct,145.0,56.0,74.0,39.0,651.0,250.0,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,2,Natural Search,40.0,10.0,35.0,11.0,13.0,3.0,OK,NaN

#### **External Traffic by Channel - S.com (Web & App)**

In [22]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "3_2_channel_external_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:33:34
▶ Output: C:\api\AA_Exporter\aa_exports\3_2_channel_external_scom_20260326_1433.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\3_2_channel_external_scom_20260326_1433.csv
총 데이터 row(FAILED row 제외, header 제외): 879
⏱ Elapsed: 0:00:18.518441
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\3_2_channel_external_scom_20260326_1433.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,11,Social Media Campaigns,572874.0,424953.0,686.0,178.0,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,2,Natural Search,482861.0,106446.0,8749.0,1624.0,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,5,Direct,434475.0,291457.0,105408.0,43018.0,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1,Paid Search,193002.0,92262.0,3257.0,848.0,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,14,Push,78238.0,60627.0,21412.0,5501.0,OK,NaN

#### **3. Home KV & GNB to cmp Page**

In [23]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "3_3_homepage_kv_gnb_to_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:34:10
▶ Output: C:\api\AA_Exporter\aa_exports\3_3_homepage_kv_gnb_to_cmp_20260326_1434.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\3_3_homepage_kv_gnb_to_cmp_20260326_1434.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:20.254612
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\3_3_homepage_kv_gnb_to_cmp_20260326_1434.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),111920.0,142677.0,107886.0,284.0,512.0,550.0,31.0,9.0,2.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),11281.0,15172.0,19605.0,34.0,87.0,256.0,6.0,4.0,1.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),33543.0,66343.0,88446.0,549.0,928.0,366.0,25.0,4.0,1.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),23979.0,35433.0,60922.0,582.0,1015.0,636.0,26.0,10.0,322.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),11752.0,17424.0,57772.0,164.0,283.0,418.0,24.0,0.0,1.0,OK,NaN

## **4. Order Conversion with Login/Non-Login**

#### **Order Conversion - cmp Page > PD / ATC Page, cmp Page & S.com Order (Total)**

In [24]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "4_1_order_cvr_loginout.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:35:26
▶ Output: C:\api\AA_Exporter\aa_exports\4_1_order_cvr_loginout_20260326_1435.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\4_1_order_cvr_loginout_20260326_1435.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:06:36.053687
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\4_1_order_cvr_loginout_20260326_1435.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),6069.0,409.0,...,25174.50,5824.94,4348.0,2761.0,1587.0,3740968.77,2251824.48,1489144.29,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),1030.0,39.0,...,3731.44,269.99,473.0,324.0,149.0,326258.09,218860.09,107398.00,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),1260.0,157.0,...,31294.11,3890.44,4072.0,3113.0,959.0,2960972.34,2319266.50,641705.84,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),14463.0,4447.0,...,150543.29,70897.67,2129.0,1245.0,884.0,1748789.12,994504.92,754284.20,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),11925.0,1623.0,...,296599.92,80579.09,1778.0,1384.0,394.0,1916777.34,1469155.22,447622.12,OK,NaN

#### **(4_2.) Order Conversion - Visit/Visitor by Login & Non-login (Total)**

In [25]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "4_2_order_cvr_visit_visitor.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:45:39
▶ Output: C:\api\AA_Exporter\aa_exports\4_2_order_cvr_visit_visitor_20260326_1445.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\4_2_order_cvr_visit_visitor_20260326_1445.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:53.701427
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\4_2_order_cvr_visit_visitor_20260326_1445.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),912.0,50532.0,...,5896.0,963.0,5655.0,855.0,76361.0,1999835.0,108784.0,58054.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),142.0,12859.0,...,1320.0,320.0,1236.0,201.0,7955.0,154696.0,18709.0,23861.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),455.0,2405.0,...,423.0,154.0,405.0,129.0,53395.0,497569.0,81609.0,42775.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),2957.0,39812.0,...,4196.0,674.0,3692.0,618.0,32421.0,450692.0,56157.0,33186.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),2877.0,28957.0,...,2212.0,459.0,2097.0,435.0,20496.0,252560.0,54416.0,37435.0,OK,NaN

## 5. S.COM ORDER CONVERSION IN cmp PERIOD

#### **S.com Order Conversion - Order & Revenue (Total & APP)**

In [1]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "5_1_scom_order_cvr.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 13:52:07
▶ Output: C:\api\AA_Exporter\aa_exports\5_1_scom_order_cvr_20260330_1352.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\5_1_scom_order_cvr_20260330_1352.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:02:40.038220
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\5_1_scom_order_cvr_20260330_1352.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),4348.0,3740968.77,...,505.0,57.0,429722.72,347691.43,59705.24,182.0,154.0,16.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),473.0,326258.09,...,107.0,13.0,87706.58,65097.67,12724.07,33.0,28.0,1.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),4079.0,2969367.41,...,700.0,77.0,535570.71,426371.85,60363.04,255.0,217.0,17.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),2140.0,1753127.95,...,371.0,36.0,315403.63,236053.56,32596.99,117.0,93.0,7.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),1781.0,1920737.69,...,451.0,125.0,698492.91,465214.28,152776.35,208.0,145.0,30.0,OK,NaN

#### **S.com Order Conversion - cmp Page Order (Total)**

In [2]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "5_1_campaign_order_cvr.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 13:55:01
▶ Output: C:\api\AA_Exporter\aa_exports\5_1_campaign_order_cvr_20260330_1355.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\5_1_campaign_order_cvr_20260330_1355.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:01:12.651531
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\5_1_campaign_order_cvr_20260330_1355.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),25.0,27.0,...,4.0,0.0,22.0,19.0,2.0,2.0,1.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),5.0,7.0,...,4.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),20.0,31.0,...,7.0,1.0,4.0,3.0,1.0,1.0,1.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),266.0,285.0,...,55.0,4.0,67.0,52.0,4.0,15.0,13.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),297.0,330.0,...,27.0,12.0,53.0,35.0,11.0,12.0,8.0,2.0,OK,NaN

## **6. S.com Cross Sell Order**

#### **6-1. Multi Order Cross-Sell (Total)**

In [28]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "6_1_multi_order_cross_sell.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:48:55
▶ Output: C:\api\AA_Exporter\aa_exports\6_1_multi_order_cross_sell_20260326_1448.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\6_1_multi_order_cross_sell_20260326_1448.csv
총 데이터 row(FAILED row 제외, header 제외): 38
⏱ Elapsed: 0:01:53.847934
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\6_1_multi_order_cross_sell_20260326_1448.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,1244.0,1649364.86,...,7.0,7088.21,0.0,0.00,0.0,0.00,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,129.0,122293.80,...,2.0,4018.96,0.0,0.00,0.0,0.00,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,1038.0,1060624.26,...,8.0,11279.08,3.0,5964.53,3.0,6518.94,0.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,604.0,802205.85,...,1.0,208.80,19.0,38877.31,20.0,50624.89,0.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,571.0,847127.45,...,5.0,8125.85,6.0,13870.57,7.0,16930.96,0.0,0.0,OK,NaN

#### **6-2. All Order Cross-Sell (Total)**

In [29]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "6_2_total_order_cross_sell.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:51:20
▶ Output: C:\api\AA_Exporter\aa_exports\6_2_total_order_cross_sell_20260326_1451.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\6_2_total_order_cross_sell_20260326_1451.csv
총 데이터 row(FAILED row 제외, header 제외): 38
⏱ Elapsed: 0:00:43.369437
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\6_2_total_order_cross_sell_20260326_1451.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,0,NaN,4348.0,3740968.77,...,7.0,7088.21,0.0,0.00,0.0,0.00,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,0,NaN,473.0,326258.09,...,2.0,4018.96,0.0,0.00,0.0,0.00,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,0,NaN,4072.0,2960972.34,...,8.0,11279.08,3.0,5964.53,3.0,6518.94,0.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,0,NaN,2129.0,1748789.12,...,1.0,208.80,19.0,38877.31,20.0,50624.89,0.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,0,NaN,1778.0,1916777.34,...,5.0,8125.85,6.0,13870.57,7.0,16930.96,0.0,0.0,OK,NaN

#### **6-3. cmp Visit & Order Cross-Sell (Total)**

In [30]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "6_3_cmp_order_cross_sell.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:52:13
▶ Output: C:\api\AA_Exporter\aa_exports\6_3_cmp_order_cross_sell_20260326_1452.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\6_3_cmp_order_cross_sell_20260326_1452.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:35.497741
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\6_3_cmp_order_cross_sell_20260326_1452.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),27.0,30999.44,...,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),7.0,4001.43,...,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),31.0,35184.55,...,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),284.0,221440.96,...,0.0,0.0,2.0,4087.45,3.0,8397.58,0.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),331.0,377179.01,...,0.0,0.0,3.0,9066.74,1.0,2459.68,0.0,0.0,OK,NaN

## **7_1~2. Order Conversion/Traffic by Channel**

#### **Order Conversion by Channel - cmp Page (Web & App)**

In [31]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "7_1_order_by_channel_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:52:55
▶ Output: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_cmp_20260326_1452.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_cmp_20260326_1452.csv
총 데이터 row(FAILED row 제외, header 제외): 692
⏱ Elapsed: 0:00:30.721340
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_cmp_20260326_1452.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value8,value9,value10,value11,value12,value13,value14,value15,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,14,Push,1288.0,43555.0,...,0.0,0.0,0.0,0.00,1134.99,0.00,0.00,0.0,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,4,Email,857.0,1935.0,...,0.0,0.0,0.0,0.00,1349.99,0.00,0.00,0.0,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,21,Pmax,601.0,1148.0,...,0.0,0.0,0.0,4449.95,3221.45,0.00,0.00,0.0,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,5,Direct,416.0,311.0,...,2.0,2.0,0.0,0.00,0.00,2599.98,2599.98,0.0,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,2,Natural Search,276.0,407.0,...,0.0,0.0,0.0,5657.11,2519.98,0.00,0.00,0.0,OK,NaN

#### **Order Conversion by Channel - S.com (Web & App)**

In [33]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "7_1_order_by_channel_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:53:55
▶ Output: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_scom_20260326_1453.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_scom_20260326_1453.csv
총 데이터 row(FAILED row 제외, header 제외): 879
⏱ Elapsed: 0:00:48.631098
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_scom_20260326_1453.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,11,Social Media Campaigns,572874.0,686.0,4.0,3.0,6722.01,1047.98,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,2,Natural Search,482861.0,8749.0,1666.0,58.0,1378725.45,42968.13,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,5,Direct,434475.0,105408.0,600.0,320.0,572999.98,218854.25,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1,Paid Search,193002.0,3257.0,528.0,7.0,528724.24,5249.31,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,14,Push,78238.0,21412.0,5.0,89.0,3246.96,70920.69,OK,NaN

## 8. cmp PAGE ADAPTIVE BANNER PERFORMANCE

## Login CTA > Login Success / Marketing Consent CTA > Pop-up CTA

In [34]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "8_1_login_cta.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:54:58
▶ Output: C:\api\AA_Exporter\aa_exports\8_1_login_cta_20260326_1454.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\8_1_login_cta_20260326_1454.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:45.585563
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\8_1_login_cta_20260326_1454.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),58303.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-26,1260001,2026 (Jan 1-Dec 31),14641.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),3437.0,0.0,0.0,2.0,2.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-01-26,1260001,2026 (Jan 1-Dec 31),47639.0,1.0,1.0,0.0,0.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-01-26,1260001,2026 (Jan 1-Dec 31),34505.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

## Nextpage, Multiorder, Best Selling Products

## Next page

In [38]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "nextpage.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 15:03:19
▶ Output: C:\api\AA_Exporter\aa_exports\nextpage_20260326_1503.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\nextpage_20260326_1503.csv
총 데이터 row(FAILED row 제외, header 제외): 1,473
⏱ Elapsed: 0:00:26.686993
❌ 실패 site: 3
실패 목록(앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: C:\api\AA_Exporter\aa_exports\nextpage_20260326_1503.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,3.457728e+09,flagship pdp,2508.0,2507.0,0.0,0.0,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,3.543974e+09,product finder,1554.0,1221.0,251.0,86.0,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,2.067554e+09,product detail,1122.0,256.0,515.0,409.0,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1.231280e+09,microsite,342.0,190.0,0.0,10.0,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,8.041200e+08,product category detail,171.0,93.0,23.0,14.0,OK,NaN

#### **cmp Multi Order (Total)**

In [36]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "multi_purchase.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 15:01:48
▶ Output: C:\api\AA_Exporter\aa_exports\multi_purchase_20260326_1501.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\multi_purchase_20260326_1501.csv
총 데이터 row(FAILED row 제외, header 제외): 9,694
⏱ Elapsed: 0:00:26.890197
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\multi_purchase_20260326_1501.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,2732371547,HAF-QIN/EXP,0.0,0.0,0.00,146.0,62.0,6432.60,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,4161418187,HAF-CIN/EXP,0.0,0.0,0.00,45.0,17.0,1962.50,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,3323044592,"SM-R630NZAAXAC,P-GT-AXXCW0MC",0.0,0.0,0.00,24.0,12.0,3339.99,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,537663737,"SM-Q5KAPH,ET-YQ510KBEGCA",0.0,0.0,0.00,22.0,11.0,4849.89,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,3179410324,"SM-Q5KAPH,P-GT-AXXDW0PC,ET-YQ510KBEGCA",3.0,1.0,616.07,21.0,7.0,3970.51,OK,NaN

## Best Selling Product

In [37]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "bestselling.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 15:02:21
▶ Output: C:\api\AA_Exporter\aa_exports\bestselling_20260326_1502.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\bestselling_20260326_1502.csv
총 데이터 row(FAILED row 제외, header 제외): 8,649
⏱ Elapsed: 0:00:46.859209
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\bestselling_20260326_1502.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,3312046943,SMC-CA-STANDALONE,346.0,64986.29,0.0,0.00,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,2977328126,SMC-CA,310.0,36428.82,2.0,145.08,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,833632946,SM-S938W,294.0,623317.37,4.0,6759.97,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,1802553923,TRADE-IN,234.0,0.00,2.0,0.00,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-26,2466828847,SM-R630,201.0,49047.87,1.0,207.00,OK,NaN