In [1]:
# !pip install tqdm

## **1_1~2. S.com Traffic by Division**

#### **Scom DA Traffic APP**

In [2]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_1_1_scom_da_traffic_app.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:00:35
▶ Output: C:\api\AA_Exporter\aa_exports\last_1_1_scom_da_traffic_app_20260326_1400.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_1_1_scom_da_traffic_app_20260326_1400.csv
총 데이터 row(FAILED row 제외, header 제외): 23
⏱ Elapsed: 0:02:08.627217
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_1_1_scom_da_traffic_app_20260326_1400.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,3276.0,2655.0,...,11.0,12.0,60.0,28.0,24.0,50581.51,12453.68,22905.92,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,652.0,487.0,...,0.0,3.0,10.0,4.0,5.0,7806.20,3594.96,3186.25,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,6668.0,5639.0,...,2.0,4.0,177.0,80.0,31.0,169389.30,64581.04,36835.17,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,2629.0,2318.0,...,0.0,0.0,78.0,55.0,9.0,57140.61,42860.03,6287.04,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,2383.0,1976.0,...,0.0,1.0,133.0,41.0,17.0,108317.41,32811.26,13323.59,OK,NaN

#### **Scom DA Traffic WEB**

In [3]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_1_1_scom_da_traffic_web.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:03:39
▶ Output: C:\api\AA_Exporter\aa_exports\last_1_1_scom_da_traffic_web_20260326_1403.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_1_1_scom_da_traffic_web_20260326_1403.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:30.998746
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_1_1_scom_da_traffic_web_20260326_1403.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,67135.0,116778.0,...,53434.0,104344.0,29065.0,45759.0,215.0,162.0,121223.81,55041.69,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,5661.0,9886.0,...,3155.0,7071.0,944.0,2578.0,23.0,20.0,8249.78,9012.84,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,24400.0,39474.0,...,16949.0,29849.0,5594.0,5970.0,265.0,180.0,205294.40,127467.56,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,14546.0,35261.0,...,10317.0,29784.0,1924.0,608.0,151.0,181.0,130240.58,133257.79,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,10198.0,20076.0,...,7392.0,16154.0,1936.0,3326.0,189.0,51.0,125436.52,37942.16,OK,NaN

#### **Scom MX Traffic APP**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_1_1_scom_mx_traffic_app.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:06:23
▶ Output: C:\api\AA_Exporter\aa_exports\last_1_1_scom_mx_traffic_app_20260326_1406.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_1_1_scom_mx_traffic_app_20260326_1406.csv
총 데이터 row(FAILED row 제외, header 제외): 23
⏱ Elapsed: 0:03:56.939839
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_1_1_scom_mx_traffic_app_20260326_1406.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,71263.0,62115.0,...,25.0,15.0,2572.0,1765.0,462.0,2589328.96,1722097.42,523873.57,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,8299.0,7433.0,...,2.0,1.0,295.0,229.0,27.0,279261.55,217323.71,28123.26,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,80125.0,75191.0,...,9.0,2.0,2633.0,1747.0,137.0,2012731.37,1334765.72,122639.83,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,49648.0,47948.0,...,5.0,1.0,1669.0,1209.0,55.0,1182124.99,835164.15,59734.16,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,21608.0,20650.0,...,14.0,2.0,1188.0,524.0,18.0,894851.67,399204.63,19995.74,OK,NaN

#### **Scom MX Traffic WEB**

In [5]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_1_1_scom_mx_traffic_web.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:10:50
▶ Output: C:\api\AA_Exporter\aa_exports\last_1_1_scom_mx_traffic_web_20260326_1410.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_1_1_scom_mx_traffic_web_20260326_1410.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:28.492975
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_1_1_scom_mx_traffic_web_20260326_1410.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,211436.0,751235.0,...,163375.0,683406.0,53085.0,331505.0,3103.0,2367.0,3102654.82,2091253.77,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,21993.0,77999.0,...,15446.0,65361.0,6130.0,38060.0,266.0,236.0,224752.02,224439.29,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,123614.0,599976.0,...,94667.0,538156.0,25820.0,212948.0,1711.0,1839.0,1083280.08,1004430.67,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,102074.0,407685.0,...,79970.0,368885.0,18928.0,98247.0,1883.0,1862.0,995798.47,851468.97,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,53894.0,177997.0,...,40486.0,150799.0,12284.0,50211.0,1167.0,573.0,915407.43,558447.37,OK,NaN

#### **Scom VD Traffic APP**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_1_1_scom_vd_traffic_app.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:12:09
▶ Output: C:\api\AA_Exporter\aa_exports\last_1_1_scom_vd_traffic_app_20260326_1412.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_1_1_scom_vd_traffic_app_20260326_1412.csv
총 데이터 row(FAILED row 제외, header 제외): 23
⏱ Elapsed: 0:05:07.585325
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_1_1_scom_vd_traffic_app_20260326_1412.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,8625.0,7090.0,...,30.0,17.0,98.0,60.0,20.0,107288.13,73438.31,17279.40,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,1121.0,887.0,...,6.0,2.0,10.0,4.0,4.0,13291.53,4999.94,5499.96,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,9267.0,7762.0,...,5.0,1.0,167.0,82.0,27.0,215773.46,99833.66,35673.89,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,3212.0,2848.0,...,1.0,0.0,33.0,21.0,3.0,25575.65,15793.59,1942.39,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,4770.0,3997.0,...,10.0,16.0,209.0,86.0,11.0,209015.57,82842.48,14347.26,OK,NaN

#### **Scom VD Traffic WEB**

In [7]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_1_1_scom_vd_traffic_web.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:19:54
▶ Output: C:\api\AA_Exporter\aa_exports\last_1_1_scom_vd_traffic_web_20260326_1419.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_1_1_scom_vd_traffic_web_20260326_1419.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:31.918603
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_1_1_scom_vd_traffic_web_20260326_1419.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,123354.0,186425.0,...,101308.0,167963.0,60145.0,56667.0,382.0,146.0,466760.05,188419.49,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,7131.0,9800.0,...,4610.0,7376.0,1660.0,1976.0,28.0,11.0,30540.67,11919.88,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,37876.0,62729.0,...,27109.0,51094.0,9037.0,12435.0,247.0,162.0,252515.46,157918.63,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,30396.0,56775.0,...,20572.0,46196.0,3582.0,1224.0,123.0,130.0,116687.13,119191.25,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,19692.0,39851.0,...,14114.0,32234.0,3824.0,6020.0,355.0,89.0,367921.23,90895.14,OK,NaN

## **2_1~4. Basic Traffic**

#### **Basic Traffic CMP**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_2_1_basic_traffic_cmp.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:21:51
▶ Output: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_cmp_20260326_1421.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30', 'value31', 'value32', 'value33', 'value34', 'value35']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_cmp_20260326_1421.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:06:21.138041
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_cmp_20260326_1421.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value28,value29,value30,value31,value32,value33,value34,value35,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),3125.0,9563.0,...,59.0,68.0,72.0,42.0,29.0,0.0,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),164.0,175.0,...,1.0,11.0,3.0,0.0,3.0,0.0,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,1250001,2025 (Jan 1-Dec 31),5002.0,6066.0,...,2.0,54.0,32.0,1.0,30.0,0.0,0.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,1250001,2025 (Jan 1-Dec 31),5379.0,10817.0,...,20.0,39.0,23.0,7.0,16.0,0.0,0.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,1250001,2025 (Jan 1-Dec 31),8470.0,15245.0,...,1.0,30.0,12.0,0.0,11.0,0.0,0.0,0.0,OK,NaN

#### **Basic Traffic Scom**

In [9]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_2_1_basic_traffic_scom.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:28:56
▶ Output: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_scom_20260326_1428.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_scom_20260326_1428.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:03:06.535130
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_scom_20260326_1428.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,612665.0,1516350.0,...,2095569.0,246104.0,182932.0,156365.0,26375.0,57077.0,45307.0,11630.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,51487.0,148886.0,...,309592.0,33418.0,77539.0,26954.0,2840.0,60848.0,11935.0,1269.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,262947.0,963522.0,...,3023829.0,227234.0,249613.0,225022.0,23976.0,73989.0,61553.0,12169.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,193475.0,665870.0,...,1597054.0,72567.0,139669.0,131301.0,8142.0,37621.0,33595.0,3934.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,112139.0,338743.0,...,1062617.0,65587.0,93291.0,82822.0,10183.0,33832.0,27392.0,6297.0,OK,NaN

#### **Basic Traffic Time**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_2_1_basic_traffic_time.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:33:01
▶ Output: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_time_20260326_1433.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_time_20260326_1433.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:50.419799
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_2_1_basic_traffic_time_20260326_1433.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),66.056124,106.434016,53.223568,63.732332,64.482915,59.718750,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),72.602894,214.861386,36.027027,48.595174,53.913333,30.700000,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,1250001,2025 (Jan 1-Dec 31),82.281668,101.321560,69.358303,67.151730,66.541667,68.149171,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,1250001,2025 (Jan 1-Dec 31),111.331473,141.397944,97.285510,109.896037,108.146288,135.441860,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,1250001,2025 (Jan 1-Dec 31),72.717531,76.767190,70.809351,71.389163,69.644689,96.981132,OK,NaN

## **3. Traffic by Channel**

#### **Channel Internal**

In [11]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_3_1_channel_internal.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:34:02
▶ Output: C:\api\AA_Exporter\aa_exports\last_3_1_channel_internal_20260326_1434.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_3_1_channel_internal_20260326_1434.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:02:17.150341
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_3_1_channel_internal_20260326_1434.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),29.0,46.0,...,0.0,0.0,0.0,1079.0,0.0,0.0,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),1.0,10.0,...,0.0,0.0,0.0,334.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,1250001,2025 (Jan 1-Dec 31),1143.0,191.0,...,10.0,0.0,0.0,1005.0,23.0,0.0,0.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,1250001,2025 (Jan 1-Dec 31),1318.0,109.0,...,39.0,0.0,320.0,895.0,2341.0,0.0,1.0,320.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,1250001,2025 (Jan 1-Dec 31),16.0,53.0,...,0.0,0.0,0.0,495.0,13.0,0.0,0.0,0.0,OK,NaN

#### **Channel Traffic External**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_3_2_channel_traffic_external.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:37:19
▶ Output: C:\api\AA_Exporter\aa_exports\last_3_2_channel_traffic_external_20260326_1437.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_3_2_channel_traffic_external_20260326_1437.csv
총 데이터 row(FAILED row 제외, header 제외): 355
⏱ Elapsed: 0:00:15.509990
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_3_2_channel_traffic_external_20260326_1437.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,11,Social Media Campaigns,5944.0,2714.0,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,21,Pmax,3183.0,441.0,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1,Paid Search,900.0,186.0,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,4,Email,608.0,256.0,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,5,Direct,477.0,189.0,OK,NaN

#### **Homepage KV GNB TO CMP**

In [13]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_3_3_homepage_kv_gnb_to_cmp.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:38:06
▶ Output: C:\api\AA_Exporter\aa_exports\last_3_3_homepage_kv_gnb_to_cmp_20260326_1438.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_3_3_homepage_kv_gnb_to_cmp_20260326_1438.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:24.447694
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_3_3_homepage_kv_gnb_to_cmp_20260326_1438.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),142248.0,164321.0,133415.0,46.0,60.0,1079.0,7.0,7.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),12017.0,18509.0,18903.0,10.0,16.0,334.0,0.0,1.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,1250001,2025 (Jan 1-Dec 31),63982.0,115237.0,192463.0,191.0,320.0,1005.0,311.0,529.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,1250001,2025 (Jan 1-Dec 31),36304.0,54775.0,110455.0,109.0,76.0,895.0,286.0,475.0,320.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,1250001,2025 (Jan 1-Dec 31),18439.0,50971.0,65365.0,53.0,24.0,495.0,9.0,4.0,0.0,OK,NaN

## **4. Order CVR**

#### **Order CVR Loginout**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_4_1_order_cvr_loginout.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:38:38
▶ Output: C:\api\AA_Exporter\aa_exports\last_4_1_order_cvr_loginout_20260326_1438.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_4_1_order_cvr_loginout_20260326_1438.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:17.715752
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_4_1_order_cvr_loginout_20260326_1438.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),80.0,64.0,16.0,71528.41,59248.61,12279.80,636.0,12052.0,2833.0,420.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),8.0,6.0,2.0,8482.24,6893.26,1588.98,20.0,319.0,257.0,134.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,1250001,2025 (Jan 1-Dec 31),181.0,146.0,35.0,124385.16,100172.27,24212.89,1453.0,9615.0,1124.0,172.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,1250001,2025 (Jan 1-Dec 31),347.0,282.0,65.0,219522.85,185267.68,34255.17,1186.0,15010.0,3688.0,265.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,1250001,2025 (Jan 1-Dec 31),234.0,193.0,41.0,212346.05,167216.59,45129.46,3156.0,20559.0,535.0,92.0,OK,NaN

#### **Scom Order CVR Loginout**

In [15]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_4_1_scom_order_cvr_loginout.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:39:48
▶ Output: C:\api\AA_Exporter\aa_exports\last_4_1_scom_order_cvr_loginout_20260326_1439.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_4_1_scom_order_cvr_loginout_20260326_1439.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:22.929243
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_4_1_scom_order_cvr_loginout_20260326_1439.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),9179.0,5853.0,3326.0,8734800.16,5665695.59,3069104.57,93161.0,2035854.0,151736.0,31196.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),910.0,549.0,361.0,810883.78,479939.44,330944.34,7985.0,192388.0,20079.0,57460.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,1250001,2025 (Jan 1-Dec 31),7422.0,4404.0,3018.0,5060597.91,3156251.24,1904346.67,70521.0,1155948.0,210074.0,39539.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,1250001,2025 (Jan 1-Dec 31),6289.0,3296.0,2993.0,3589526.31,1979419.04,1610107.27,45443.0,813902.0,117604.0,22065.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,1250001,2025 (Jan 1-Dec 31),3934.0,1590.0,2344.0,3240939.29,1345013.91,1895925.38,25953.0,424929.0,72720.0,20571.0,OK,NaN

## **5. Campaign Order CVR**

#### **Scom Campaign Order CVR**

In [16]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_5_1_scom_campaign_order_cvr.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:40:18
▶ Output: C:\api\AA_Exporter\aa_exports\last_5_1_scom_campaign_order_cvr_20260326_1440.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_5_1_scom_campaign_order_cvr_20260326_1440.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:22.623597
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_5_1_scom_campaign_order_cvr_20260326_1440.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),2129015.0,182932.0,9179.0,8734800.16,3316.0,76.0,80.0,158.0,31.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),200373.0,77539.0,910.0,810883.78,305.0,6.0,8.0,8.0,1.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,1250001,2025 (Jan 1-Dec 31),1226469.0,249613.0,7422.0,5060597.91,3133.0,154.0,181.0,107.0,68.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,1250001,2025 (Jan 1-Dec 31),859345.0,139669.0,6289.0,3589526.31,1335.0,313.0,347.0,185.0,98.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,1250001,2025 (Jan 1-Dec 31),450882.0,93291.0,3934.0,3240939.29,1698.0,214.0,234.0,112.0,120.0,OK,NaN

## **6. S.com Cross Sell Order**

#### **Multi Order Cross Sell**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_6_1_multi_order_cross_sell.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:40:47
▶ Output: C:\api\AA_Exporter\aa_exports\last_6_1_multi_order_cross_sell_20260326_1440.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_6_1_multi_order_cross_sell_20260326_1440.csv
총 데이터 row(FAILED row 제외, header 제외): 28
⏱ Elapsed: 0:00:53.357063
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_6_1_multi_order_cross_sell_20260326_1440.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,3316.0,4032409.09,...,28.0,60046.32,0.0,0.00,4.0,4738.05,0.0,0.00,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,305.0,335025.24,...,1.0,2047.99,0.0,0.00,0.0,0.00,0.0,0.00,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,3133.0,3084808.51,...,106.0,161926.99,5.0,9244.77,6.0,4519.49,3.0,9404.94,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,1335.0,1137080.90,...,13.0,16550.30,10.0,20611.45,7.0,4914.05,0.0,0.00,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,1698.0,2022574.13,...,36.0,42251.35,8.0,13857.74,7.0,14131.66,0.0,0.00,OK,NaN

#### **Total Order Cross Sell**

In [18]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_6_2_total_order_cross_sell.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:45:32
▶ Output: C:\api\AA_Exporter\aa_exports\last_6_2_total_order_cross_sell_20260326_1445.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_6_2_total_order_cross_sell_20260326_1445.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:24.529539
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_6_2_total_order_cross_sell_20260326_1445.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,0,NaN,9179.0,8734800.16,...,28.0,60046.32,0.0,0.00,4.0,4738.05,0.0,0.00,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,0,NaN,910.0,810883.78,...,1.0,2047.99,0.0,0.00,0.0,0.00,0.0,0.00,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,0,NaN,7422.0,5060597.91,...,106.0,161926.99,5.0,9244.77,6.0,4519.49,3.0,9404.94,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,0,NaN,6289.0,3589526.31,...,13.0,16550.30,10.0,20611.45,7.0,4914.05,0.0,0.00,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,0,NaN,3934.0,3240939.29,...,36.0,42251.35,8.0,13857.74,7.0,14131.66,0.0,0.00,OK,NaN

#### **CMP Order Cross Sell**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_6_3_cmp_order_cross_sell.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:46:38
▶ Output: C:\api\AA_Exporter\aa_exports\last_6_3_cmp_order_cross_sell_20260326_1446.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_6_3_cmp_order_cross_sell_20260326_1446.csv
총 데이터 row(FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:00:22.832664
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_6_3_cmp_order_cross_sell_20260326_1446.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),80.0,71528.41,...,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-02-22,2025-03-18,1250001,2025 (Jan 1-Dec 31),8.0,8482.24,...,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-02-26,1250001,2025 (Jan 1-Dec 31),181.0,124385.16,...,4.0,9184.98,0.0,0.00,0.0,0.00,1.0,2521.86,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-02-26,1250001,2025 (Jan 1-Dec 31),347.0,219522.85,...,4.0,4751.87,1.0,1714.05,2.0,2629.71,0.0,0.00,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-02-24,1250001,2025 (Jan 1-Dec 31),234.0,212346.05,...,1.0,851.09,0.0,0.00,2.0,7625.53,0.0,0.00,OK,NaN

## **7. Order Conversion/Traffic by Channel**

#### **Order BY Channel CMP**

In [20]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_7_1_order_by_channel_cmp.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:48:23
▶ Output: C:\api\AA_Exporter\aa_exports\last_7_1_order_by_channel_cmp_20260326_1448.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_7_1_order_by_channel_cmp_20260326_1448.csv
총 데이터 row(FAILED row 제외, header 제외): 437
⏱ Elapsed: 0:00:15.065989
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_7_1_order_by_channel_cmp_20260326_1448.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,11,Social Media Campaigns,6029.0,3.0,1425.64,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,5,Direct,3571.0,23.0,25207.79,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,21,Pmax,3337.0,25.0,21894.11,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1,Paid Search,1313.0,14.0,9270.90,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,4,Email,707.0,0.0,0.00,OK,NaN

## **Best Selling Product**

#### **Bestselling**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 형태 맞게 설정


json_file_name = "last_bestselling.json"

json_path = Path.cwd().parent / "json" / "last_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "last_site_code.csv"),
    json_file=str(json_path),
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:49:01
▶ Output: C:\api\AA_Exporter\aa_exports\last_bestselling_20260326_1449.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/30 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_bestselling_20260326_1449.csv
총 데이터 row(FAILED row 제외, header 제외): 7,999
⏱ Elapsed: 0:00:12.721467
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_bestselling_20260326_1449.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,833632946,SM-S938W,2956.0,4214307.45,21.0,32421.83,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,1802553923,TRADE-IN,1686.0,0.00,16.0,0.00,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,2977328126,SMC-CA,1132.0,96944.62,12.0,1215.17,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,644142495,SM-S931W,967.0,838121.05,1.0,978.99,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2025-02-22,2025-03-18,3981674007,SM-S936W,720.0,811846.90,12.0,13167.66,OK,NaN