In [ ]:
!pip install tqdm

## **1_1~2. S.com Traffic by Division**

#### **S.com DA Traffic & Order (App)**

In [2]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
import pandas as pd

json_file_name = "1_1_scom_da_traffic_app_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:00:45
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_app_prior_20260326_1400.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_app_prior_20260326_1400.csv
총 데이터 row(FAILED row 제외, header 제외): 27
⏱ Elapsed: 0:02:10.493044
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_app_prior_20260326_1400.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,3706.0,2860.0,...,9.0,1.0,72.0,43.0,25.0,105345.89,57517.27,44615.60,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,1130.0,869.0,...,0.0,1.0,20.0,11.0,8.0,41423.99,17986.65,23137.35,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,3673.0,3003.0,...,1.0,5.0,116.0,90.0,23.0,86192.98,58679.04,24340.74,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,1782.0,1260.0,...,0.0,0.0,54.0,34.0,15.0,58257.16,34233.45,20062.43,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,1978.0,1341.0,...,0.0,0.0,75.0,54.0,17.0,64638.55,52048.96,11095.30,OK,NaN

#### **S.com DA Traffic & Order (Web)**

In [3]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_da_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:03:46
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_web_prior_20260326_1403.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_web_prior_20260326_1403.csv
총 데이터 row(FAILED row 제외, header 제외): 42
⏱ Elapsed: 0:00:33.251966
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_da_traffic_web_prior_20260326_1403.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,107856.0,106012.0,...,93132.0,87524.0,65176.0,59332.0,187.0,212.0,155851.07,110994.13,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,6913.0,10271.0,...,4736.0,7696.0,2487.0,4388.0,23.0,19.0,17572.12,14052.26,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,15259.0,25127.0,...,10312.0,18030.0,4204.0,6270.0,200.0,210.0,170838.13,156549.98,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,7360.0,14403.0,...,4657.0,10497.0,893.0,3315.0,98.0,153.0,99246.65,126623.08,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,7805.0,10641.0,...,5612.0,7610.0,1785.0,2524.0,121.0,78.0,90965.52,54338.96,OK,NaN

#### **S.com MX Traffic & Order (App)**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_mx_traffic_app_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:06:14
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_app_prior_20260326_1406.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_app_prior_20260326_1406.csv
총 데이터 row(FAILED row 제외, header 제외): 28
⏱ Elapsed: 0:03:56.425287
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_app_prior_20260326_1406.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,82276.0,68356.0,...,92.0,74.0,1296.0,1104.0,113.0,992370.81,822916.67,126161.85,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,9261.0,7752.0,...,23.0,9.0,183.0,154.0,20.0,110803.70,86059.16,18619.64,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,28139.0,23445.0,...,9.0,2.0,679.0,579.0,36.0,342350.43,292556.83,21247.44,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,18269.0,14244.0,...,1.0,0.0,499.0,404.0,33.0,356388.99,272544.43,40017.11,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,14862.0,11695.0,...,6.0,5.0,474.0,390.0,37.0,415903.93,336116.93,36571.97,OK,NaN

#### **S.com MX Traffic & Order (Web)**

In [5]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_mx_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:10:44
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_web_prior_20260326_1410.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_web_prior_20260326_1410.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:32.266697
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_mx_traffic_web_prior_20260326_1410.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,192315.0,615978.0,...,141987.0,529760.0,47296.0,291864.0,2588.0,2610.0,2228588.53,2019150.34,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,19809.0,35483.0,...,14059.0,26238.0,7031.0,12615.0,179.0,147.0,135304.56,76370.41,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,58066.0,205300.0,...,41354.0,167563.0,11360.0,67843.0,839.0,1502.0,628435.70,882706.62,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,42870.0,133118.0,...,28537.0,108741.0,6117.0,41318.0,668.0,1015.0,556861.38,765511.35,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,29873.0,108505.0,...,21155.0,90270.0,5476.0,33231.0,332.0,459.0,274699.05,459556.64,OK,NaN

#### **S.com VD Traffic & Order (App)**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_vd_traffic_app_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:12:03
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_app_prior_20260326_1412.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_app_prior_20260326_1412.csv
총 데이터 row(FAILED row 제외, header 제외): 27
⏱ Elapsed: 0:05:00.732071
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_app_prior_20260326_1412.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,15242.0,11453.0,...,14.0,58.0,173.0,128.0,35.0,204482.87,145356.18,46124.33,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,2548.0,1883.0,...,4.0,6.0,28.0,21.0,5.0,23217.60,16567.68,5149.95,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,5800.0,4628.0,...,0.0,0.0,99.0,74.0,20.0,112977.42,79339.34,26993.43,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,2945.0,1991.0,...,1.0,0.0,47.0,37.0,8.0,55021.78,41543.66,8599.31,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,5742.0,3612.0,...,6.0,20.0,167.0,103.0,52.0,187291.45,110162.24,69716.65,OK,NaN

#### **S.com VD Traffic & Order (Web)**

In [7]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "1_1_scom_vd_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" /  json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:20:01
▶ Output: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_web_prior_20260326_1420.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_web_prior_20260326_1420.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:33.500336
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\1_1_scom_vd_traffic_web_prior_20260326_1420.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,209091.0,338345.0,...,181983.0,303445.0,123598.0,182582.0,621.0,512.0,847146.21,589526.26,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,10635.0,15829.0,...,7528.0,12162.0,4024.0,6801.0,45.0,46.0,41463.38,38392.52,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,23513.0,38435.0,...,16572.0,29831.0,5048.0,10092.0,228.0,201.0,248928.34,204828.26,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,19826.0,30454.0,...,12612.0,23109.0,2542.0,7150.0,130.0,123.0,177859.63,133526.56,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,15147.0,27519.0,...,11078.0,22088.0,3153.0,9013.0,180.0,131.0,184550.46,148890.35,OK,NaN

## **2_1~4. Basic Traffic**

#### Basic Traffic - S.com (Web & App) [w. Prior Period]

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "2_1_basic_traffic_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:21:43
▶ Output: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_scom_prior_20260326_1421.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_scom_prior_20260326_1421.csv
총 데이터 row(FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:03:26.642900
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_scom_prior_20260326_1421.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,672693.0,1794588.0,...,2254720.0,102606.0,253010.0,209333.0,18920.0,80529.0,63487.0,8484.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,60659.0,112080.0,...,352159.0,22427.0,55416.0,47018.0,2645.0,27841.0,23596.0,1211.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,132199.0,417832.0,...,2402711.0,80187.0,121583.0,104444.0,9681.0,37261.0,30242.0,6191.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,105133.0,292991.0,...,1030898.0,39230.0,94623.0,80224.0,5278.0,27529.0,23590.0,3080.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,69568.0,209979.0,...,1528485.0,56627.0,87010.0,68057.0,9887.0,28371.0,20822.0,6437.0,OK,NaN

#### **Basic Traffic  - S.com Time Spent per Visit (Web & App) [w. Prior Period]**

In [9]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "2_1_basic_traffic_time_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:25:55
▶ Output: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_scom_prior_20260326_1425.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_scom_prior_20260326_1425.csv
총 데이터 row(FAILED row 제외, header 제외): 60
⏱ Elapsed: 0:00:23.285447
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\2_1_basic_traffic_time_scom_prior_20260326_1425.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,1250001,2025 (Jan 1-Dec 31),239.345803,292.522415,212.307244,251.749553,251.956728,313.094362,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,1260001,2026 (Jan 1-Dec 31),250.723745,302.521217,229.862717,263.257266,263.806357,264.352060,OK,NaN
2,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,1250001,2025 (Jan 1-Dec 31),233.138979,266.897001,193.792724,295.209280,269.076581,385.960717,OK,NaN
3,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,1260001,2026 (Jan 1-Dec 31),225.480000,287.683893,189.032768,283.462547,277.712215,304.145161,OK,NaN
4,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,1260001,2026 (Jan 1-Dec 31),299.364482,401.679367,267.687507,280.058034,271.507224,376.033574,OK,NaN

## **3. Traffic by Channel**

#### **External Traffic by Channel - S.com (Web & App) [w. Prior Period]**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "3_2_channel_external_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:27:29
▶ Output: C:\api\AA_Exporter\aa_exports\3_2_channel_external_scom_prior_20260326_1427.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\3_2_channel_external_scom_prior_20260326_1427.csv
총 데이터 row(FAILED row 제외, header 제외): 874
⏱ Elapsed: 0:00:24.801645
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\3_2_channel_external_scom_prior_20260326_1427.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,11,Social Media Campaigns,538794.0,481928.0,1780.0,327.0,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,1,Paid Search,472896.0,236390.0,10170.0,2210.0,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,5,Direct,471762.0,315425.0,133733.0,50241.0,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,2,Natural Search,463305.0,102778.0,9049.0,1514.0,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,21,Pmax,125574.0,36969.0,7747.0,1467.0,OK,NaN

## **6. S.com Cross Sell Order**

#### **6-1. S.com Multi Order Cross-Sell (Total) [w. Prior Period]**

In [11]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "6_1_multi_order_cross_sell_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:28:49
▶ Output: C:\api\AA_Exporter\aa_exports\6_1_multi_order_cross_sell_prior_20260326_1428.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\6_1_multi_order_cross_sell_prior_20260326_1428.csv
총 데이터 row(FAILED row 제외, header 제외): 38
⏱ Elapsed: 0:00:59.672154
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\6_1_multi_order_cross_sell_prior_20260326_1428.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,2363.0,2962623.50,...,11.0,16942.80,5.0,13462.65,4.0,6003.91,0.0,0.00,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,183.0,206132.74,...,2.0,1099.97,1.0,4199.96,0.0,0.00,0.0,0.00,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,1104.0,1025979.04,...,5.0,13925.14,5.0,13979.41,2.0,3378.20,0.0,0.00,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,738.0,806313.15,...,2.0,60.55,12.0,22286.42,20.0,52619.78,3.0,13886.33,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,703.0,870796.44,...,8.0,10316.96,16.0,27818.10,2.0,1718.44,0.0,0.00,OK,NaN

#### **6-2. S.com All Order Cross-Sell (Total) [w. Prior Period]**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "6_2_total_order_cross_sell_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:30:33
▶ Output: C:\api\AA_Exporter\aa_exports\6_2_total_order_cross_sell_prior_20260326_1430.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\6_2_total_order_cross_sell_prior_20260326_1430.csv
총 데이터 row(FAILED row 제외, header 제외): 38
⏱ Elapsed: 0:00:24.719074
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\6_2_total_order_cross_sell_prior_20260326_1430.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,0,NaN,8562.0,7310399.39,...,11.0,16942.80,5.0,13462.65,4.0,6003.91,0.0,0.00,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2025-12-08,2026-01-01,0,NaN,711.0,500280.33,...,2.0,1099.97,1.0,4199.96,0.0,0.00,0.0,0.00,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-11,2026-01-18,0,NaN,4142.0,2815232.84,...,5.0,13925.14,5.0,13979.41,2.0,3378.20,0.0,0.00,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-13,2026-01-19,0,NaN,2897.0,2275010.27,...,2.0,60.55,12.0,22286.42,20.0,52619.78,3.0,13886.33,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-11,2026-01-18,0,NaN,2015.0,1844157.91,...,8.0,10316.96,16.0,27818.10,2.0,1718.44,0.0,0.00,OK,NaN

## **7_1~2. Order Conversion/Traffic by Channel**

#### **S.com Order Conversion by Channel (Web & App) [w. Prior Period]**

In [13]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "7_1_order_by_channel_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:32:54
▶ Output: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_scom_prior_20260326_1432.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_scom_prior_20260326_1432.csv
총 데이터 row(FAILED row 제외, header 제외): 874
⏱ Elapsed: 0:00:28.438778
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\7_1_order_by_channel_scom_prior_20260326_1432.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,11,Social Media Campaigns,538794.0,1780.0,73.0,18.0,71099.53,19402.43,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,1,Paid Search,472896.0,10170.0,1692.0,158.0,1578379.42,150344.28,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,5,Direct,471762.0,133734.0,1128.0,651.0,971876.34,543095.46,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,2,Natural Search,463305.0,9049.0,1900.0,100.0,1550087.82,86662.43,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,21,Pmax,125574.0,7747.0,893.0,82.0,844531.06,85969.12,OK,NaN

#### **Campaign Multi Order (Total) [w. Prior Period]**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "multi_purchase_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:33:44
▶ Output: C:\api\AA_Exporter\aa_exports\multi_purchase_prior_20260326_1433.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/43 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\multi_purchase_prior_20260326_1433.csv
총 데이터 row(FAILED row 제외, header 제외): 11,846
⏱ Elapsed: 0:01:10.353107
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\multi_purchase_prior_20260326_1433.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,2732371547,HAF-QIN/EXP,0.0,0.0,0.0,272.0,112.0,11920.55,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,4161418187,HAF-CIN/EXP,0.0,0.0,0.0,66.0,27.0,2889.02,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,3852794278,SM-A166WZKAXAC,0.0,0.0,0.0,55.0,22.0,10999.45,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,1858662333,SM-X230NZAAXAC,0.0,0.0,0.0,44.0,13.0,10974.56,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2025-12-08,2026-01-01,717674559,"SM-F966WDBEXAC,TRADE-IN,P-GT-AXXCS1FK",0.0,0.0,0.0,26.0,13.0,18912.55,OK,NaN