In [ ]:
!pip install tqdm

## **1_1~2. S.com Traffic by Division**

#### **S.com DA Traffic & Order (Web)**

In [1]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_1_1_scom_da_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 13:50:35
▶ Output: C:\api\AA_Exporter\aa_exports\us_1_1_scom_da_traffic_web_20260326_1350.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_1_1_scom_da_traffic_web_20260326_1350.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:15.030279
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_1_1_scom_da_traffic_web_20260326_1350.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,138027.0,138342.0,...,118320.0,117302.0,48230.0,39282.0,1016.0,1623.0,661142.19,427003.84,OK,NaN

#### **S.com MX Traffic & Order (Web)**

In [2]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_1_1_scom_mx_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:00:50
▶ Output: C:\api\AA_Exporter\aa_exports\us_1_1_scom_mx_traffic_web_20260326_1400.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_1_1_scom_mx_traffic_web_20260326_1400.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:05.421525
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_1_1_scom_mx_traffic_web_20260326_1400.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,409116.0,1841468.0,...,331690.0,1716603.0,141556.0,1209961.0,3192.0,5841.0,2020754.38,2352419.02,OK,NaN

#### **S.com VD Traffic & Order (Web)**

In [3]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_1_1_scom_vd_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" /  json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:01:06
▶ Output: C:\api\AA_Exporter\aa_exports\us_1_1_scom_vd_traffic_web_20260326_1401.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_1_1_scom_vd_traffic_web_20260326_1401.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:07.353665
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_1_1_scom_vd_traffic_web_20260326_1401.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,209009.0,366201.0,...,175107.0,330244.0,61530.0,124346.0,1551.0,5212.0,947840.04,808024.54,OK,NaN

## **2_1~4. Basic Traffic**

## Basic Traffic - Campaign Page (w. CID) (Web & App)

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_2_1_basic_traffic_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:02:46
▶ Output: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_cmp_20260326_1402.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_cmp_20260326_1402.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.524580
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_cmp_20260326_1402.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,2852.0,9259.0,...,2680.0,8598.0,3603.0,11226.0,502.0,1679.0,172.0,660.0,OK,NaN

#### **Basic Traffic - S.com (Web & App)**

In [5]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_2_1_basic_traffic_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:03:27
▶ Output: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_scom_20260326_1403.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_scom_20260326_1403.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:03.862576
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_scom_20260326_1403.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,1282118.0,3612887.0,...,843007.0,1896145.0,2390601.0,5013209.0,1282118.0,3612887.0,439078.0,1716660.0,OK,NaN

## Basic Traffic  - Campaign Page Time Spent per Visit (Web & App)

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_2_1_basic_traffic_time_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:06:31
▶ Output: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_cmp_20260326_1406.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_cmp_20260326_1406.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:07.510117
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_cmp_20260326_1406.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,118.958457,142.510529,111.27506,OK,NaN

#### **Basic Traffic  - S.com Time Spent per Visit (Web & App)**

In [7]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_2_1_basic_traffic_time_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:07:07
▶ Output: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_scom_20260326_1407.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_scom_20260326_1407.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:08.274258
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_scom_20260326_1407.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,239.403392,298.698334,213.497586,OK,NaN

## **3. Traffic by Channel**

#### **Internal Traffic (Web)**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_3_1_channel_internal_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:07:21
▶ Output: C:\api\AA_Exporter\aa_exports\us_3_1_channel_internal_web_20260326_1407.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_3_1_channel_internal_web_20260326_1407.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:08.396113
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_3_1_channel_internal_web_20260326_1407.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,79.0,1466.0,25.0,12.0,225.0,3547.0,590.0,25.0,OK,NaN

#### **External Traffic by Channel - Campaign Page (Web & App)**

In [9]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_3_2_channel_external_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:07:37
▶ Output: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_cmp_20260326_1407.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_cmp_20260326_1407.csv
총 데이터 row(FAILED row 제외, header 제외): 16
⏱ Elapsed: 0:00:07.477955
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_cmp_20260326_1407.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,5,Direct,293.0,106.0,434.0,248.0,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,6,Session Refresh,78.0,25.0,356.0,133.0,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,2,Natural Search,55.0,11.0,143.0,64.0,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,23,Email - CRM,35.0,18.0,51.0,24.0,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,8,Referring Domains,26.0,5.0,6.0,1.0,OK,NaN

#### **External Traffic by Channel - S.com (Web & App)**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_3_2_channel_external_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:07:49
▶ Output: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_scom_20260326_1407.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_scom_20260326_1407.csv
총 데이터 row(FAILED row 제외, header 제외): 18
⏱ Elapsed: 0:00:13.813382
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_scom_20260326_1407.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,5,Direct,1344086.0,631368.0,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,2,Natural Search,1096872.0,114412.0,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,18,Social (Paid),668652.0,610626.0,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1,Paid Search,384205.0,112257.0,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,19,Push Notifications,331342.0,202431.0,OK,NaN

#### **3. Home KV & GNB to cmp Page**

In [11]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_3_3_homepage_kv_gnb_to_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:09:12
▶ Output: C:\api\AA_Exporter\aa_exports\us_3_3_homepage_kv_gnb_to_cmp_20260326_1409.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_3_3_homepage_kv_gnb_to_cmp_20260326_1409.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.270373
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_3_3_homepage_kv_gnb_to_cmp_20260326_1409.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,244914.0,402390.0,1466.0,3547.0,79.0,225.0,OK,NaN

## **4. Order Conversion with Login/Non-Login**

#### **Order Conversion - cmp Page > PD / ATC Page, cmp Page & S.com Order (Total)**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_4_1_order_cvr_loginout.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:09:28
▶ Output: C:\api\AA_Exporter\aa_exports\us_4_1_order_cvr_loginout_20260326_1409.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_4_1_order_cvr_loginout_20260326_1409.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.173687
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_4_1_order_cvr_loginout_20260326_1409.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value10,value11,value12,value13,value14,value15,value16,value17,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,372.0,452.0,...,56675.93,6620.2,19440.0,11161.0,8279.0,7209694.71,5648058.78,1561635.93,OK,NaN

#### **(4_2.) Order Conversion - Visit/Visitor by Login & Non-login (Total)**

In [13]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_4_2_order_cvr_visit_visitor.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:10:36
▶ Output: C:\api\AA_Exporter\aa_exports\us_4_2_order_cvr_visit_visitor_20260326_1410.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_4_2_order_cvr_visit_visitor_20260326_1410.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:01.500655
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_4_2_order_cvr_visit_visitor_20260326_1410.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,1156.0,10955.0,770.0,10340.0,182090.0,4712915.0,OK,NaN

## 5. S.COM ORDER CONVERSION IN cmp PERIOD

#### **S.com Order Conversion - Order & Revenue (Total & APP)**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_5_1_campaign_order_cvr_total.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:11:15
▶ Output: C:\api\AA_Exporter\aa_exports\us_5_1_campaign_order_cvr_total_20260326_1411.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_5_1_campaign_order_cvr_total_20260326_1411.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:01.679070
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_5_1_campaign_order_cvr_total_20260326_1411.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,19440.0,7209694.71,6411.0,47.0,55.0,27.0,38.0,OK,NaN

## **6. S.com Cross Sell Order**

#### **6-1. Multi Order Cross-Sell (Total)**

In [15]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_6_1_multi_order_cross_sell.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:11:22
▶ Output: C:\api\AA_Exporter\aa_exports\us_6_1_multi_order_cross_sell_20260326_1411.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_6_1_multi_order_cross_sell_20260326_1411.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:21.836113
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_6_1_multi_order_cross_sell_20260326_1411.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,6411.0,6007347.3,...,14.0,7997.82,17.0,55702.0,7.0,3929.65,1.0,81.27,OK,NaN

#### **6-2. All Order Cross-Sell (Total)**

In [16]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_6_2_total_order_cross_sell.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:11:56
▶ Output: C:\api\AA_Exporter\aa_exports\us_6_2_total_order_cross_sell_20260326_1411.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_6_2_total_order_cross_sell_20260326_1411.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.151065
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_6_2_total_order_cross_sell_20260326_1411.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,19440.0,7209694.71,...,14.0,7997.82,17.0,55702.0,7.0,3929.65,1.0,81.27,OK,NaN

#### **6-3. cmp Visit & Order Cross-Sell (Total)**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_6_3_cmp_order_cross_sell.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:12:16
▶ Output: C:\api\AA_Exporter\aa_exports\us_6_3_cmp_order_cross_sell_20260326_1412.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_6_3_cmp_order_cross_sell_20260326_1412.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:03.051592
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_6_3_cmp_order_cross_sell_20260326_1412.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,55.0,63296.13,...,1.0,36.22,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

## **7_1~2. Order Conversion/Traffic by Channel**

#### **Order Conversion by Channel - cmp Page (Web & App)**

In [18]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_7_1_order_by_channel_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:12:24
▶ Output: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_cmp_20260326_1412.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_cmp_20260326_1412.csv
총 데이터 row(FAILED row 제외, header 제외): 17
⏱ Elapsed: 0:00:01.456307
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_cmp_20260326_1412.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,5,Direct,1684.0,3173.0,9.0,12.0,10335.68,11783.25,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,2,Natural Search,476.0,1344.0,5.0,2.0,4931.03,3006.99,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,6,Session Refresh,242.0,1075.0,1.0,1.0,15.55,9804.97,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1,Paid Search,105.0,263.0,2.0,1.0,4080.89,1527.74,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,16,Affiliate,98.0,482.0,6.0,9.0,4588.81,10088.09,OK,NaN

#### **Order Conversion by Channel - S.com (Web & App)**

In [20]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_7_1_order_by_channel_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:12:58
▶ Output: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_scom_20260326_1412.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_scom_20260326_1412.csv
총 데이터 row(FAILED row 제외, header 제외): 18
⏱ Elapsed: 0:00:01.662946
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_scom_20260326_1412.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,5,Direct,1344086.0,7655.0,2029594.14,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,2,Natural Search,1096872.0,2434.0,1344792.89,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,18,Social (Paid),668652.0,4.0,3050.88,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1,Paid Search,384205.0,1832.0,1534064.05,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,19,Push Notifications,331342.0,46.0,27398.91,OK,NaN

## 8. cmp PAGE ADAPTIVE BANNER PERFORMANCE

## Login CTA > Login Success / Marketing Consent CTA > Pop-up CTA

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_8_1_login_cta.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:13:06
▶ Output: C:\api\AA_Exporter\aa_exports\us_8_1_login_cta_20260326_1413.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_8_1_login_cta_20260326_1413.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:10.677007
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_8_1_login_cta_20260326_1413.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,12111.0,46.0,17.0,1.0,0.0,0.0,OK,NaN

## Nextpage, Multiorder, Best Selling Products

## Next page

In [22]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "us_nextpage.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:13:27
▶ Output: C:\api\AA_Exporter\aa_exports\us_nextpage_20260326_1413.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_nextpage_20260326_1413.csv
총 데이터 row(FAILED row 제외, header 제외): 606
⏱ Elapsed: 0:00:01.627624
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_nextpage_20260326_1413.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1305170805,https://www.samsung.com/us/offer/new-year-new-...,2917.0,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,206243805,www.samsung.com/us,2203.0,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,331009310,https://www.samsung.com/us/offer/,388.0,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1096879890,https://www.samsung.com/us/mobile/phones/all-p...,213.0,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,3384632923,https://www.samsung.com/us/shop/featured-offers/,143.0,OK,NaN

#### **cmp Multi Order (Total)**

In [23]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "us_multi_purchase.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:13:34
▶ Output: C:\api\AA_Exporter\aa_exports\us_multi_purchase_20260326_1413.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_multi_purchase_20260326_1413.csv
총 데이터 row(FAILED row 제외, header 제외): 5,384
⏱ Elapsed: 0:00:02.523094
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_multi_purchase_20260326_1413.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,574116155,"SM-R630NZAAXAR,BUDS3PRO-IFIT-OFFER",0.0,0.0,0.0,204.0,102.0,23302.38,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,3861630432,"SM-X528UZAAVZW,PC-OFFER-SIRIUSXM6MOS,ABCM-OFFE...",0.0,0.0,0.0,72.0,18.0,535.82,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,4041002594,"NP960QHA-KG1US,GD-OFFER-PC",0.0,0.0,0.0,68.0,34.0,42372.56,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1098094531,"SM-X528UZAAVZW,ABCM-OFFER-TAB,GD-OFFER-TAB,PC-...",0.0,0.0,0.0,68.0,17.0,0.00,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,4224325437,"SM-X528UZAAVZW,GD-OFFER-TAB,ABCM-OFFER-TAB,PC-...",0.0,0.0,0.0,56.0,14.0,0.00,OK,NaN

## Best Selling Product

In [24]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "us_bestselling.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:13:43
▶ Output: C:\api\AA_Exporter\aa_exports\us_bestselling_20260326_1413.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_bestselling_20260326_1413.csv
총 데이터 row(FAILED row 제외, header 제외): 2,660
⏱ Elapsed: 0:00:01.870872
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_bestselling_20260326_1413.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,3864011536,QN43Q7FAAFXZA,5274.0,3311.43,2.0,0.0,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1435662958,SM-X528UZAAVZW,3181.0,2399.96,1.0,0.0,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,743259034,2-MO-ADOBE-LR,2905.0,0.00,20.0,0.0,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,788511896,ARCSITE_PREMIUM_30DAY,2861.0,0.00,20.0,0.0,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,4011924632,LUMAFUSION_HALF_OFF,2854.0,0.00,21.0,0.0,OK,NaN