In [ ]:
!pip install tqdm

## **1_1~2. S.com Traffic by Division**

#### **S.com DA Traffic & Order (Web)**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_1_1_scom_da_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 16:58:02
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_da_traffic_web_20260330_1658.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_da_traffic_web_20260330_1658.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:09.640561
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_da_traffic_web_20260330_1658.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,138027.0,138342.0,...,118320.0,117302.0,48230.0,39282.0,1016.0,1623.0,661142.19,427003.84,OK,NaN

#### **S.com MX Traffic & Order (Web)**

In [18]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_1_1_scom_mx_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 16:58:18
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_mx_traffic_web_20260330_1658.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_mx_traffic_web_20260330_1658.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:04.926505
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_mx_traffic_web_20260330_1658.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,409116.0,1841468.0,...,331690.0,1716603.0,141556.0,1209961.0,3192.0,5841.0,2020754.38,2352419.02,OK,NaN

#### **S.com VD Traffic & Order (Web)**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_1_1_scom_vd_traffic_web.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" /  json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 16:58:30
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_vd_traffic_web_20260330_1658.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_vd_traffic_web_20260330_1658.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:07.590758
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_1_1_scom_vd_traffic_web_20260330_1658.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-19,2026-01-26,1260001,2026,209009.0,366201.0,...,175107.0,330244.0,61530.0,124346.0,1551.0,5212.0,947840.04,808024.54,OK,NaN

## **2_1~4. Basic Traffic**

In [20]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_2_1_basic_traffic_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:05:09
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_cmp_20260330_1705.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_cmp_20260330_1705.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:06.940507
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_cmp_20260330_1705.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

#### **Basic Traffic - S.com (Web & App)**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_2_1_basic_traffic_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:05:27
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_scom_20260330_1705.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_scom_20260330_1705.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:05.687168
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_scom_20260330_1705.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,2353810.0,10016634.0,...,2122193.0,9189412.0,6184536.0,15395676.0,2353810.0,10016634.0,231602.0,827140.0,OK,NaN

#### **Basic Traffic  - S.com Time Spent per Visit (Web & App)**

In [22]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_2_1_basic_traffic_time_scom.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:06:03
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_time_scom_20260330_1706.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_time_scom_20260330_1706.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:01.941236
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_2_1_basic_traffic_time_scom_20260330_1706.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,187.799679,310.825183,155.801343,OK,NaN

## **3. Traffic by Channel**

#### **Internal Traffic (Web)**

In [15]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_3_1_channel_internal.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 15:57:27
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_3_1_channel_internal_20260330_1557.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_3_1_channel_internal_20260330_1557.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:08.699557
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_3_1_channel_internal_20260330_1557.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

#### **External Traffic by Channel - S.com (Web & App)**

In [7]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_3_2_channel_traffic_external.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 15:49:03
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_3_2_channel_traffic_external_20260330_1549.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_3_2_channel_traffic_external_20260330_1549.csv
총 데이터 row(FAILED row 제외, header 제외): 18
⏱ Elapsed: 0:00:06.291984
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_3_2_channel_traffic_external_20260330_1549.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,5,Direct,2468275.0,235133.0,OK,NaN
1,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,11,Display,2197119.0,213246.0,OK,NaN
2,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,2,Natural Search,1999010.0,79367.0,OK,NaN
3,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,18,Social (Paid),1221189.0,101113.0,OK,NaN
4,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1,Paid Search,1111319.0,39790.0,OK,NaN

#### **3. Home KV & GNB to cmp Page**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_3_3_homepage_kv_gnb_to_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-27 08:24:13
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_3_3_homepage_kv_gnb_to_cmp_20260327_0824.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_3_3_homepage_kv_gnb_to_cmp_20260327_0824.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.461406
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_3_3_homepage_kv_gnb_to_cmp_20260327_0824.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,483973.0,942676.0,0.0,0.0,OK,NaN

## **4. Order Conversion with Login/Non-Login**

#### **Order Conversion - cmp Page > PD / ATC Page, cmp Page & S.com Order (Total)**

In [23]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_4_1_order_cvr_loginout.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:09:46
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_4_1_order_cvr_loginout_20260330_1709.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_4_1_order_cvr_loginout_20260330_1709.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:03.240910
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_4_1_order_cvr_loginout_20260330_1709.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value10,value11,value12,value13,value14,value15,value16,value17,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,0.0,0.0,...,0.0,0.0,64058.0,45443.0,18615.0,50960081.9,37313220.41,13646861.49,OK,NaN

#### **(4_2.) Order Conversion - Visit/Visitor by Login & Non-login (Total)**

In [24]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_4_2_order_cvr_visit_visitor.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:09:56
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_4_2_order_cvr_visit_visitor_20260330_1709.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_4_2_order_cvr_visit_visitor_20260330_1709.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.370770
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_4_2_order_cvr_visit_visitor_20260330_1709.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,64058.0,45443.0,18615.0,50960081.9,37313220.41,13646861.49,399657.0,11970787.0,OK,NaN

## 5. S.COM ORDER CONVERSION IN cmp PERIOD

#### **S.com Order Conversion - Order & Revenue (Total & APP)**

In [25]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_5_1_campaign_order_cvr_total.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:10:11
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_5_1_campaign_order_cvr_total_20260330_1710.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_5_1_campaign_order_cvr_total_20260330_1710.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.007838
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_5_1_campaign_order_cvr_total_20260330_1710.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,12370444.0,64058.0,50960081.9,54691.0,OK,NaN

## **6. S.com Cross Sell Order**

#### **6-1. Multi Order Cross-Sell (Total)**

In [26]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_6_1_multi_order_cross_sell.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:10:20
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_6_1_multi_order_cross_sell_20260330_1710.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_6_1_multi_order_cross_sell_20260330_1710.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:24.033621
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_6_1_multi_order_cross_sell_20260330_1710.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,54691.0,49337027.71,...,30.0,33904.84,12.0,15741.27,16.0,19778.05,0.0,0.0,OK,NaN

#### **6-2. All Order Cross-Sell (Total)**

In [27]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_6_2_total_order_cross_sell.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:10:54
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_6_2_total_order_cross_sell_20260330_1710.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_6_2_total_order_cross_sell_20260330_1710.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.876130
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_6_2_total_order_cross_sell_20260330_1710.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1250001,2025,64058.0,50960081.9,...,30.0,33904.84,12.0,15741.27,16.0,19778.05,0.0,0.0,OK,NaN

## **7_1~2. Order Conversion/Traffic by Channel**

#### **Order Conversion by Channel - cmp Page (Web & App)**

In [28]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "last_us_7_1_order_by_channel_cmp.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:11:57
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_7_1_order_by_channel_cmp_20260330_1711.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_7_1_order_by_channel_cmp_20260330_1711.csv
총 데이터 row(FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:02.060670
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_7_1_order_by_channel_cmp_20260330_1711.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, status, error]
Index: []

## Best Selling Product

In [29]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "last_us_bestselling.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "last_us_main" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_last_site_code.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-30 17:12:25
▶ Output: C:\api\AA_Exporter\aa_exports\last_us_bestselling_20260330_1712.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\last_us_bestselling_20260330_1712.csv
총 데이터 row(FAILED row 제외, header 제외): 43,305
⏱ Elapsed: 0:00:11.269829
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\last_us_bestselling_20260330_1712.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,2990790841,3MOS-PCKPREM-TAB-OFFER,49172.0,0.00,0.0,0.0,OK,NaN
1,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,743259034,2-MO-ADOBE-LR,49052.0,0.00,0.0,0.0,OK,NaN
2,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,4126757957,PC-OFFER-SIRIUSXM,46373.0,0.00,0.0,0.0,OK,NaN
3,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,3787077948,SM-R630NZAAXAR,12283.0,586436.17,0.0,0.0,OK,NaN
4,SEA,US,US,sssamsungnewus,2025-01-19,2025-01-26,1387889035,SM-S938UAKEXAA,10392.0,7676106.03,0.0,0.0,OK,NaN