In [ ]:
!pip install tqdm

## **1_1~2. S.com Traffic by Division**

#### **S.com DA Traffic & Order (Web)**

In [1]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_1_1_scom_da_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:21:37
▶ Output: C:\api\AA_Exporter\aa_exports\us_1_1_scom_da_traffic_web_prior_20260326_1421.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_1_1_scom_da_traffic_web_prior_20260326_1421.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:10.620290
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_1_1_scom_da_traffic_web_prior_20260326_1421.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1260001,2026,129627.0,141582.0,...,110940.0,119905.0,40658.0,41439.0,1012.0,1702.0,656602.53,531364.33,OK,NaN

#### **S.com MX Traffic & Order (Web)**

In [2]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_1_1_scom_mx_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:21:55
▶ Output: C:\api\AA_Exporter\aa_exports\us_1_1_scom_mx_traffic_web_prior_20260326_1421.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_1_1_scom_mx_traffic_web_prior_20260326_1421.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:14.303099
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_1_1_scom_mx_traffic_web_prior_20260326_1421.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1260001,2026,373886.0,1514316.0,...,298101.0,1397591.0,105137.0,846090.0,3574.0,5847.0,2375501.15,2754985.26,OK,NaN

#### **S.com VD Traffic & Order (Web)**

In [3]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_1_1_scom_vd_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" /  json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:22:40
▶ Output: C:\api\AA_Exporter\aa_exports\us_1_1_scom_vd_traffic_web_prior_20260326_1422.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_1_1_scom_vd_traffic_web_prior_20260326_1422.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:20.220669
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_1_1_scom_vd_traffic_web_prior_20260326_1422.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1260001,2026,199324.0,307475.0,...,166081.0,271299.0,56320.0,91254.0,1249.0,4088.0,868248.0,752854.84,OK,NaN

## **2_1~4. Basic Traffic**

#### **Basic Traffic - S.com (Web) [w. Prior Period]**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_2_1_basic_traffic_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:25:49
▶ Output: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_scom_prior_20260326_1425.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_scom_prior_20260326_1425.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:03.787823
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_scom_prior_20260326_1425.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1260001,2026,1279455.0,3100329.0,...,844831.0,1860622.0,2361025.0,4492850.0,1279455.0,3100329.0,434597.0,1239648.0,OK,NaN

#### **Basic Traffic  - S.com Time Spent per Visit (Web) [w. Prior Period]**

In [5]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_2_1_basic_traffic_time_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:26:16
▶ Output: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_scom_prior_20260326_1426.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_scom_prior_20260326_1426.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:01.517456
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_2_1_basic_traffic_time_scom_prior_20260326_1426.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1260001,2026,241.570438,294.393332,218.079923,OK,NaN

## **3. Traffic by Channel**

#### **External Traffic by Channel - S.com (Web) [w. Prior Period]**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_3_2_channel_external_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:26:23
▶ Output: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_scom_prior_20260326_1426.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_scom_prior_20260326_1426.csv
총 데이터 row(FAILED row 제외, header 제외): 19
⏱ Elapsed: 0:00:01.404359
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_3_2_channel_external_scom_prior_20260326_1426.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,5,Direct,1365333.0,627102.0,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,2,Natural Search,1162056.0,121846.0,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,18,Social (Paid),384668.0,345517.0,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1,Paid Search,354887.0,88608.0,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,19,Push Notifications,269390.0,170260.0,OK,NaN

## **6. S.com Cross Sell Order**

#### **6-1. S.com Multi Order Cross-Sell (Total) [w. Prior Period]**

In [7]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_6_1_multi_order_cross_sell_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:26:28
▶ Output: C:\api\AA_Exporter\aa_exports\us_6_1_multi_order_cross_sell_prior_20260326_1426.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_6_1_multi_order_cross_sell_prior_20260326_1426.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:03.167408
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_6_1_multi_order_cross_sell_prior_20260326_1426.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1260001,2026,7606.0,6686162.87,...,14.0,7338.04,17.0,43363.75,7.0,3691.87,0.0,0.0,OK,NaN

#### **6-2. S.com All Order Cross-Sell (Total) [w. Prior Period]**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_6_2_total_order_cross_sell_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:26:54
▶ Output: C:\api\AA_Exporter\aa_exports\us_6_2_total_order_cross_sell_prior_20260326_1426.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_6_2_total_order_cross_sell_prior_20260326_1426.csv
총 데이터 row(FAILED row 제외, header 제외): 1
⏱ Elapsed: 0:00:02.277064
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_6_2_total_order_cross_sell_prior_20260326_1426.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1260001,2026,18369.0,7965455.37,...,14.0,7338.04,17.0,43363.75,7.0,3691.87,0.0,0.0,OK,NaN

## **7_1~2. Order Conversion/Traffic by Channel**

#### **S.com Order Conversion by Channel (Web) [w. Prior Period]**

In [9]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd




json_file_name = "us_7_1_order_by_channel_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:27:04
▶ Output: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_scom_prior_20260326_1427.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_scom_prior_20260326_1427.csv
총 데이터 row(FAILED row 제외, header 제외): 19
⏱ Elapsed: 0:00:02.692597
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_7_1_order_by_channel_scom_prior_20260326_1427.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,5,Direct,1365333.0,6611.0,2221705.87,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,2,Natural Search,1162056.0,2772.0,1560023.94,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,18,Social (Paid),384668.0,6.0,1239.78,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1,Paid Search,354887.0,2161.0,1832117.86,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,19,Push Notifications,269390.0,78.0,29191.82,OK,NaN

#### **Campaign Multi Order (Total) [w. Prior Period]**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter

import pandas as pd

base = ""  # 테이블 명에 맞게 수정


json_file_name = "us_multi_purchase_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd().parent / "json" / "us_main_prior" / json_file_name

cfg = ExportConfig(
    data_csv=str(Path.cwd().parent / "date" / "us_site_code_prior.csv"),
    json_file=str(json_path), 
    out_dir=str(Path.cwd().parent / "aa_exports"),
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-26 14:27:11
▶ Output: C:\api\AA_Exporter\aa_exports\us_multi_purchase_prior_20260326_1427.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites):   0%|          | 0/1 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: C:\api\AA_Exporter\aa_exports\us_multi_purchase_prior_20260326_1427.csv
총 데이터 row(FAILED row 제외, header 제외): 6,271
⏱ Elapsed: 0:00:03.823704
❌ 실패 site: 0
DONE: C:\api\AA_Exporter\aa_exports\us_multi_purchase_prior_20260326_1427.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,574116155,"SM-R630NZAAXAR,BUDS3PRO-IFIT-OFFER",0.0,0.0,0.0,388.0,194.0,35634.68,OK,NaN
1,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,1066271128,"SM-L500NZKAXAA,WATCHES-IFIT-OFFER",0.0,0.0,0.0,90.0,45.0,16318.28,OK,NaN
2,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,89260503,"SM-R630NZWAXAR,BUDS3PRO-IFIT-OFFER",0.0,0.0,0.0,88.0,44.0,7822.60,OK,NaN
3,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,4224325437,"SM-X528UZAAVZW,GD-OFFER-TAB,ABCM-OFFER-TAB,PC-...",0.0,0.0,0.0,76.0,19.0,46.16,OK,NaN
4,SEA,US,US,sssamsungnewus,2026-01-11,2026-01-18,3937848504,"SM-L320NDAAXAA,WATCHES-IFIT-OFFER",0.0,0.0,0.0,70.0,35.0,8177.87,OK,NaN