In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic APP**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_da_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-06 15:43:15
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_app_20260306_154315.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [13:40<00:00, 17.85s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_app_20260306_154315.csv
총 데이터 row (FAILED row 제외, header 제외): 28
⏱ Elapsed: 0:13:41.360809
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_app_20260306_154315.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,5772.0,5456.0,...,1.0,1.0,5.0,5.0,0.0,4.087300e+04,4.087300e+04,0.000000e+00,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,5061.0,3839.0,...,2.0,0.0,172.0,124.0,31.0,1.530661e+05,1.091304e+05,2.422029e+04,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,4775.0,3308.0,...,3.0,14.0,189.0,116.0,56.0,1.671448e+05,1.142309e+05,4.495105e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,0,NaN,9277.0,7571.0,...,0.0,7.0,168.0,121.0,32.0,1.402396e+05,9.882924e+04,3.002583e+04,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,243763.0,226255.0,...,89419.0,2377.0,4972.0,4000.0,972.0,5.518781e+09,4.319906e+09,1.198875e+09,OK,NaN

In [5]:
#### **Scom DA Traffic WEB**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_da_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:56:57
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_web_20260306_155657.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:26<00:00,  1.73site/s, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_web_20260306_155657.csv
총 데이터 row (FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:00:26.763731
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_web_20260306_155657.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,19982.0,20116.0,...,14778.0,4018.0,7470.0,2510.0,9.0,8.0,1.342658e+05,1.213861e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,21727.0,44542.0,...,13439.0,31761.0,1603.0,6706.0,230.0,353.0,1.985412e+05,3.052828e+05,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,17956.0,26937.0,...,13082.0,20263.0,4201.0,7352.0,213.0,152.0,1.764429e+05,1.233535e+05,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,0,NaN,43322.0,63140.0,...,29627.0,44688.0,12552.0,15830.0,403.0,412.0,3.612648e+05,3.421153e+05,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,460664.0,898680.0,...,346013.0,753241.0,209149.0,377517.0,4685.0,11862.0,5.423614e+09,1.341480e+10,OK,NaN

In [7]:
#### **Scom MX Traffic APP**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_mx_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:57:24
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_app_20260306_155724.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [05:39<00:00,  7.38s/site, ok=1, rows=1, site=SG]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_app_20260306_155724.csv
총 데이터 row (FAILED row 제외, header 제외): 31
⏱ Elapsed: 0:05:39.757110
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_app_20260306_155724.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,192351.0,178249.0,...,4.0,22.0,1558.0,1395.0,161.0,4.609409e+06,3.699109e+06,9.059586e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,42990.0,34292.0,...,8.0,0.0,717.0,616.0,23.0,4.463180e+05,3.710261e+05,2.386340e+04,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,27755.0,22392.0,...,27.0,6.0,726.0,601.0,40.0,7.797158e+05,6.354046e+05,4.930748e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,0,NaN,80169.0,66936.0,...,22.0,2.0,1781.0,1549.0,95.0,1.065033e+06,8.998827e+05,7.531585e+04,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,1497019.0,1461357.0,...,89858.0,2725.0,36582.0,34330.0,2252.0,4.711210e+10,4.375493e+10,3.357167e+09,OK,NaN

In [9]:
#### **Scom MX Traffic WEB**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_mx_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:04
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_web_20260306_160304.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:36<00:00,  1.26site/s, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_web_20260306_160304.csv
총 데이터 row (FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:00:36.704236
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_web_20260306_160304.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0.0,NaN,194195.0,518313.0,...,117785.0,275770.0,52097.0,169639.0,920.0,828.0,6.520484e+06,4.120123e+06,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0.0,NaN,116777.0,363635.0,...,76190.0,295761.0,11941.0,70631.0,801.0,1241.0,6.521166e+05,9.033096e+05,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0.0,NaN,64059.0,199113.0,...,46054.0,163590.0,13123.0,72337.0,484.0,658.0,5.251389e+05,7.868542e+05,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0.0,NaN,1084749.0,2252617.0,...,822301.0,1933339.0,231155.0,613340.0,21478.0,25934.0,3.158027e+10,3.491383e+10,OK,NaN

In [11]:
#### **Scom VD Traffic APP**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_vd_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:41
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_app_20260306_160341.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [11:01<00:00, 14.37s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_app_20260306_160341.csv
총 데이터 row (FAILED row 제외, header 제외): 25
⏱ Elapsed: 0:11:01.365561
❌ 실패 site: 3
실패 목록 (앞 50개):
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_app_20260306_160341.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0.0,NaN,15578.0,13663.0,...,0.0,6.0,51.0,34.0,17.0,2.517121e+05,1.508357e+05,1.008763e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0.0,NaN,118651.0,111525.0,...,49538.0,975.0,1248.0,1012.0,236.0,2.274896e+09,1.842068e+09,4.328280e+08,OK,NaN

In [13]:
#### **Scom VD Traffic WEB**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_vd_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:14:43
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_web_20260306_161443.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:37<00:00,  1.22site/s, ok=0, rows=0, site=ES]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_web_20260306_161443.csv
총 데이터 row (FAILED row 제외, header 제외): 43
⏱ Elapsed: 0:00:37.875683
❌ 실패 site: 3
실패 목록 (앞 50개):
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_web_20260306_161443.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0.0,NaN,68917.0,59818.0,...,43685.0,12506.0,19281.0,6249.0,40.0,46.0,2.572609e+05,4.978723e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0.0,NaN,233770.0,290100.0,...,168989.0,226794.0,102905.0,116819.0,1400.0,1655.0,2.506184e+09,3.642071e+09,OK,NaN

In [15]:
## **2_1~4. Basic Traffic**

In [16]:
#### **Basic Traffic CMP**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:15:22
▶ Output: aa_exports\26_ny_2_1_basic_traffic_cmp_20260306_161522.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30', 'value31', 'value32', 'value33', 'value34', 'value35']

AA Export (sites): 100%|██████████| 46/46 [01:36<00:00,  2.09s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_cmp_20260306_161522.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:01:36.431318
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_cmp_20260306_161522.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value28,value29,value30,value31,value32,value33,value34,value35,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),60321.0,2434303.0,...,2027.0,4734.0,2112.0,271.0,1839.0,0.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),25304.0,67194.0,...,58.0,267.0,169.0,5.0,162.0,0.0,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),9899.0,35708.0,...,594.0,139.0,535.0,490.0,45.0,0.0,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),2356.0,3911.0,...,324.0,71.0,31.0,2.0,29.0,0.0,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),89426.0,655043.0,...,98986.0,1902.0,88003.0,87192.0,811.0,0.0,0.0,0.0,OK,NaN

In [18]:
#### **Basic Traffic Scom**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:16:59
▶ Output: aa_exports\26_ny_2_1_basic_traffic_scom_20260306_161659.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites): 100%|██████████| 46/46 [04:43<00:00,  6.16s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_scom_20260306_161659.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:04:43.732544
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_scom_20260306_161659.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,632116.0,4546193.0,...,7789163.0,202718.0,724270.0,689000.0,35240.0,240759.0,224354.0,16380.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,286604.0,830751.0,...,2177983.0,82518.0,217969.0,188222.0,11580.0,72885.0,63561.0,7187.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,147090.0,417144.0,...,2641696.0,101449.0,171695.0,137861.0,19004.0,61969.0,47481.0,12426.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,0,NaN,380145.0,1159980.0,...,6014735.0,188020.0,345459.0,297076.0,25350.0,116156.0,95185.0,16520.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,2399258.0,7194107.0,...,18170680.0,515064.0,7155517.0,7052389.0,103124.0,4049660.0,4015077.0,34581.0,OK,NaN

In [20]:
#### **Basic Traffic Time CMP**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_time_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:21:43
▶ Output: aa_exports\26_ny_2_1_basic_traffic_time_cmp_20260306_162143.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:16<00:00,  2.87site/s, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_time_cmp_20260306_162143.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:16.262652
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_time_cmp_20260306_162143.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),210.743071,313.727601,177.347212,194.709841,186.564272,351.206783,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),293.028468,337.642029,292.218473,224.179768,215.860381,366.310421,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),284.567873,363.335613,251.574558,283.931180,266.253748,419.741153,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),292.039097,395.918950,259.351259,270.003553,261.218161,397.723646,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),255.702038,424.784837,244.006818,217.335013,214.564222,380.786812,OK,NaN

In [22]:
#### **Basic Traffic Time Scom**

In [23]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_time_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:22:00
▶ Output: aa_exports\26_ny_2_1_basic_traffic_time_scom_20260306_162200.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:04<00:00, 11.09site/s, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_time_scom_20260306_162200.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:04.439895
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_time_scom_20260306_162200.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),210.743071,313.727601,177.347212,194.709841,186.564272,351.206783,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),293.028468,337.642029,292.218473,224.179768,215.860381,366.310421,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),284.567873,363.335613,251.574558,283.931180,266.253748,419.741153,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),292.039097,395.918950,259.351259,270.003553,261.218161,397.723646,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),255.702038,424.784837,244.006818,217.335013,214.564222,380.786812,OK,NaN

In [24]:
## **3. Traffic by Channel**

In [25]:
#### **Channel Internal**

In [26]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_1_channel_internal.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:22:05
▶ Output: aa_exports\26_ny_3_1_channel_internal_20260306_162205.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites): 100%|██████████| 46/46 [02:34<00:00,  3.35s/site, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_1_channel_internal_20260306_162205.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:02:34.411470
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_1_channel_internal_20260306_162205.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),221.0,116.0,...,0.0,0.0,172.0,6564.0,10843.0,0.0,0.0,172.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),96.0,1224.0,...,72.0,0.0,747.0,1442.0,7349.0,2.0,19.0,747.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),69.0,274.0,...,15.0,0.0,1.0,679.0,560.0,0.0,0.0,1.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),141.0,1190.0,...,1.0,0.0,3.0,760.0,138.0,0.0,0.0,3.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),585.0,3959.0,...,0.0,0.0,1.0,1859.0,44.0,0.0,0.0,0.0,OK,NaN

In [27]:
#### **Channel External CMP**

In [28]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_2_channel_external_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:24:40
▶ Output: aa_exports\26_ny_3_2_channel_external_cmp_20260306_162440.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:16<00:00,  2.86site/s, ok=1, rows=19, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_2_channel_external_cmp_20260306_162440.csv
총 데이터 row (FAILED row 제외, header 제외): 656
⏱ Elapsed: 0:00:16.357207
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_2_channel_external_cmp_20260306_162440.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1,Paid Search,42143.0,12248.0,78813.0,55081.0,32.0,6.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,11,Social Media Campaigns,2894.0,2268.0,591706.0,590968.0,0.0,0.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,5,Direct,2002.0,451.0,11663.0,5896.0,5957.0,1916.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,15,Mobile Application,1533.0,1134.0,81175.0,66576.0,134.0,52.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,16,Affiliate Marketing,1382.0,915.0,1611888.0,1405319.0,48.0,36.0,OK,NaN

In [29]:
#### **Channel External Scom**

In [30]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_2_channel_external_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:24:57
▶ Output: aa_exports\26_ny_3_2_channel_external_scom_20260306_162457.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 46/46 [00:18<00:00,  2.50site/s, ok=1, rows=23, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_2_channel_external_scom_20260306_162457.csv
총 데이터 row (FAILED row 제외, header 제외): 942
⏱ Elapsed: 0:00:18.645960
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_2_channel_external_scom_20260306_162457.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,16,Affiliate Marketing,1614838.0,1406601.0,114.0,78.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,5,Direct,809175.0,578688.0,663682.0,228377.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,20,Display,770934.0,707365.0,83.0,26.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,11,Social Media Campaigns,600209.0,598223.0,59.0,9.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,14,Push,356835.0,299925.0,44425.0,8943.0,OK,NaN

In [31]:
#### **Homepage KV GNB TO CMP**

In [32]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_3_homepage_kv_gnb_to_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:25:16
▶ Output: aa_exports\26_ny_3_3_homepage_kv_gnb_to_cmp_20260306_162516.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites): 100%|██████████| 46/46 [00:20<00:00,  2.26site/s, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_3_homepage_kv_gnb_to_cmp_20260306_162516.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:20.638369
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_3_homepage_kv_gnb_to_cmp_20260306_162516.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),144000.0,147841.0,426716.0,116.0,301.0,6564.0,122.0,10.0,172.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),58291.0,85831.0,146610.0,1224.0,2503.0,1442.0,50.0,14.0,747.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),23593.0,36303.0,108567.0,274.0,569.0,679.0,42.0,0.0,1.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),90684.0,182491.0,243578.0,1190.0,2097.0,760.0,62.0,10.0,3.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),497838.0,909932.0,4434688.0,3959.0,7135.0,1859.0,162.0,97.0,0.0,OK,NaN

In [33]:
## **4. Order CVR**

In [34]:
#### **Order CVR Loginout**

In [35]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_4_1_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:25:37
▶ Output: aa_exports\26_ny_4_1_order_cvr_loginout_20260306_162537.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites): 100%|██████████| 46/46 [12:54<00:00, 16.84s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_4_1_order_cvr_loginout_20260306_162537.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:12:55.040210
❌ 실패 site: 0
DONE: aa_exports\26_ny_4_1_order_cvr_loginout_20260306_162537.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),282256.0,8676.0,...,1.099395e+07,47830.20,3701.0,3584.0,117.0,1.671588e+07,1.630323e+07,4.126448e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),33167.0,9616.0,...,3.670340e+05,167243.95,4478.0,2646.0,1832.0,3.555669e+06,2.173285e+06,1.382384e+06,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),19199.0,2507.0,...,4.190083e+05,120397.56,3347.0,2602.0,745.0,3.503271e+06,2.698075e+06,8.051966e+05,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),2667.0,362.0,...,6.406738e+04,6814.53,10123.0,7613.0,2510.0,7.396056e+06,5.736987e+06,1.659069e+06,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),52808.0,9072.0,...,3.526659e+09,660900.00,122997.0,121721.0,1276.0,1.468690e+11,1.462702e+11,5.988030e+08,OK,NaN

In [36]:
#### **Order CVR Visit Visitor**

In [37]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_4_2_order_cvr_visit_visitor.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:38:33
▶ Output: aa_exports\26_ny_4_2_order_cvr_visit_visitor_20260306_163833.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 46/46 [00:23<00:00,  1.95site/s, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_4_2_order_cvr_visit_visitor_20260306_163833.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:23.854110
❌ 실패 site: 0
DONE: aa_exports\26_ny_4_2_order_cvr_visit_visitor_20260306_163833.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),5799.0,2488825.0,...,59196.0,11478.0,41490.0,7855.0,29701.0,5148608.0,402273.0,322002.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),6355.0,86143.0,...,9504.0,1596.0,7722.0,1372.0,74624.0,1042731.0,134481.0,83489.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),4653.0,40954.0,...,2742.0,589.0,2557.0,545.0,41091.0,523143.0,101498.0,70197.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),1035.0,5232.0,...,929.0,303.0,866.0,260.0,142194.0,1397931.0,224590.0,120870.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),146133.0,598336.0,...,121783.0,6081.0,106384.0,3950.0,3097552.0,6495813.0,6320315.0,835202.0,OK,NaN

In [38]:
## **5. Campaign Order CVR**

In [39]:
#### **Campaign Order CVR**

In [40]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_5_1_campaign_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:38:57
▶ Output: aa_exports\26_ny_5_1_campaign_order_cvr_20260306_163857.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 46/46 [00:14<00:00,  3.24site/s, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_5_1_campaign_order_cvr_20260306_163857.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:14.438872
❌ 실패 site: 0
DONE: aa_exports\26_ny_5_1_campaign_order_cvr_20260306_163857.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),3701.0,1.671588e+07,...,1532.0,212.0,5.213019e+06,4.069522e+06,1.139155e+06,391.0,315.0,75.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),4478.0,3.555669e+06,...,844.0,74.0,7.198168e+05,5.574084e+05,7.268989e+04,289.0,240.0,21.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),3347.0,3.503271e+06,...,918.0,230.0,1.311960e+06,9.235702e+05,2.543875e+05,440.0,329.0,56.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),10123.0,7.396056e+06,...,1897.0,188.0,1.494006e+06,1.204733e+06,1.685257e+05,625.0,548.0,39.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),122997.0,1.468690e+11,...,41636.0,3731.0,5.462788e+10,4.967051e+10,4.957371e+09,2694.0,2378.0,316.0,OK,NaN

In [41]:
#### **Scom Order CVR**

In [42]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_5_1_scom_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:39:12
▶ Output: aa_exports\26_ny_5_1_scom_order_cvr_20260306_163912.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:14<00:00,  3.17site/s, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_5_1_scom_order_cvr_20260306_163912.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:14.750417
❌ 실패 site: 0
DONE: aa_exports\26_ny_5_1_scom_order_cvr_20260306_163912.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),1796.0,1846.0,...,343.0,81.0,461.0,370.0,90.0,133.0,107.0,26.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),605.0,637.0,...,123.0,10.0,189.0,152.0,17.0,51.0,46.0,3.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),438.0,488.0,...,36.0,18.0,90.0,68.0,13.0,16.0,10.0,3.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),55.0,74.0,...,15.0,4.0,30.0,25.0,5.0,3.0,3.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),1789.0,2091.0,...,816.0,167.0,1164.0,812.0,352.0,151.0,125.0,26.0,OK,NaN

In [43]:
## **6. S.com Cross Sell Order**

In [44]:
#### **Multi Order Cross Sell**

In [45]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_1_multi_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:39:27
▶ Output: aa_exports\26_ny_6_1_multi_order_cross_sell_20260306_163927.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:52<00:00,  1.14s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_1_multi_order_cross_sell_20260306_163927.csv
총 데이터 row (FAILED row 제외, header 제외): 39
⏱ Elapsed: 0:00:52.715960
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_1_multi_order_cross_sell_20260306_163927.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,1364.0,1.022199e+07,...,9.0,2.549130e+05,0.0,0.000000e+00,7.0,1.297253e+05,0.0,0.00,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,1297.0,1.562063e+06,...,3.0,9.839180e+03,30.0,6.161341e+04,48.0,1.210253e+05,0.0,0.00,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,1106.0,1.588599e+06,...,9.0,1.471617e+04,12.0,2.266178e+04,9.0,2.131008e+04,3.0,9530.23,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,0,NaN,2524.0,2.709225e+06,...,13.0,1.998868e+04,8.0,1.600452e+04,8.0,1.523730e+04,0.0,0.00,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,7563.0,1.240615e+10,...,155.0,2.711655e+08,216.0,1.687022e+09,762.0,8.445645e+08,13.0,61161500.00,OK,NaN

In [46]:
#### **Total Order Cross Sell**

In [47]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_2_total_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:40:21
▶ Output: aa_exports\26_ny_6_2_total_order_cross_sell_20260306_164021.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:18<00:00,  2.51site/s, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_2_total_order_cross_sell_20260306_164021.csv
총 데이터 row (FAILED row 제외, header 제외): 39
⏱ Elapsed: 0:00:18.533340
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_2_total_order_cross_sell_20260306_164021.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,3701.0,1.671588e+07,...,9.0,2.549130e+05,0.0,0.000000e+00,7.0,1.297253e+05,0.0,0.00,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,4478.0,3.555669e+06,...,3.0,9.839180e+03,30.0,6.161341e+04,48.0,1.210253e+05,0.0,0.00,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,3347.0,3.503271e+06,...,9.0,1.471617e+04,12.0,2.266178e+04,9.0,2.131008e+04,3.0,9530.23,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,0,NaN,10123.0,7.396056e+06,...,13.0,1.998868e+04,8.0,1.600452e+04,8.0,1.523730e+04,0.0,0.00,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,122997.0,1.468690e+11,...,155.0,2.711655e+08,216.0,1.687022e+09,762.0,8.445645e+08,13.0,61161500.00,OK,NaN

In [48]:
#### **CMP Order Cross Sell**

In [49]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_3_cmp_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:40:40
▶ Output: aa_exports\26_ny_6_3_cmp_order_cross_sell_20260306_164040.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:21<00:00,  2.19site/s, ok=1, rows=1, site=DE]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_3_cmp_order_cross_sell_20260306_164040.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:21.228137
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_3_cmp_order_cross_sell_20260306_164040.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),1846.0,1.104178e+07,...,6.0,179503.04,0.0,0.000000e+00,6.0,111066.34,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),637.0,5.342780e+05,...,0.0,0.00,3.0,5.653400e+03,10.0,27332.50,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),488.0,5.394059e+05,...,0.0,0.00,3.0,9.066740e+03,1.0,2459.68,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),74.0,7.088191e+04,...,0.0,0.00,0.0,0.000000e+00,0.0,0.00,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),2091.0,3.527320e+09,...,8.0,16577800.00,36.0,2.637011e+08,10.0,20063045.00,0.0,0.0,OK,NaN

In [50]:
## **7. Order Conversion/Traffic by Channel**

In [51]:
#### **Order BY Channel CMP**

In [52]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_7_1_order_by_channel_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:41:01
▶ Output: aa_exports\26_ny_7_1_order_by_channel_cmp_20260306_164101.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15']

AA Export (sites): 100%|██████████| 46/46 [00:15<00:00,  2.98site/s, ok=1, rows=21, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_7_1_order_by_channel_cmp_20260306_164101.csv
총 데이터 row (FAILED row 제외, header 제외): 760
⏱ Elapsed: 0:00:15.675085
❌ 실패 site: 0
DONE: aa_exports\26_ny_7_1_order_by_channel_cmp_20260306_164101.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value8,value9,value10,value11,value12,value13,value14,value15,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1,Paid Search,43446.0,80317.0,...,1.0,0.0,1.0,1275544.12,233844.79,8862.98,0.00,8862.98,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,5,Direct,3440.0,26389.0,...,355.0,281.0,74.0,388302.04,0.00,1337647.89,944719.27,392928.62,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,11,Social Media Campaigns,2953.0,591718.0,...,0.0,0.0,0.0,1978901.04,803336.14,0.00,0.00,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2,Natural Search,2743.0,1306.0,...,0.0,0.0,0.0,71864.83,34570.14,0.00,0.00,0.00,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,15,Mobile Application,1625.0,83176.0,...,23.0,23.0,0.0,0.00,46071.19,60845.68,60845.68,0.00,OK,NaN

In [53]:
#### **Order BY Channel Scom**

In [54]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_7_1_order_by_channel_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:41:18
▶ Output: aa_exports\26_ny_7_1_order_by_channel_scom_20260306_164118.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:18<00:00,  2.42site/s, ok=1, rows=22, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_7_1_order_by_channel_scom_20260306_164118.csv
총 데이터 row (FAILED row 제외, header 제외): 942
⏱ Elapsed: 0:00:19.269787
❌ 실패 site: 0
DONE: aa_exports\26_ny_7_1_order_by_channel_scom_20260306_164118.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,16,Affiliate Marketing,1614838.0,114.0,538.0,9.0,4418482.18,44056.62,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,5,Direct,809175.0,663686.0,228.0,1546.0,1081443.20,4616092.43,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,20,Display,770934.0,83.0,0.0,0.0,0.00,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,11,Social Media Campaigns,600209.0,59.0,368.0,0.0,2848938.04,0.00,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,14,Push,356835.0,44425.0,11.0,133.0,64406.36,375296.31,OK,NaN

In [72]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_8_8_cmp_adaptive_banner.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 18:13:48
▶ Output: aa_exports\26_ny_8_8_cmp_adaptive_banner_20260306_181348.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [02:54<00:00,  3.79s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_8_8_cmp_adaptive_banner_20260306_181348.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:02:54.509492
❌ 실패 site: 0
DONE: aa_exports\26_ny_8_8_cmp_adaptive_banner_20260306_181348.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),2565298.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),103598.0,1.0,1.0,0.0,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),48938.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),7499.0,0.0,0.0,2.0,2.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),872333.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [55]:
## **Multi Purchase**

In [56]:
#### **RAW Multi Purchase V41**

In [57]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_raw_multi_purchase_v41.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:41:38
▶ Output: aa_exports\26_ny_raw_multi_purchase_v41_20260306_164138.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:07<00:00,  5.86site/s, ok=1, rows=330, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_raw_multi_purchase_v41_20260306_164138.csv
총 데이터 row (FAILED row 제외, header 제외): 21,645
⏱ Elapsed: 0:00:08.586553
❌ 실패 site: 0
DONE: aa_exports\26_ny_raw_multi_purchase_v41_20260306_164138.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3667055378,"SM-S9380ZSDCHC,EP-T4511XBCMCN",217.0,85.0,645911.2,219.0,86.0,653510.2,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,4002195195,"SM-S9380ZKDCHC,EP-T4511XBCMCN",158.0,66.0,501532.2,189.0,78.0,592720.2,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3360070075,"SM-S9380ZBDCHC,EP-T4511XBCMCN",122.0,42.0,319154.4,122.0,42.0,319154.4,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2459278122,"SM-S9380ZSGCHC,EP-T4511XBCMCN",113.0,44.0,377854.0,113.0,44.0,377854.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,459863883,"SM-S9380ZTGCHC,EP-T4511XBCMCN",103.0,39.0,335359.2,103.0,39.0,335359.2,OK,NaN

In [58]:
## **Best Selling Product**

In [59]:
#### **Bestselling**

In [60]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_bestselling.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:41:47
▶ Output: aa_exports\26_ny_bestselling_20260306_164147.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 46/46 [00:07<00:00,  6.17site/s, ok=1, rows=326, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_bestselling_20260306_164147.csv
총 데이터 row (FAILED row 제외, header 제외): 12,111
⏱ Elapsed: 0:00:08.008954
❌ 실패 site: 0
DONE: aa_exports\26_ny_bestselling_20260306_164147.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3340441902,EP-T4511,768.0,23653.33,646.0,4403.90,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2597718718,SM-S9380,707.0,5700459.18,645.0,5198299.73,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2983901684,NaN,577.0,0.00,485.0,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,163391546,SM-S9280,442.0,2444128.39,219.0,1208394.32,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1525368397,SM-F9660,236.0,3136018.64,177.0,2317336.65,OK,NaN

In [61]:
## **Next Page**

In [62]:
#### **Nextpage**

In [63]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_nextpage.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:41:55
▶ Output: aa_exports\26_ny_nextpage_20260306_164155.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 46/46 [01:43<00:00,  2.25s/site, ok=1, rows=51, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_nextpage_20260306_164155.csv
총 데이터 row (FAILED row 제외, header 제외): 1,734
⏱ Elapsed: 0:01:43.826527
❌ 실패 site: 3
실패 목록 (앞 50개):
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_nextpage_20260306_164155.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3.457728e+09,flagship pdp,131723.0,131651.0,0.0,0.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2.067554e+09,product detail,117238.0,61457.0,40968.0,13598.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3.543974e+09,product finder,14609.0,11942.0,1932.0,239.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,9.147071e+08,shop event,36311.0,9550.0,910.0,1.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,8.041200e+08,product category detail,917.0,198.0,8.0,0.0,OK,NaN

In [64]:
## **CC (Contents)**

In [65]:
#### **CC Order**

In [66]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_cc_order.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:43:40
▶ Output: aa_exports\26_ny_cc_order_20260306_164340.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27']

AA Export (sites): 100%|██████████| 46/46 [06:07<00:00,  7.99s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_cc_order_20260306_164340.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:06:07.758733
❌ 실패 site: 0
DONE: aa_exports\26_ny_cc_order_20260306_164340.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value20,value21,value22,value23,value24,value25,value26,value27,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),754.0,656.0,...,0.0,0.0,0.0,0.0,0.0,276.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),219.0,133.0,...,0.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),170.0,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),25.0,3.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),611.0,271.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [67]:
#### **CC Revenue**

In [68]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_cc_revenue.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:49:48
▶ Output: aa_exports\26_ny_cc_revenue_20260306_164948.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27']

AA Export (sites): 100%|██████████| 46/46 [00:37<00:00,  1.21site/s, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_cc_revenue_20260306_164948.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:38.160504
❌ 실패 site: 0
DONE: aa_exports\26_ny_cc_revenue_20260306_164948.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value20,value21,value22,value23,value24,value25,value26,value27,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),5.747466e+06,5.168188e+06,...,0.0,0.0,0.00,0.0,0.00,2396206.60,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),2.027110e+05,1.422614e+05,...,0.0,0.0,0.00,0.0,0.00,19022.73,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),1.902604e+05,2.252588e+04,...,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),1.782383e+04,3.011440e+03,...,0.0,0.0,92.54,0.0,1983.68,0.00,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),1.063455e+09,6.461536e+08,...,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0,OK,NaN

In [69]:
#### **CC Visit**

In [70]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_cc_visit.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:50:27
▶ Output: aa_exports\26_ny_cc_visit_20260306_165027.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27']

AA Export (sites): 100%|██████████| 46/46 [01:03<00:00,  1.38s/site, ok=1, rows=1, site=ES]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_cc_visit_20260306_165027.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:01:03.733450
❌ 실패 site: 0
DONE: aa_exports\26_ny_cc_visit_20260306_165027.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value20,value21,value22,value23,value24,value25,value26,value27,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),60321.0,13618.0,...,0.0,0.0,0.0,0.0,0.0,3668.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),25304.0,13707.0,...,0.0,0.0,0.0,0.0,2.0,1361.0,3.0,2.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),9899.0,1036.0,...,0.0,0.0,1.0,0.0,3.0,43.0,2.0,1.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-09,1260001,2026 (Jan 1-Dec 31),2356.0,411.0,...,5.0,19.0,10.0,4.0,23.0,34.0,35.0,24.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),89426.0,17340.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

# **CSV to Excel Raw Sheet Format**

In [71]:
# 후처리 코드를 여기에 추가하세요.