In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic APP**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_da_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-06 15:43:25
▶ Output: aa_exports\25_ny_1_1_scom_da_traffic_app_20260306_154325.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [14:26<00:00, 18.84s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_da_traffic_app_20260306_154325.csv
총 데이터 row (FAILED row 제외, header 제외): 28
⏱ Elapsed: 0:14:27.064945
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_da_traffic_app_20260306_154325.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,11951.0,11303.0,...,1.0,9.0,97.0,91.0,6.0,5.429676e+05,4.974562e+05,4.551136e+04,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,0,NaN,6326.0,5559.0,...,1.0,0.0,228.0,173.0,24.0,2.150736e+05,1.592181e+05,2.730035e+04,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0,NaN,5116.0,4220.0,...,2.0,4.0,265.0,99.0,25.0,2.045852e+05,7.350084e+04,1.969738e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,0,NaN,16853.0,14290.0,...,6.0,6.0,370.0,222.0,64.0,3.630963e+05,1.944824e+05,8.086539e+04,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,233172.0,225998.0,...,30522.0,865.0,5711.0,5326.0,385.0,4.770468e+09,4.266817e+09,5.036505e+08,OK,NaN

In [5]:
#### **Scom DA Traffic WEB**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_da_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:57:52
▶ Output: aa_exports\25_ny_1_1_scom_da_traffic_web_20260306_155752.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:29<00:00,  1.55site/s, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_da_traffic_web_20260306_155752.csv
총 데이터 row (FAILED row 제외, header 제외): 44
⏱ Elapsed: 0:00:29.877846
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_da_traffic_web_20260306_155752.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,118523.0,352763.0,...,79213.0,336406.0,17202.0,293394.0,68.0,160.0,6.276053e+05,1.014692e+06,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,0,NaN,33305.0,80641.0,...,23081.0,67567.0,3549.0,1376.0,405.0,462.0,4.149993e+05,3.594251e+05,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0,NaN,21784.0,42420.0,...,15725.0,34821.0,4262.0,8376.0,442.0,123.0,2.877677e+05,9.178071e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,0,NaN,68924.0,107173.0,...,48649.0,80876.0,18061.0,17853.0,596.0,465.0,5.091222e+05,3.399238e+05,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,408839.0,976304.0,...,267123.0,822801.0,155075.0,464061.0,6389.0,9825.0,5.538583e+09,4.513541e+09,OK,NaN

In [7]:
#### **Scom MX Traffic APP**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_mx_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:58:23
▶ Output: aa_exports\25_ny_1_1_scom_mx_traffic_app_20260306_155823.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [07:11<00:00,  9.39s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_mx_traffic_app_20260306_155823.csv
총 데이터 row (FAILED row 제외, header 제외): 33
⏱ Elapsed: 0:07:12.309944
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_mx_traffic_app_20260306_155823.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,426460.0,401683.0,...,52.0,16.0,6930.0,6489.0,435.0,1.585718e+07,1.326240e+07,2.584182e+06,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,0,NaN,112888.0,108718.0,...,33.0,2.0,3962.0,3080.0,122.0,2.721671e+06,2.089294e+06,1.165571e+05,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0,NaN,45459.0,43252.0,...,36.0,5.0,2637.0,1252.0,65.0,2.032766e+06,9.964833e+05,6.889551e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,0,NaN,175739.0,164298.0,...,32.0,5.0,4934.0,3682.0,266.0,3.779534e+06,2.790363e+06,2.584727e+05,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,1478892.0,1470793.0,...,171873.0,883.0,68376.0,67739.0,637.0,2.105035e+10,2.016458e+10,8.857682e+08,OK,NaN

In [9]:
#### **Scom MX Traffic WEB**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_mx_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:05:35
▶ Output: aa_exports\25_ny_1_1_scom_mx_traffic_web_20260306_160535.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [02:11<00:00,  2.85s/site, ok=1, rows=1, site=ES]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_mx_traffic_web_20260306_160535.csv
총 데이터 row (FAILED row 제외, header 제외): 44
⏱ Elapsed: 0:02:11.384415
❌ 실패 site: 2
실패 목록 (앞 50개):
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\25_ny_1_1_scom_mx_traffic_web_20260306_160535.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0.0,NaN,447080.0,6668933.0,...,325601.0,6494763.0,134688.0,5599404.0,1564.0,2691.0,6.801867e+06,1.053508e+07,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0.0,NaN,121886.0,364212.0,...,92217.0,308978.0,28344.0,95547.0,2442.0,1209.0,1.964810e+06,1.056220e+06,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0.0,NaN,1042101.0,2699612.0,...,819058.0,2414291.0,252540.0,1184832.0,14042.0,12736.0,1.155741e+10,7.187770e+09,OK,NaN

In [11]:
#### **Scom VD Traffic APP**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_vd_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:07:47
▶ Output: aa_exports\25_ny_1_1_scom_vd_traffic_app_20260306_160747.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [08:57<00:00, 11.69s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_vd_traffic_app_20260306_160747.csv
총 데이터 row (FAILED row 제외, header 제외): 30
⏱ Elapsed: 0:08:58.122822
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_vd_traffic_app_20260306_160747.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,41762.0,37952.0,...,8.0,28.0,187.0,127.0,60.0,1.168806e+06,8.615884e+05,3.072177e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,0,NaN,7648.0,6739.0,...,1.0,0.0,84.0,61.0,6.0,7.309594e+04,5.292202e+04,7.353640e+03,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0,NaN,10744.0,8798.0,...,18.0,31.0,601.0,265.0,71.0,4.784982e+05,1.752280e+05,5.355168e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,0,NaN,23405.0,19690.0,...,13.0,5.0,424.0,259.0,72.0,5.608814e+05,3.308118e+05,1.050307e+05,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,106080.0,103408.0,...,18890.0,440.0,789.0,727.0,62.0,1.496895e+09,1.334236e+09,1.626587e+08,OK,NaN

In [13]:
#### **Scom VD Traffic WEB**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_vd_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:16:46
▶ Output: aa_exports\25_ny_1_1_scom_vd_traffic_web_20260306_161646.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:51<00:00,  1.12s/site, ok=1, rows=1, site=ES]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_vd_traffic_web_20260306_161646.csv
총 데이터 row (FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:00:51.647294
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_vd_traffic_web_20260306_161646.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,514214.0,334200.0,...,476561.0,299996.0,86252.0,249364.0,179.0,222.0,1.664202e+06,2.207849e+06,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,0,NaN,67225.0,120392.0,...,44174.0,96049.0,7073.0,2489.0,275.0,289.0,2.834106e+05,2.813291e+05,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0,NaN,42708.0,86894.0,...,30718.0,71697.0,8150.0,15897.0,742.0,257.0,7.765525e+05,2.469370e+05,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,0,NaN,107766.0,193321.0,...,80148.0,160944.0,28822.0,41491.0,635.0,569.0,6.792680e+05,5.132687e+05,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,170004.0,308582.0,...,100497.0,251072.0,35425.0,92611.0,1083.0,647.0,2.029926e+09,1.029330e+09,OK,NaN

In [15]:
## **2_1~4. Basic Traffic**

In [16]:
#### **Basic Traffic CMP**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_2_1_basic_traffic_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:17:38
▶ Output: aa_exports\25_ny_2_1_basic_traffic_cmp_20260306_161738.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30', 'value31', 'value32', 'value33', 'value34', 'value35']

AA Export (sites): 100%|██████████| 46/46 [01:41<00:00,  2.22s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_2_1_basic_traffic_cmp_20260306_161738.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:01:42.228474
❌ 실패 site: 0
DONE: aa_exports\25_ny_2_1_basic_traffic_cmp_20260306_161738.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value28,value29,value30,value31,value32,value33,value34,value35,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [18]:
#### **Basic Traffic Scom**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_2_1_basic_traffic_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:19:21
▶ Output: aa_exports\25_ny_2_1_basic_traffic_scom_20260306_161921.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites): 100%|██████████| 46/46 [04:44<00:00,  6.19s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_2_1_basic_traffic_scom_20260306_161921.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:04:44.811649
❌ 실패 site: 0
DONE: aa_exports\25_ny_2_1_basic_traffic_scom_20260306_161921.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,2998186.0,12661221.0,...,13314947.0,603259.0,1054332.0,999574.0,54726.0,333905.0,317464.0,16425.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,0,NaN,465770.0,1597864.0,...,3713930.0,171322.0,312113.0,292146.0,19491.0,84876.0,75210.0,9480.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0,NaN,245005.0,687624.0,...,2851245.0,206460.0,185259.0,161817.0,22888.0,62125.0,48190.0,13689.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,0,NaN,705260.0,2471248.0,...,6993363.0,545946.0,572663.0,513391.0,57985.0,170991.0,140724.0,29702.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,2356504.0,6128066.0,...,25052052.0,188286.0,5714688.0,5680379.0,34286.0,2766096.0,2752703.0,13388.0,OK,NaN

In [20]:
#### **Basic Traffic Time**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_2_1_basic_traffic_time.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:24:06
▶ Output: aa_exports\25_ny_2_1_basic_traffic_time_20260306_162406.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:53<00:00,  1.16s/site, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_2_1_basic_traffic_time_20260306_162406.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:53.689778
❌ 실패 site: 0
DONE: aa_exports\25_ny_2_1_basic_traffic_time_20260306_162406.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),31.569003,77.089385,23.039324,30.564689,29.600567,45.890643,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),104.090393,132.764755,90.170579,105.641080,103.028373,145.063008,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),72.143127,73.618330,72.182490,54.361474,54.179620,59.543307,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),84.936410,106.763332,73.125104,68.340587,70.648311,53.654762,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),131.621152,133.283291,178.994401,62.924235,61.807888,145.592969,OK,NaN

In [22]:
#### **Basic Traffic Time CMP**

In [23]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_2_1_basic_traffic_time_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:25:01
▶ Output: aa_exports\25_ny_2_1_basic_traffic_time_cmp_20260306_162501.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:15<00:00,  2.94site/s, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_2_1_basic_traffic_time_cmp_20260306_162501.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:15.862884
❌ 실패 site: 0
DONE: aa_exports\25_ny_2_1_basic_traffic_time_cmp_20260306_162501.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),171.473767,139.236507,155.624058,263.257850,256.924410,385.050805,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),312.701733,372.568654,307.457341,325.364785,322.116926,366.191079,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),284.382438,376.607535,230.748588,346.635333,342.468220,360.386109,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),288.059724,397.511376,236.418767,351.300909,346.934266,387.453100,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),272.472316,389.527132,258.691285,243.243659,242.178891,415.732515,OK,NaN

In [24]:
#### **Basic Traffic Time Scom**

In [25]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_2_1_basic_traffic_time_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:25:17
▶ Output: aa_exports\25_ny_2_1_basic_traffic_time_scom_20260306_162517.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:03<00:00, 11.63site/s, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_2_1_basic_traffic_time_scom_20260306_162517.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:04.193725
❌ 실패 site: 0
DONE: aa_exports\25_ny_2_1_basic_traffic_time_scom_20260306_162517.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),171.473767,139.236507,155.624058,263.257850,256.924410,385.050805,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),312.701733,372.568654,307.457341,325.364785,322.116926,366.191079,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),284.382438,376.607535,230.748588,346.635333,342.468220,360.386109,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),288.059724,397.511376,236.418767,351.300909,346.934266,387.453100,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),272.472316,389.527132,258.691285,243.243659,242.178891,415.732515,OK,NaN

In [26]:
## **3. Traffic by Channel**

In [27]:
#### **Channel Internal**

In [28]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_1_channel_internal.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:25:22
▶ Output: aa_exports\25_ny_3_1_channel_internal_20260306_162522.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites): 100%|██████████| 46/46 [02:38<00:00,  3.44s/site, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_1_channel_internal_20260306_162522.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:02:38.697970
❌ 실패 site: 0
DONE: aa_exports\25_ny_3_1_channel_internal_20260306_162522.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [29]:
#### **Channel External CMP**

In [30]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_2_channel_external_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:28:01
▶ Output: aa_exports\25_ny_3_2_channel_external_cmp_20260306_162801.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:12<00:00,  3.65site/s, ok=1, rows=0, site=SG]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_2_channel_external_cmp_20260306_162801.csv
총 데이터 row (FAILED row 제외, header 제외): 3
⏱ Elapsed: 0:00:12.822266
❌ 실패 site: 0
DONE: aa_exports\25_ny_3_2_channel_external_cmp_20260306_162801.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SEPOL,Poland,PL,sssamsung4pl,2025-01-19,2025-02-05,5,Direct,2.0,1.0,0.0,0.0,0.0,0.0,OK,NaN
1,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-01-19,2025-02-26,4,Email,0.0,0.0,4.0,4.0,0.0,0.0,OK,NaN
2,SME,Malaysia,MY,sssamsung4my,2025-02-20,2025-04-06,2,Natural Search,1.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [31]:
#### **Channel External Scom**

In [32]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_2_channel_external_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:28:14
▶ Output: aa_exports\25_ny_3_2_channel_external_scom_20260306_162814.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 46/46 [00:19<00:00,  2.42site/s, ok=1, rows=20, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_2_channel_external_scom_20260306_162814.csv
총 데이터 row (FAILED row 제외, header 제외): 872
⏱ Elapsed: 0:00:19.326137
❌ 실패 site: 0
DONE: aa_exports\25_ny_3_2_channel_external_scom_20260306_162814.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,16,Affiliate Marketing,7430048.0,5423596.0,0.0,0.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,20,Display,2772673.0,2318423.0,626.0,74.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,11,Social Media Campaigns,2185634.0,2002039.0,6524.0,1774.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,5,Direct,1278578.0,964822.0,908233.0,295434.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1,Paid Search,428209.0,136685.0,676.0,169.0,OK,NaN

In [33]:
#### **Channel Traffic External**

In [34]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_2_channel_traffic_external.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:28:34
▶ Output: aa_exports\25_ny_3_2_channel_traffic_external_20260306_162834.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2']

AA Export (sites): 100%|██████████| 46/46 [12:01<00:00, 15.69s/site, ok=1, rows=11, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_2_channel_traffic_external_20260306_162834.csv
총 데이터 row (FAILED row 제외, header 제외): 390
⏱ Elapsed: 0:12:02.006301
❌ 실패 site: 0
DONE: aa_exports\25_ny_3_2_channel_traffic_external_20260306_162834.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,14,Push,10841.0,8026.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,15,Mobile Application,7850.0,6102.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1,Paid Search,1798.0,342.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,5,Direct,1058.0,395.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,6,Session Refresh,145.0,100.0,OK,NaN

In [35]:
#### **Homepage KV GNB TO CMP**

In [36]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_3_homepage_kv_gnb_to_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:40:37
▶ Output: aa_exports\25_ny_3_3_homepage_kv_gnb_to_cmp_20260306_164037.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites): 100%|██████████| 46/46 [00:24<00:00,  1.85site/s, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_3_homepage_kv_gnb_to_cmp_20260306_164037.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:25.171149
❌ 실패 site: 0
DONE: aa_exports\25_ny_3_3_homepage_kv_gnb_to_cmp_20260306_164037.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),213396.0,248528.0,721171.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),87613.0,134516.0,244928.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),40107.0,87405.0,129069.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),148022.0,294298.0,437429.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),599554.0,672259.0,4465474.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [37]:
## **4. Order CVR**

In [38]:
#### **Order CVR Loginout**

In [39]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_4_1_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:41:02
▶ Output: aa_exports\25_ny_4_1_order_cvr_loginout_20260306_164102.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites): 100%|██████████| 46/46 [10:09<00:00, 13.26s/site, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_4_1_order_cvr_loginout_20260306_164102.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:10:10.052923
❌ 실패 site: 0
DONE: aa_exports\25_ny_4_1_order_cvr_loginout_20260306_164102.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,11983.0,11695.0,288.0,3.600886e+07,3.494312e+07,1.065741e+06,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,15150.0,8136.0,7014.0,8.550152e+06,4.823281e+06,3.726871e+06,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,8673.0,3778.0,4895.0,6.982387e+06,3.040050e+06,3.942337e+06,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,16637.0,10431.0,6206.0,1.141419e+07,7.517195e+06,3.896991e+06,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,127076.0,125218.0,1858.0,5.848669e+10,5.811453e+10,3.721645e+08,OK,NaN

In [40]:
#### **Scom Order CVR Loginout**

In [41]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_4_1_scom_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:51:13
▶ Output: aa_exports\25_ny_4_1_scom_order_cvr_loginout_20260306_165113.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10']

AA Export (sites): 100%|██████████| 46/46 [01:06<00:00,  1.45s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_4_1_scom_order_cvr_loginout_20260306_165113.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:01:06.888843
❌ 실패 site: 0
DONE: aa_exports\25_ny_4_1_scom_order_cvr_loginout_20260306_165113.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),11983.0,11695.0,288.0,3.600886e+07,3.494312e+07,1.065741e+06,90830.0,15568577.0,807685.0,246647.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),15150.0,8136.0,7014.0,8.550152e+06,4.823281e+06,3.726871e+06,102056.0,1961578.0,259205.0,52908.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),8673.0,3778.0,4895.0,6.982387e+06,3.040050e+06,3.942337e+06,55795.0,876834.0,142975.0,42284.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),16637.0,10431.0,6206.0,1.141419e+07,7.517195e+06,3.896991e+06,179822.0,2996686.0,480170.0,92495.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),127076.0,125218.0,1858.0,5.848669e+10,5.811453e+10,3.721645e+08,2005422.0,6479148.0,4609889.0,1104799.0,OK,NaN

In [42]:
#### **Order CVR Visit Visitor**

In [43]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_4_2_order_cvr_visit_visitor.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:52:20
▶ Output: aa_exports\25_ny_4_2_order_cvr_visit_visitor_20260306_165220.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 46/46 [00:32<00:00,  1.42site/s, ok=1, rows=1, site=SA_EN]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_4_2_order_cvr_visit_visitor_20260306_165220.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:32.542153
❌ 실패 site: 0
DONE: aa_exports\25_ny_4_2_order_cvr_visit_visitor_20260306_165220.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,90830.0,15568577.0,807685.0,246647.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),0.0,1.0,...,0.0,0.0,0.0,0.0,102056.0,1961578.0,259205.0,52908.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,55795.0,876834.0,142975.0,42284.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,179822.0,2996686.0,480170.0,92495.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,2005422.0,6479148.0,4609889.0,1104799.0,OK,NaN

In [44]:
## **5. Campaign Order CVR**

In [45]:
#### **Campaign Order CVR**

In [46]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_5_1_campaign_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:52:54
▶ Output: aa_exports\25_ny_5_1_campaign_order_cvr_20260306_165254.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 46/46 [00:25<00:00,  1.79site/s, ok=1, rows=1, site=HU]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_5_1_campaign_order_cvr_20260306_165254.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:25.898178
❌ 실패 site: 0
DONE: aa_exports\25_ny_5_1_campaign_order_cvr_20260306_165254.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),11983.0,3.600886e+07,...,6799.0,519.0,1.653397e+07,1.366306e+07,2.859691e+06,3171.0,2803.0,366.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),15150.0,8.550152e+06,...,3294.0,152.0,2.915276e+06,2.229001e+06,1.480042e+05,1119.0,859.0,55.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),8673.0,6.982387e+06,...,1591.0,155.0,2.638545e+06,1.211356e+06,1.354065e+05,1526.0,758.0,57.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),16637.0,1.141419e+07,...,4106.0,384.0,4.505678e+06,3.211647e+06,4.045712e+05,2729.0,1930.0,199.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),127076.0,5.848669e+10,...,75544.0,1131.0,2.700545e+10,2.552641e+10,1.479039e+09,5523.0,5398.0,125.0,OK,NaN

In [47]:
#### **Scom Campaign Order CVR**

In [48]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_5_1_scom_campaign_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:53:20
▶ Output: aa_exports\25_ny_5_1_scom_campaign_order_cvr_20260306_165320.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites): 100%|██████████| 46/46 [00:31<00:00,  1.47site/s, ok=1, rows=1, site=RO]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_5_1_scom_campaign_order_cvr_20260306_165320.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:31.496857
❌ 실패 site: 0
DONE: aa_exports\25_ny_5_1_scom_campaign_order_cvr_20260306_165320.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),15659407.0,1054332.0,11983.0,3.600886e+07,5851.0,650.0,737.0,1306.0,575.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),2063634.0,312113.0,15150.0,8.550152e+06,3361.0,786.0,857.0,720.0,245.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),932629.0,185259.0,8673.0,6.982387e+06,3659.0,471.0,524.0,384.0,244.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),3176508.0,572665.0,16637.0,1.141419e+07,6119.0,359.0,421.0,338.0,148.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),8484570.0,5714688.0,127076.0,5.848669e+10,10786.0,3169.0,3619.0,5439.0,451.0,OK,NaN

In [49]:
#### **Scom Order CVR**

In [50]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_5_1_scom_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:53:52
▶ Output: aa_exports\25_ny_5_1_scom_order_cvr_20260306_165352.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:39<00:00,  1.18site/s, ok=1, rows=1, site=CO]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_5_1_scom_order_cvr_20260306_165352.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:39.305643
❌ 실패 site: 0
DONE: aa_exports\25_ny_5_1_scom_order_cvr_20260306_165352.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [51]:
## **6. S.com Cross Sell Order**

In [52]:
#### **Multi Order Cross Sell**

In [53]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_6_1_multi_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:54:32
▶ Output: aa_exports\25_ny_6_1_multi_order_cross_sell_20260306_165432.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [02:22<00:00,  3.09s/site, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_6_1_multi_order_cross_sell_20260306_165432.csv
총 데이터 row (FAILED row 제외, header 제외): 38
⏱ Elapsed: 0:02:22.726610
❌ 실패 site: 0
DONE: aa_exports\25_ny_6_1_multi_order_cross_sell_20260306_165432.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,5851.0,3.369854e+07,...,392.0,3.856493e+06,33.0,3.147458e+05,125.0,8.155335e+05,33.0,3.147458e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,0,NaN,3361.0,2.915251e+06,...,21.0,2.513535e+04,25.0,5.316994e+04,237.0,3.213712e+05,0.0,0.000000e+00,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0,NaN,3659.0,4.403713e+06,...,93.0,1.161292e+05,18.0,3.211317e+04,15.0,1.722082e+04,0.0,0.000000e+00,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,0,NaN,6119.0,6.475893e+06,...,282.0,3.985968e+05,14.0,3.425078e+04,13.0,9.569410e+03,4.0,1.363218e+04,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,10786.0,8.401757e+09,...,82.0,1.336280e+08,206.0,1.051318e+09,82.0,1.051916e+08,18.0,1.272995e+08,OK,NaN

In [54]:
#### **Total Order Cross Sell**

In [55]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_6_2_total_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:56:55
▶ Output: aa_exports\25_ny_6_2_total_order_cross_sell_20260306_165655.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:48<00:00,  1.05s/site, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_6_2_total_order_cross_sell_20260306_165655.csv
총 데이터 row (FAILED row 제외, header 제외): 40
⏱ Elapsed: 0:00:48.753321
❌ 실패 site: 0
DONE: aa_exports\25_ny_6_2_total_order_cross_sell_20260306_165655.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,11983.0,3.600886e+07,...,392.0,3.856493e+06,33.0,3.147458e+05,125.0,8.155335e+05,33.0,3.147458e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,0,NaN,15150.0,8.550152e+06,...,21.0,2.513535e+04,25.0,5.316994e+04,237.0,3.213712e+05,0.0,0.000000e+00,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,0,NaN,8673.0,6.982387e+06,...,93.0,1.161292e+05,18.0,3.211317e+04,15.0,1.722082e+04,0.0,0.000000e+00,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,0,NaN,16637.0,1.141419e+07,...,282.0,3.985968e+05,14.0,3.425078e+04,13.0,9.569410e+03,4.0,1.363218e+04,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,127076.0,5.848669e+10,...,82.0,1.336280e+08,206.0,1.051318e+09,82.0,1.051916e+08,18.0,1.272995e+08,OK,NaN

In [56]:
#### **CMP Order Cross Sell**

In [57]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_6_3_cmp_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:57:45
▶ Output: aa_exports\25_ny_6_3_cmp_order_cross_sell_20260306_165745.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:40<00:00,  1.14site/s, ok=1, rows=1, site=CA]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_6_3_cmp_order_cross_sell_20260306_165745.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:00:40.450334
❌ 실패 site: 0
DONE: aa_exports\25_ny_6_3_cmp_order_cross_sell_20260306_165745.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2025-02-17,2025-03-05,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-02-19,2025-03-12,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [58]:
## **7. Order Conversion/Traffic by Channel**

In [59]:
#### **Order BY Channel CMP**

In [60]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_7_1_order_by_channel_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:58:26
▶ Output: aa_exports\25_ny_7_1_order_by_channel_cmp_20260306_165826.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15']

AA Export (sites): 100%|██████████| 46/46 [00:44<00:00,  1.04site/s, ok=1, rows=0, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_7_1_order_by_channel_cmp_20260306_165826.csv
총 데이터 row (FAILED row 제외, header 제외): 8
⏱ Elapsed: 0:00:44.470859
❌ 실패 site: 0
DONE: aa_exports\25_ny_7_1_order_by_channel_cmp_20260306_165826.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value8,value9,value10,value11,value12,value13,value14,value15,status,error
0,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2025-02-20,2025-03-08,5,Direct,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SEPOL,Poland,PL,sssamsung4pl,2025-01-19,2025-02-05,5,Direct,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEPOL,Poland,PL,sssamsung4pl,2025-01-19,2025-02-05,18,Paid Others,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEPOL,Poland,PL,sssamsung4pl,2025-01-19,2025-02-05,2,Natural Search,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
4,SEPAK,Pakistan,PK,sssamsung4pk,2025-01-16,2025-01-31,12,Other,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [63]:
## **Multi Purchase**

In [64]:
#### **RAW Multi Purchase V41**

In [65]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_raw_multi_purchase_v41.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:59:34
▶ Output: aa_exports\25_ny_raw_multi_purchase_v41_20260306_165934.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:10<00:00,  4.48site/s, ok=1, rows=947, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_raw_multi_purchase_v41_20260306_165934.csv
총 데이터 row (FAILED row 제외, header 제외): 46,930
⏱ Elapsed: 0:00:11.500083
❌ 실패 site: 0
DONE: aa_exports\25_ny_raw_multi_purchase_v41_20260306_165934.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,909682801,EF-US921CTEGCN,0.0,0.0,0.0,720.0,50.0,7020.52,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,2186785383,SM-S9280ZTHCHC,0.0,0.0,0.0,291.0,103.0,841684.58,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1029253768,"SM-R630NZAACHC,30YUANMX",0.0,0.0,0.0,282.0,141.0,78911.73,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,4071345644,EF-ZF731CTEGCN,0.0,0.0,0.0,261.0,4.0,2533.85,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,3412643844,EF-UF731CTEGCN,0.0,0.0,0.0,250.0,4.0,2415.99,OK,NaN

In [66]:
## **Best Selling Product**

In [67]:
#### **Bestselling**

In [68]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_bestselling.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:59:46
▶ Output: aa_exports\25_ny_bestselling_20260306_165946.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 46/46 [00:18<00:00,  2.49site/s, ok=1, rows=213, site=SA]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_bestselling_20260306_165946.csv
총 데이터 row (FAILED row 제외, header 제외): 12,840
⏱ Elapsed: 0:00:18.885042
❌ 실패 site: 0
DONE: aa_exports\25_ny_bestselling_20260306_165946.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,2983901684,NaN,2541.0,0.00,0.0,0.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,3309145458,HUAFEI,1970.0,0.00,0.0,0.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1107069323,3WYGJFWQYZP,1168.0,0.00,0.0,0.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1802553923,TRADE-IN,1036.0,0.00,0.0,0.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,445878911,EF-US921,954.0,15441.03,0.0,0.0,OK,NaN

In [69]:
## **Next Page**

In [70]:
#### **Nextpage**

In [ ]:
## **CC (Contents)**

In [ ]:
#### **CC Order**

In [ ]:
#### **CC Revenue**

In [ ]:
#### **CC Visit**

# **CSV to Excel Raw Sheet Format**

In [ ]:
# 후처리 코드를 여기에 추가하세요.