In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic APP**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_da_traffic_app_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-06 15:43:28
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260306_154328.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [13:10<00:00, 17.18s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260306_154328.csv
총 데이터 row (FAILED row 제외, header 제외): 28
⏱ Elapsed: 0:13:10.619434
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260306_154328.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,6640.0,6206.0,...,0.0,0.0,5.0,5.0,0.0,1.757322e+04,1.757322e+04,0.000000e+00,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0,NaN,4881.0,3561.0,...,0.0,0.0,164.0,113.0,37.0,1.542703e+05,9.850836e+04,4.624405e+04,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,0,NaN,4422.0,3029.0,...,3.0,1.0,165.0,109.0,38.0,1.343038e+05,9.278230e+04,2.541684e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,0,NaN,10855.0,8817.0,...,3.0,16.0,300.0,218.0,62.0,2.260912e+05,1.564862e+05,5.154558e+04,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,248678.0,230462.0,...,85433.0,1801.0,5288.0,4207.0,1081.0,5.983223e+09,4.533876e+09,1.449348e+09,OK,NaN

In [5]:
#### **Scom DA Traffic WEB**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_da_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:56:39
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260306_155639.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:30<00:00,  1.50site/s, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260306_155639.csv
총 데이터 row (FAILED row 제외, header 제외): 44
⏱ Elapsed: 0:00:30.847508
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260306_155639.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,31081.0,73130.0,...,24924.0,28944.0,12214.0,27511.0,5.0,5.0,5.470790e+04,3.362691e+04,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0,NaN,17044.0,34536.0,...,10898.0,25117.0,2111.0,7728.0,226.0,338.0,2.178525e+05,2.783552e+05,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,0,NaN,15404.0,22522.0,...,10951.0,15989.0,3304.0,5207.0,203.0,140.0,1.534891e+05,9.714882e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,0,NaN,41107.0,69893.0,...,27828.0,50225.0,11103.0,17770.0,461.0,512.0,3.932499e+05,3.825792e+05,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,505249.0,1153449.0,...,370329.0,985623.0,233998.0,569390.0,4811.0,9164.0,5.122399e+09,4.012197e+09,OK,NaN

In [7]:
#### **Scom MX Traffic APP**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_mx_traffic_app_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:57:10
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260306_155710.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [05:14<00:00,  6.84s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260306_155710.csv
총 데이터 row (FAILED row 제외, header 제외): 31
⏱ Elapsed: 0:05:14.883791
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260306_155710.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,228205.0,209298.0,...,11.0,12.0,1802.0,1645.0,154.0,5.824285e+06,4.732494e+06,1.085026e+06,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0,NaN,47736.0,37553.0,...,5.0,0.0,1352.0,1130.0,60.0,9.184057e+05,7.431320e+05,6.434749e+04,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,0,NaN,37355.0,29192.0,...,47.0,7.0,1192.0,970.0,92.0,1.077867e+06,8.735770e+05,8.919546e+04,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,0,NaN,85325.0,71235.0,...,28.0,4.0,2118.0,1834.0,122.0,1.019595e+06,8.619162e+05,7.719911e+04,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,620313.0,597074.0,...,89233.0,2526.0,13083.0,12045.0,1038.0,1.303434e+10,1.169493e+10,1.339406e+09,OK,NaN

In [9]:
#### **Scom MX Traffic WEB**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_mx_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:26
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260306_160226.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [01:10<00:00,  1.52s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260306_160226.csv
총 데이터 row (FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:01:10.265084
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260306_160226.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0.0,NaN,244843.0,1240479.0,...,157360.0,1100578.0,72534.0,833119.0,603.0,374.0,6.679554e+06,1.997633e+06,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0.0,NaN,98722.0,306868.0,...,65980.0,249342.0,13774.0,91301.0,1588.0,2654.0,1.312296e+06,2.011592e+06,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,0.0,NaN,64126.0,257339.0,...,45087.0,214943.0,11627.0,81958.0,731.0,1084.0,6.100240e+05,1.077363e+06,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0.0,NaN,836860.0,2176655.0,...,590226.0,1906856.0,210781.0,772711.0,8498.0,8512.0,1.152842e+10,6.096868e+09,OK,NaN

In [11]:
#### **Scom VD Traffic APP**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_vd_traffic_app_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:36
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260306_160336.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 46/46 [10:57<00:00, 14.29s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260306_160336.csv
총 데이터 row (FAILED row 제외, header 제외): 27
⏱ Elapsed: 0:10:57.580434
❌ 실패 site: 2
실패 목록 (앞 50개):
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260306_160336.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0.0,NaN,17138.0,14859.0,...,0.0,3.0,111.0,74.0,37.0,5.493859e+05,3.448743e+05,2.045117e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0.0,NaN,7551.0,5162.0,...,1.0,2.0,117.0,85.0,27.0,1.343542e+05,8.682268e+04,3.946232e+04,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0.0,NaN,123232.0,115130.0,...,43183.0,954.0,1695.0,1391.0,304.0,2.940910e+09,2.436801e+09,5.041085e+08,OK,NaN

In [13]:
#### **Scom VD Traffic WEB**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_vd_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:14:35
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260306_161435.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:40<00:00,  1.14site/s, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260306_161435.csv
총 데이터 row (FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:00:40.687454
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260306_161435.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,88651.0,82889.0,...,60979.0,13237.0,29684.0,6551.0,39.0,19.0,1.874974e+05,1.369515e+05,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0,NaN,46839.0,73008.0,...,29969.0,55539.0,5635.0,16186.0,256.0,265.0,3.209481e+05,2.980329e+05,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,0,NaN,30763.0,58040.0,...,21973.0,45797.0,6064.0,18360.0,332.0,234.0,3.569231e+05,2.588445e+05,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,0,NaN,67633.0,118673.0,...,47834.0,92070.0,14742.0,30944.0,478.0,521.0,5.188545e+05,4.832032e+05,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,252575.0,341095.0,...,169677.0,261100.0,100814.0,122450.0,1840.0,2052.0,3.026781e+09,1.648715e+09,OK,NaN

In [15]:
## **2_1~4. Basic Traffic**

In [16]:
#### **Basic Traffic Scom**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:15:16
▶ Output: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260306_161516.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites): 100%|██████████| 46/46 [04:19<00:00,  5.64s/site, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260306_161516.csv
총 데이터 row (FAILED row 제외, header 제외): 46
⏱ Elapsed: 0:04:19.815484
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260306_161516.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,891083.0,3614111.0,...,8325295.0,243116.0,789158.0,748085.0,41046.0,241557.0,224377.0,17157.0,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0,NaN,244606.0,696609.0,...,2804047.0,110278.0,245181.0,208986.0,13981.0,73147.0,62469.0,8201.0,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,0,NaN,145177.0,482821.0,...,3609361.0,126808.0,207863.0,163480.0,21663.0,69679.0,51594.0,14159.0,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,0,NaN,363787.0,1204807.0,...,7081725.0,232235.0,369268.0,313894.0,29862.0,115744.0,92630.0,19004.0,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,2225713.0,7290586.0,...,18959332.0,463911.0,8165195.0,8078081.0,87112.0,6117814.0,6086674.0,31140.0,OK,NaN

In [18]:
#### **Basic Traffic Time Scom**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_time_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:19:36
▶ Output: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260306_161936.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:17<00:00,  2.66site/s, ok=1, rows=2, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260306_161936.csv
총 데이터 row (FAILED row 제외, header 제외): 75
⏱ Elapsed: 0:00:17.537508
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260306_161936.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,1250001,2025 (Jan 1-Dec 31),203.664151,279.608537,150.689386,213.208691,204.327187,348.012925,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,1260001,2026 (Jan 1-Dec 31),179.381597,295.537482,133.781869,172.805396,164.919233,338.662848,OK,NaN
2,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,1260001,2026 (Jan 1-Dec 31),595.185360,447.290240,643.828273,249.495568,240.235611,368.680891,OK,NaN
3,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,1260001,2026 (Jan 1-Dec 31),286.126360,376.434115,250.737912,293.011463,282.083534,388.930260,OK,NaN
4,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,1250001,2025 (Jan 1-Dec 31),304.419207,413.628367,273.599486,292.844176,282.787864,398.611860,OK,NaN

In [20]:
## **3. Traffic by Channel**

In [21]:
#### **Channel External Scom**

In [22]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_2_channel_external_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:19:54
▶ Output: aa_exports\26_ny_3_2_channel_external_scom_prior_20260306_161954.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 46/46 [00:20<00:00,  2.25site/s, ok=1, rows=23, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_2_channel_external_scom_prior_20260306_161954.csv
총 데이터 row (FAILED row 제외, header 제외): 937
⏱ Elapsed: 0:00:20.689147
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_2_channel_external_scom_prior_20260306_161954.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,16,Affiliate Marketing,1302359.0,1157193.0,15.0,4.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,5,Direct,1219471.0,944517.0,720275.0,227895.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,20,Display,416523.0,368778.0,12.0,7.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,15,Mobile Application,407616.0,259064.0,14791.0,2793.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,1,Paid Search,278543.0,130526.0,5072.0,571.0,OK,NaN

In [23]:
## **6. S.com Cross Sell Order**

In [24]:
#### **Multi Order Cross Sell**

In [25]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_1_multi_order_cross_sell_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:20:15
▶ Output: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260306_162015.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [01:00<00:00,  1.32s/site, ok=1, rows=1, site=TH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260306_162015.csv
총 데이터 row (FAILED row 제외, header 제외): 39
⏱ Elapsed: 0:01:00.846971
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260306_162015.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,1202.0,9.543053e+06,...,1.0,9.177760e+03,0.0,0.000000e+00,1.0,9135.20,0.0,0.00,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0,NaN,1825.0,1.935362e+06,...,5.0,6.189160e+03,23.0,3.845043e+04,31.0,83804.63,3.0,13886.33,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,0,NaN,1572.0,1.929553e+06,...,16.0,2.320513e+04,17.0,2.873957e+04,3.0,2575.20,0.0,0.00,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,0,NaN,2938.0,2.724456e+06,...,13.0,2.687793e+04,13.0,2.975699e+04,5.0,4415.86,0.0,0.00,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,7977.0,1.053722e+10,...,62.0,1.888882e+08,191.0,9.919776e+08,76.0,88103513.00,22.0,95561548.00,OK,NaN

In [26]:
#### **Total Order Cross Sell**

In [27]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_2_total_order_cross_sell_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:21:17
▶ Output: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260306_162117.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 46/46 [00:19<00:00,  2.41site/s, ok=1, rows=1, site=MY]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260306_162117.csv
총 데이터 row (FAILED row 제외, header 제외): 39
⏱ Elapsed: 0:00:19.342970
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260306_162117.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,3338.0,1.594378e+07,...,1.0,9.177760e+03,0.0,0.000000e+00,1.0,9135.20,0.0,0.00,OK,NaN
1,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-03,2026-01-19,0,NaN,7185.0,5.563869e+06,...,5.0,6.189160e+03,23.0,3.845043e+04,31.0,83804.63,3.0,13886.33,OK,NaN
2,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-02,2026-01-18,0,NaN,4407.0,4.066051e+06,...,16.0,2.320513e+04,17.0,2.873957e+04,3.0,2575.20,0.0,0.00,OK,NaN
3,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2025-12-28,2026-01-18,0,NaN,10924.0,7.157625e+06,...,13.0,2.687793e+04,13.0,2.975699e+04,5.0,4415.86,0.0,0.00,OK,NaN
4,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,76771.0,5.318667e+10,...,62.0,1.888882e+08,191.0,9.919776e+08,76.0,88103513.00,22.0,95561548.00,OK,NaN

In [28]:
## **7. Order Conversion/Traffic by Channel**

In [29]:
#### **Order BY Channel Scom**

In [30]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_7_1_order_by_channel_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:21:37
▶ Output: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260306_162137.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [00:19<00:00,  2.34site/s, ok=1, rows=23, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260306_162137.csv
총 데이터 row (FAILED row 제외, header 제외): 937
⏱ Elapsed: 0:00:19.947360
❌ 실패 site: 0
DONE: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260306_162137.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,16,Affiliate Marketing,1302359.0,15.0,178.0,0.0,1510412.69,0.00,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,5,Direct,1219471.0,720276.0,309.0,1828.0,3297999.96,5947850.75,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,20,Display,416523.0,12.0,0.0,0.0,0.00,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,15,Mobile Application,407616.0,14791.0,72.0,47.0,159592.08,166388.21,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,1,Paid Search,278543.0,5072.0,300.0,8.0,2476932.53,9917.60,OK,NaN

In [31]:
## **Multi Purchase**

In [32]:
#### **RAW Multi Purchase V41**

In [33]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_raw_multi_purchase_v41_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:21:57
▶ Output: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260306_162157.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 46/46 [01:06<00:00,  1.46s/site, ok=1, rows=786, site=SG]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260306_162157.csv
총 데이터 row (FAILED row 제외, header 제외): 23,596
⏱ Elapsed: 0:01:07.721914
❌ 실패 site: 0
DONE: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260306_162157.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,190103735,SM-S9280ZTGCHC,0.0,0.0,0.0,119.0,59.0,303176.99,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,4002195195,"SM-S9380ZKDCHC,EP-T4511XBCMCN",74.0,28.0,212171.1,116.0,40.0,303456.82,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,3876492148,"SM-W9026DRDCHC,P-GT-NUXPS6HC-BUNDLE",6.0,3.0,50996.7,108.0,54.0,917936.16,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,3667055378,"SM-S9380ZSDCHC,EP-T4511XBCMCN",30.0,10.0,75789.3,69.0,20.0,151879.10,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,2014262008,"SM-W9026AKDCHC,P-GT-NUXPS6HC-BUNDLE",0.0,0.0,0.0,68.0,34.0,577932.92,OK,NaN

# **CSV to Excel Raw Sheet Format**

In [34]:
# 후처리 코드를 여기에 추가하세요.