In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic WEB (US)**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_1_1_scom_da_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-06 15:43:41
▶ Output: aa_exports\us_26_ny_1_1_scom_da_traffic_web_20260306_154341.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.46site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_1_1_scom_da_traffic_web_20260306_154341.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.742486
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_1_1_scom_da_traffic_web_20260306_154341.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [5]:
#### **Scom MX Traffic WEB (US)**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_1_1_scom_mx_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:43:42
▶ Output: aa_exports\us_26_ny_1_1_scom_mx_traffic_web_20260306_154342.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.83site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_1_1_scom_mx_traffic_web_20260306_154342.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.566188
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_1_1_scom_mx_traffic_web_20260306_154342.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [7]:
#### **Scom VD Traffic WEB (US)**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_1_1_scom_vd_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:43:43
▶ Output: aa_exports\us_26_ny_1_1_scom_vd_traffic_web_20260306_154343.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.72site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_1_1_scom_vd_traffic_web_20260306_154343.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.603538
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_1_1_scom_vd_traffic_web_20260306_154343.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [9]:
## **2_1~4. Basic Traffic**

In [10]:
#### **Basic Traffic CMP (US)**

In [11]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_2_1_basic_traffic_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:43:44
▶ Output: aa_exports\us_26_ny_2_1_basic_traffic_cmp_20260306_154344.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.83site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_2_1_basic_traffic_cmp_20260306_154344.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.561350
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_2_1_basic_traffic_cmp_20260306_154344.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, status, error]
Index: []

[0 rows x 22 columns]

In [12]:
#### **Basic Traffic Scom (US)**

In [13]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_2_1_basic_traffic_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:43:45
▶ Output: aa_exports\us_26_ny_2_1_basic_traffic_scom_20260306_154345.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.77site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_2_1_basic_traffic_scom_20260306_154345.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.581620
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_2_1_basic_traffic_scom_20260306_154345.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, status, error]
Index: []

[0 rows x 22 columns]

In [14]:
#### **Basic Traffic Time CMP (US)**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_2_1_basic_traffic_time_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:29
▶ Output: aa_exports\us_26_ny_2_1_basic_traffic_time_cmp_20260306_160229.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.08site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_2_1_basic_traffic_time_cmp_20260306_160229.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.945080
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_2_1_basic_traffic_time_cmp_20260306_160229.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, status, error]
Index: []

In [ ]:
#### **Basic Traffic Time Scom (US)**

In [16]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_2_1_basic_traffic_time_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:45:36
▶ Output: aa_exports\us_26_ny_2_1_basic_traffic_time_scom_20260306_154536.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.69site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_2_1_basic_traffic_time_scom_20260306_154536.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.387427
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_2_1_basic_traffic_time_scom_20260306_154536.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, status, error]
Index: []

In [ ]:
## **3. Traffic by Channel**

In [ ]:
#### **Channel Internal (US)**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_3_1_channel_internal.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:45:41
▶ Output: aa_exports\us_26_ny_3_1_channel_internal_20260306_154541.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.04site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_3_1_channel_internal_20260306_154541.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.511408
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_3_1_channel_internal_20260306_154541.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, status, error]
Index: []

In [ ]:
#### **Channel External CMP (US)**

In [20]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_3_2_channel_external_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:36
▶ Output: aa_exports\us_26_ny_3_2_channel_external_cmp_20260306_160236.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.67site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_3_2_channel_external_cmp_20260306_160236.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.619331
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_3_2_channel_external_cmp_20260306_160236.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, status, error]
Index: []

In [ ]:
#### **Channel External Scom (US)**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_3_2_channel_external_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:39
▶ Output: aa_exports\us_26_ny_3_2_channel_external_scom_20260306_160239.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.85site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_3_2_channel_external_scom_20260306_160239.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.569846
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_3_2_channel_external_scom_20260306_160239.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, status, error]
Index: []

In [ ]:
#### **Homepage KV GNB TO CMP (US)**

In [22]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_3_3_homepage_kv_gnb_to_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:42
▶ Output: aa_exports\us_26_ny_3_3_homepage_kv_gnb_to_cmp_20260306_160242.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.29site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_3_3_homepage_kv_gnb_to_cmp_20260306_160242.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.460079
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_3_3_homepage_kv_gnb_to_cmp_20260306_160242.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, status, error]
Index: []

In [ ]:
## **4. Order CVR**

In [ ]:
#### **Order CVR Loginout (US)**

In [23]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_4_1_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:44
▶ Output: aa_exports\us_26_ny_4_1_order_cvr_loginout_20260306_160244.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.35site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_4_1_order_cvr_loginout_20260306_160244.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.447052
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_4_1_order_cvr_loginout_20260306_160244.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, value17, status, error]
Index: []

[0 rows x 27 columns]

In [ ]:
#### **Order CVR Visit Visitor (US)**

In [24]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_4_2_order_cvr_visit_visitor.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:47
▶ Output: aa_exports\us_26_ny_4_2_order_cvr_visit_visitor_20260306_160247.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.19site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_4_2_order_cvr_visit_visitor_20260306_160247.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.476862
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_4_2_order_cvr_visit_visitor_20260306_160247.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, status, error]
Index: []

In [ ]:
## **5. Campaign Order CVR**

In [ ]:
#### **Campaign Order CVR Total (US)**

In [25]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_5_1_campaign_order_cvr_total.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:49
▶ Output: aa_exports\us_26_ny_5_1_campaign_order_cvr_total_20260306_160249.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.14site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_5_1_campaign_order_cvr_total_20260306_160249.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.488674
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_5_1_campaign_order_cvr_total_20260306_160249.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, status, error]
Index: []

In [ ]:
## **6. S.com Cross Sell Order**

In [ ]:
#### **Multi Order Cross Sell (US)**

In [26]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_6_1_multi_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:52
▶ Output: aa_exports\us_26_ny_6_1_multi_order_cross_sell_20260306_160252.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.14site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_6_1_multi_order_cross_sell_20260306_160252.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.485948
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_6_1_multi_order_cross_sell_20260306_160252.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [ ]:
#### **Total Order Cross Sell (US)**

In [27]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_6_2_total_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:02:59
▶ Output: aa_exports\us_26_ny_6_2_total_order_cross_sell_20260306_160259.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.19site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_6_2_total_order_cross_sell_20260306_160259.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.480469
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_6_2_total_order_cross_sell_20260306_160259.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [ ]:
#### **CMP Order Cross Sell (US)**

In [28]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_6_3_cmp_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:01
▶ Output: aa_exports\us_26_ny_6_3_cmp_order_cross_sell_20260306_160301.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.13site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_6_3_cmp_order_cross_sell_20260306_160301.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.496975
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_6_3_cmp_order_cross_sell_20260306_160301.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [ ]:
## **7. Order Conversion/Traffic by Channel**

In [ ]:
#### **Order BY Channel CMP (US)**

In [29]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_7_1_order_by_channel_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:05
▶ Output: aa_exports\us_26_ny_7_1_order_by_channel_cmp_20260306_160305.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.76site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_7_1_order_by_channel_cmp_20260306_160305.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.593063
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_7_1_order_by_channel_cmp_20260306_160305.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, status, error]
Index: []

In [ ]:
#### **Order BY Channel Scom (US)**

In [30]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_7_1_order_by_channel_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:08
▶ Output: aa_exports\us_26_ny_7_1_order_by_channel_scom_20260306_160308.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.81site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_7_1_order_by_channel_scom_20260306_160308.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.574348
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_7_1_order_by_channel_scom_20260306_160308.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, status, error]
Index: []

In [ ]:
## **Multi Purchase**

In [ ]:
#### **RAW Multi Purchase V41 (US)**

In [31]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_raw_multi_purchase_v41.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:13
▶ Output: aa_exports\us_26_ny_raw_multi_purchase_v41_20260306_160313.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.07site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_raw_multi_purchase_v41_20260306_160313.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.506760
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_raw_multi_purchase_v41_20260306_160313.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, status, error]
Index: []

In [ ]:
#### **CMP Adaptive Banner (US)**

In [32]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_8_8_cmp_adaptive_banner.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:16
▶ Output: aa_exports\us_26_ny_8_8_cmp_adaptive_banner_20260306_160316.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.28site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_8_8_cmp_adaptive_banner_20260306_160316.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.458498
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_8_8_cmp_adaptive_banner_20260306_160316.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, status, error]
Index: []

In [ ]:
## **Best Selling Product**

In [ ]:
#### **Bestselling (US)**

In [33]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_bestselling.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:19
▶ Output: aa_exports\us_26_ny_bestselling_20260306_160319.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.28site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_bestselling_20260306_160319.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.456983
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_bestselling_20260306_160319.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, status, error]
Index: []

In [ ]:
## **Next Page**

In [ ]:
#### **Nextpage (US)**

In [34]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_nextpage.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 16:03:22
▶ Output: aa_exports\us_26_ny_nextpage_20260306_160322.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.10site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_nextpage_20260306_160322.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.494461
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_nextpage_20260306_160322.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, status, error]
Index: []

# **CSV to Excel Raw Sheet Format**

In [ ]:
# 후처리 코드를 여기에 추가하세요.