In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic WEB (US)**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_1_1_scom_da_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-06 15:43:56
▶ Output: aa_exports\us_25_ny_1_1_scom_da_traffic_web_20260306_154356.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.11site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_1_1_scom_da_traffic_web_20260306_154356.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.530851
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_1_1_scom_da_traffic_web_20260306_154356.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [5]:
#### **Scom MX Traffic WEB (US)**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_1_1_scom_mx_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:43:57
▶ Output: aa_exports\us_25_ny_1_1_scom_mx_traffic_web_20260306_154357.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.99site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_1_1_scom_mx_traffic_web_20260306_154357.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.515342
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_1_1_scom_mx_traffic_web_20260306_154357.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [7]:
#### **Scom VD Traffic WEB (US)**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_1_1_scom_vd_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:43:58
▶ Output: aa_exports\us_25_ny_1_1_scom_vd_traffic_web_20260306_154358.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.98site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_1_1_scom_vd_traffic_web_20260306_154358.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.511873
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_1_1_scom_vd_traffic_web_20260306_154358.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [9]:
## **2_1~4. Basic Traffic**

In [10]:
#### **Basic Traffic Scom (US)**

In [11]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_2_1_basic_traffic_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:43:59
▶ Output: aa_exports\us_25_ny_2_1_basic_traffic_scom_20260306_154359.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.05site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_2_1_basic_traffic_scom_20260306_154359.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.512306
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_2_1_basic_traffic_scom_20260306_154359.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, status, error]
Index: []

[0 rows x 22 columns]

In [12]:
#### **Basic Traffic Time Scom (US)**

In [13]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_2_1_basic_traffic_time_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:00
▶ Output: aa_exports\us_25_ny_2_1_basic_traffic_time_scom_20260306_154400.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.24site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_2_1_basic_traffic_time_scom_20260306_154400.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.467790
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_2_1_basic_traffic_time_scom_20260306_154400.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, status, error]
Index: []

In [14]:
## **4. Order CVR**

In [15]:
#### **Order CVR Loginout (US)**

In [16]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_4_1_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:02
▶ Output: aa_exports\us_25_ny_4_1_order_cvr_loginout_20260306_154402.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.19site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_4_1_order_cvr_loginout_20260306_154402.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.479745
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_4_1_order_cvr_loginout_20260306_154402.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, value17, status, error]
Index: []

[0 rows x 27 columns]

In [17]:
#### **Scom Order CVR Loginout (US)**

In [18]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_4_1_scom_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:03
▶ Output: aa_exports\us_25_ny_4_1_scom_order_cvr_loginout_20260306_154403.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.17site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_4_1_scom_order_cvr_loginout_20260306_154403.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.483193
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_4_1_scom_order_cvr_loginout_20260306_154403.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, status, error]
Index: []

In [19]:
## **5. Campaign Order CVR**

In [20]:
#### **Scom Campaign Order CVR (US)**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_5_1_scom_campaign_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:04
▶ Output: aa_exports\us_25_ny_5_1_scom_campaign_order_cvr_20260306_154404.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.17site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_5_1_scom_campaign_order_cvr_20260306_154404.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.484242
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_5_1_scom_campaign_order_cvr_20260306_154404.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, status, error]
Index: []

In [22]:
## **6. S.com Cross Sell Order**

In [23]:
#### **Multi Order Cross Sell (US)**

In [24]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_6_1_multi_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:05
▶ Output: aa_exports\us_25_ny_6_1_multi_order_cross_sell_20260306_154405.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.30site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_6_1_multi_order_cross_sell_20260306_154405.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.463326
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_6_1_multi_order_cross_sell_20260306_154405.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [25]:
#### **Total Order Cross Sell (US)**

In [26]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_6_2_total_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:06
▶ Output: aa_exports\us_25_ny_6_2_total_order_cross_sell_20260306_154406.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.21site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_6_2_total_order_cross_sell_20260306_154406.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.478017
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_6_2_total_order_cross_sell_20260306_154406.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [27]:
## **7. Order Conversion/Traffic by Channel**

In [28]:
#### **Order BY Channel Scom (US)**

In [29]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_7_1_order_by_channel_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:07
▶ Output: aa_exports\us_25_ny_7_1_order_by_channel_scom_20260306_154407.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.70site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_7_1_order_by_channel_scom_20260306_154407.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.606831
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_7_1_order_by_channel_scom_20260306_154407.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, status, error]
Index: []

In [30]:
## **Multi Purchase**

In [31]:
#### **RAW Multi Purchase V41 (US)**

In [32]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_25_ny_raw_multi_purchase_v41.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:08
▶ Output: aa_exports\us_25_ny_raw_multi_purchase_v41_20260306_154408.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.23site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_25_ny_raw_multi_purchase_v41_20260306_154408.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.464016
❌ 실패 site: 0
DONE: aa_exports\us_25_ny_raw_multi_purchase_v41_20260306_154408.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, status, error]
Index: []

# **CSV to Excel Raw Sheet Format**

In [33]:
# 후처리 코드를 여기에 추가하세요.