In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic WEB (US)**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_1_1_scom_da_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-06 15:44:10
▶ Output: aa_exports\us_26_ny_1_1_scom_da_traffic_web_prior_20260306_154410.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.30site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_1_1_scom_da_traffic_web_prior_20260306_154410.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.495690
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_1_1_scom_da_traffic_web_prior_20260306_154410.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [5]:
#### **Scom MX Traffic WEB (US)**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_1_1_scom_mx_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:11
▶ Output: aa_exports\us_26_ny_1_1_scom_mx_traffic_web_prior_20260306_154411.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.09site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_1_1_scom_mx_traffic_web_prior_20260306_154411.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.498499
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_1_1_scom_mx_traffic_web_prior_20260306_154411.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [7]:
#### **Scom VD Traffic WEB (US)**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_1_1_scom_vd_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:12
▶ Output: aa_exports\us_26_ny_1_1_scom_vd_traffic_web_prior_20260306_154412.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.05site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_1_1_scom_vd_traffic_web_prior_20260306_154412.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.502213
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_1_1_scom_vd_traffic_web_prior_20260306_154412.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [9]:
## **2_1~4. Basic Traffic**

In [10]:
#### **Basic Traffic Scom (US)**

In [11]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_2_1_basic_traffic_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:13
▶ Output: aa_exports\us_26_ny_2_1_basic_traffic_scom_prior_20260306_154413.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.05site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_2_1_basic_traffic_scom_prior_20260306_154413.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.512044
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_2_1_basic_traffic_scom_prior_20260306_154413.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, status, error]
Index: []

[0 rows x 22 columns]

In [12]:
#### **Basic Traffic Time Scom (US)**

In [13]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_2_1_basic_traffic_time_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:14
▶ Output: aa_exports\us_26_ny_2_1_basic_traffic_time_scom_prior_20260306_154414.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.54site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_2_1_basic_traffic_time_scom_prior_20260306_154414.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.415252
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_2_1_basic_traffic_time_scom_prior_20260306_154414.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, status, error]
Index: []

In [14]:
## **3. Traffic by Channel**

In [15]:
#### **Channel External Scom (US)**

In [16]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_3_2_channel_external_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:15
▶ Output: aa_exports\us_26_ny_3_2_channel_external_scom_prior_20260306_154415.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  1.90site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_3_2_channel_external_scom_prior_20260306_154415.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.542897
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_3_2_channel_external_scom_prior_20260306_154415.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, status, error]
Index: []

In [17]:
## **6. S.com Cross Sell Order**

In [18]:
#### **Multi Order Cross Sell (US)**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_6_1_multi_order_cross_sell_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:16
▶ Output: aa_exports\us_26_ny_6_1_multi_order_cross_sell_prior_20260306_154416.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.27site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_6_1_multi_order_cross_sell_prior_20260306_154416.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.463751
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_6_1_multi_order_cross_sell_prior_20260306_154416.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [20]:
#### **Total Order Cross Sell (US)**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_6_2_total_order_cross_sell_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:17
▶ Output: aa_exports\us_26_ny_6_2_total_order_cross_sell_prior_20260306_154417.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.49site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_6_2_total_order_cross_sell_prior_20260306_154417.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.422269
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_6_2_total_order_cross_sell_prior_20260306_154417.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15, value16, status, error]
Index: []

[0 rows x 26 columns]

In [22]:
## **7. Order Conversion/Traffic by Channel**

In [23]:
#### **Order BY Channel Scom (US)**

In [24]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_7_1_order_by_channel_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:18
▶ Output: aa_exports\us_26_ny_7_1_order_by_channel_scom_prior_20260306_154418.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.09site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_7_1_order_by_channel_scom_prior_20260306_154418.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.493509
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_7_1_order_by_channel_scom_prior_20260306_154418.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, status, error]
Index: []

In [25]:
## **Multi Purchase**

In [26]:
#### **RAW Multi Purchase V41 (US)**

In [27]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "us_26_ny_raw_multi_purchase_v41_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="us_26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-06 15:44:19
▶ Output: aa_exports\us_26_ny_raw_multi_purchase_v41_prior_20260306_154419.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 1/1 [00:00<00:00,  2.68site/s, ok=1, rows=0, site=US]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\us_26_ny_raw_multi_purchase_v41_prior_20260306_154419.csv
총 데이터 row (FAILED row 제외, header 제외): 0
⏱ Elapsed: 0:00:00.384130
❌ 실패 site: 0
DONE: aa_exports\us_26_ny_raw_multi_purchase_v41_prior_20260306_154419.csv

Empty DataFrame
Columns: [Subsidiary, Country, Site_Code, RSID, Start_Date, End_Date, itemId, value, value1, value2, value3, value4, value5, value6, status, error]
Index: []

# **CSV to Excel Raw Sheet Format**

In [28]:
# 후처리 코드를 여기에 추가하세요.