In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic APP**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_da_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-04 10:28:46
▶ Output: aa_exports\25_ny_1_1_scom_da_traffic_app_20260304_102846.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [09:32<00:00, 40.90s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_da_traffic_app_20260304_102846.csv
총 데이터 row (FAILED row 제외, header 제외): 12
⏱ Elapsed: 0:09:32.807797
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_da_traffic_app_20260304_102846.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,11951.0,11303.0,...,1.0,9.0,97.0,91.0,6.0,5.429676e+05,4.974562e+05,4.551136e+04,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,233172.0,225998.0,...,30522.0,865.0,5711.0,5326.0,385.0,4.770468e+09,4.266817e+09,5.036505e+08,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0,NaN,11286.0,9150.0,...,33.0,25.0,352.0,198.0,65.0,3.041485e+05,1.593671e+05,6.544539e+04,OK,NaN
3,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-01-19,2025-02-26,0,NaN,5756.0,4196.0,...,7.0,42.0,185.0,84.0,98.0,5.920614e+05,2.591916e+05,3.298974e+05,OK,NaN
4,SESAR,Saudi Arabia (en),SA_EN,sssamsung4saen,2025-01-19,2025-02-26,0,NaN,2150.0,1599.0,...,1.0,21.0,87.0,52.0,35.0,2.776157e+05,1.504044e+05,1.272114e+05,OK,NaN

In [5]:
#### **Scom DA Traffic WEB**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_da_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:38:19
▶ Output: aa_exports\25_ny_1_1_scom_da_traffic_web_20260304_103819.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [01:53<00:00,  8.10s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_da_traffic_web_20260304_103819.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:53.618319
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_da_traffic_web_20260304_103819.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,118523.0,352763.0,...,79213.0,336406.0,17202.0,293394.0,68.0,160.0,6.276053e+05,1.014692e+06,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,408839.0,976304.0,...,267123.0,822801.0,155075.0,464061.0,6389.0,9825.0,5.538583e+09,4.513541e+09,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,0,NaN,540.0,1685.0,...,385.0,1351.0,95.0,356.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0,NaN,46210.0,91875.0,...,32310.0,64319.0,5751.0,13812.0,146.0,103.0,7.285125e+04,5.008872e+04,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,0,NaN,12939.0,33269.0,...,9935.0,29034.0,3449.0,17215.0,112.0,136.0,3.075450e+06,3.162322e+06,OK,NaN

In [7]:
#### **Scom MX Traffic APP**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_mx_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:40:14
▶ Output: aa_exports\25_ny_1_1_scom_mx_traffic_app_20260304_104014.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [04:56<00:00, 21.18s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_mx_traffic_app_20260304_104014.csv
총 데이터 row (FAILED row 제외, header 제외): 12
⏱ Elapsed: 0:04:56.870475
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\25_ny_1_1_scom_mx_traffic_app_20260304_104014.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0.0,NaN,426460.0,401683.0,...,52.0,16.0,6930.0,6489.0,435.0,1.585718e+07,1.326240e+07,2.584182e+06,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0.0,NaN,1478892.0,1470793.0,...,171873.0,883.0,68376.0,67739.0,637.0,2.105035e+10,2.016458e+10,8.857682e+08,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,0.0,NaN,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0.0,NaN,90734.0,85564.0,...,9.0,4.0,2434.0,1872.0,124.0,1.438060e+06,1.033291e+06,1.128094e+05,OK,NaN
4,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-01-19,2025-02-26,0.0,NaN,126752.0,108347.0,...,45.0,41.0,5083.0,4049.0,1008.0,2.000964e+07,1.559408e+07,4.322259e+06,OK,NaN

In [9]:
#### **Scom MX Traffic WEB**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_mx_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:45:11
▶ Output: aa_exports\25_ny_1_1_scom_mx_traffic_web_20260304_104511.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [03:12<00:00, 13.77s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_mx_traffic_web_20260304_104511.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:03:12.962741
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\25_ny_1_1_scom_mx_traffic_web_20260304_104511.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0.0,NaN,447080.0,6668933.0,...,325601.0,6494763.0,134688.0,5599404.0,1564.0,2691.0,6.801867e+06,1.053508e+07,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0.0,NaN,1042101.0,2699612.0,...,819058.0,2414291.0,252540.0,1184832.0,14042.0,12736.0,1.155741e+10,7.187770e+09,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,0.0,NaN,13176.0,187401.0,...,12287.0,179519.0,3671.0,110030.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0.0,NaN,157695.0,468905.0,...,126768.0,415374.0,30395.0,102594.0,752.0,778.0,4.682956e+05,3.585673e+05,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,0.0,NaN,73456.0,765129.0,...,63624.0,742020.0,25813.0,549471.0,613.0,947.0,2.974507e+07,4.807987e+07,OK,NaN

In [11]:
#### **Scom VD Traffic APP**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_vd_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:48:25
▶ Output: aa_exports\25_ny_1_1_scom_vd_traffic_app_20260304_104825.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [05:00<00:00, 21.47s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_vd_traffic_app_20260304_104825.csv
총 데이터 row (FAILED row 제외, header 제외): 12
⏱ Elapsed: 0:05:00.722765
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_vd_traffic_app_20260304_104825.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,41762.0,37952.0,...,8.0,28.0,187.0,127.0,60.0,1.168806e+06,8.615884e+05,3.072177e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,105194.0,102533.0,...,18865.0,440.0,789.0,727.0,62.0,1.496895e+09,1.334236e+09,1.626587e+08,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0,NaN,13145.0,9894.0,...,14.0,52.0,538.0,301.0,116.0,4.516965e+05,2.212219e+05,1.247573e+05,OK,NaN
3,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-01-19,2025-02-26,0,NaN,10210.0,7305.0,...,87.0,155.0,195.0,95.0,98.0,5.998902e+05,2.872722e+05,3.069247e+05,OK,NaN
4,SESAR,Saudi Arabia (en),SA_EN,sssamsung4saen,2025-01-19,2025-02-26,0,NaN,3297.0,2572.0,...,10.0,42.0,82.0,47.0,34.0,2.666017e+05,1.612784e+05,1.044093e+05,OK,NaN

In [13]:
#### **Scom VD Traffic WEB**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_1_1_scom_vd_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:53:26
▶ Output: aa_exports\25_ny_1_1_scom_vd_traffic_web_20260304_105326.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [01:33<00:00,  6.68s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_1_1_scom_vd_traffic_web_20260304_105326.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:33.598984
❌ 실패 site: 0
DONE: aa_exports\25_ny_1_1_scom_vd_traffic_web_20260304_105326.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,514214.0,334200.0,...,476561.0,299996.0,86252.0,249364.0,179.0,222.0,1.664202e+06,2.207849e+06,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,168390.0,306392.0,...,100286.0,250651.0,35406.0,92487.0,1083.0,647.0,2.029926e+09,1.029330e+09,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,0,NaN,963.0,2584.0,...,626.0,1887.0,175.0,488.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0,NaN,47023.0,80218.0,...,32350.0,63679.0,6476.0,15892.0,133.0,62.0,1.226538e+05,4.146616e+04,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,0,NaN,22976.0,87017.0,...,18677.0,80426.0,8269.0,52261.0,49.0,60.0,1.792586e+06,2.135689e+06,OK,NaN

In [15]:
## **2_1~4. Basic Traffic**

In [16]:
#### **Basic Traffic CMP**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_2_1_basic_traffic_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:55:00
▶ Output: aa_exports\25_ny_2_1_basic_traffic_cmp_20260304_105500.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30', 'value31', 'value32', 'value33', 'value34', 'value35']

AA Export (sites): 100%|██████████| 14/14 [05:47<00:00, 24.84s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_2_1_basic_traffic_cmp_20260304_105500.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:05:47.941867
❌ 실패 site: 0
DONE: aa_exports\25_ny_2_1_basic_traffic_cmp_20260304_105500.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value28,value29,value30,value31,value32,value33,value34,value35,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),3697.0,21506.0,...,475.0,186.0,268.0,214.0,54.0,0.0,0.0,0.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),180225.0,439680.0,...,20268.0,756.0,12745.0,12402.0,342.0,0.0,0.0,0.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,1250001,2025 (Jan 1-Dec 31),2928.0,8220.0,...,4.0,79.0,25.0,1.0,24.0,0.0,0.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,1250001,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [18]:
#### **Basic Traffic Scom**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_2_1_basic_traffic_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:00:49
▶ Output: aa_exports\25_ny_2_1_basic_traffic_scom_20260304_110049.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites): 100%|██████████| 14/14 [04:18<00:00, 18.48s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_2_1_basic_traffic_scom_20260304_110049.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:04:19.263012
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\25_ny_2_1_basic_traffic_scom_20260304_110049.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0.0,NaN,2998186.0,12661221.0,...,13314935.0,603259.0,1054302.0,999545.0,54725.0,333877.0,317437.0,16424.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0.0,NaN,2356504.0,6128066.0,...,25052052.0,188286.0,5714688.0,5680379.0,34286.0,2766096.0,2752703.0,13388.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,0.0,NaN,18581.0,267785.0,...,6.0,1.0,3.0,2.0,1.0,1.0,0.0,1.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0.0,NaN,306448.0,937318.0,...,8212456.0,651304.0,326797.0,288166.0,36796.0,100199.0,80851.0,17873.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,0.0,NaN,137922.0,1315393.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [20]:
#### **Basic Traffic Time**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_2_1_basic_traffic_time.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:05:09
▶ Output: aa_exports\25_ny_2_1_basic_traffic_time_20260304_110509.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [02:39<00:00, 11.42s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_2_1_basic_traffic_time_20260304_110509.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:02:40.938487
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\25_ny_2_1_basic_traffic_time_20260304_110509.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001.0,2025 (Jan 1-Dec 31),31.569003,77.089385,23.039324,30.564689,29.600567,45.890643,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001.0,2025 (Jan 1-Dec 31),131.621152,133.283291,178.994401,62.924235,61.807888,145.592969,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,1250001.0,2025 (Jan 1-Dec 31),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,1250001.0,2025 (Jan 1-Dec 31),76.555914,111.574518,69.579433,52.367257,50.191394,67.253219,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,1250001.0,2025 (Jan 1-Dec 31),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,OK,NaN

In [22]:
## **3. Traffic by Channel**

In [23]:
#### **Channel Internal**

In [24]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_1_channel_internal.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:07:51
▶ Output: aa_exports\25_ny_3_1_channel_internal_20260304_110751.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites): 100%|██████████| 14/14 [03:45<00:00, 16.07s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_1_channel_internal_20260304_110751.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:03:45.538214
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\25_ny_3_1_channel_internal_20260304_110751.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001.0,2025 (Jan 1-Dec 31),200.0,448.0,...,0.0,0.0,3.0,11323.0,3508.0,0.0,0.0,3.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001.0,2025 (Jan 1-Dec 31),1180.0,0.0,...,0.0,0.0,46.0,5123.0,49.0,0.0,0.0,1.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,1250001.0,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,1250001.0,2025 (Jan 1-Dec 31),110.0,104.0,...,0.0,0.0,0.0,1496.0,0.0,0.0,0.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,1250001.0,2025 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [25]:
#### **Channel External Scom**

In [26]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_2_channel_external_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:11:37
▶ Output: aa_exports\25_ny_3_2_channel_external_scom_20260304_111137.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 14/14 [00:33<00:00,  2.39s/site, ok=1, rows=24, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_2_channel_external_scom_20260304_111137.csv
총 데이터 row (FAILED row 제외, header 제외): 282
⏱ Elapsed: 0:00:33.607605
❌ 실패 site: 0
DONE: aa_exports\25_ny_3_2_channel_external_scom_20260304_111137.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,16,Affiliate Marketing,7430048.0,5423596.0,0.0,0.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,20,Display,2772673.0,2318423.0,626.0,74.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,11,Social Media Campaigns,2185634.0,2002039.0,6524.0,1774.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,5,Direct,1278578.0,964822.0,908205.0,295408.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1,Paid Search,428209.0,136685.0,676.0,169.0,OK,NaN

In [27]:
#### **Channel Traffic External**

In [28]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_2_channel_traffic_external.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:12:11
▶ Output: aa_exports\25_ny_3_2_channel_traffic_external_20260304_111211.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2']

AA Export (sites): 100%|██████████| 14/14 [00:35<00:00,  2.55s/site, ok=1, rows=17, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_2_channel_traffic_external_20260304_111211.csv
총 데이터 row (FAILED row 제외, header 제외): 144
⏱ Elapsed: 0:00:35.765238
❌ 실패 site: 0
DONE: aa_exports\25_ny_3_2_channel_traffic_external_20260304_111211.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,14,Push,10841.0,8026.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,15,Mobile Application,7850.0,6102.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1,Paid Search,1798.0,342.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,5,Direct,1058.0,395.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,6,Session Refresh,145.0,100.0,OK,NaN

In [29]:
#### **Homepage KV GNB TO CMP**

In [30]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_3_3_homepage_kv_gnb_to_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:12:48
▶ Output: aa_exports\25_ny_3_3_homepage_kv_gnb_to_cmp_20260304_111248.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites): 100%|██████████| 14/14 [02:35<00:00, 11.12s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_3_3_homepage_kv_gnb_to_cmp_20260304_111248.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:02:35.754824
❌ 실패 site: 0
DONE: aa_exports\25_ny_3_3_homepage_kv_gnb_to_cmp_20260304_111248.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),213396.0,248528.0,721168.0,448.0,521.0,11323.0,68.0,14.0,3.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),599554.0,672259.0,4465474.0,0.0,0.0,5123.0,365.0,328.0,2.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,1250001,2025 (Jan 1-Dec 31),1901.0,7203.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,1250001,2025 (Jan 1-Dec 31),59843.0,137000.0,225267.0,104.0,80.0,1496.0,53.0,10.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,1250001,2025 (Jan 1-Dec 31),18515.0,97942.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [31]:
## **4. Order CVR**

In [32]:
#### **Order CVR Loginout**

In [33]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_4_1_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:15:24
▶ Output: aa_exports\25_ny_4_1_order_cvr_loginout_20260304_111524.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10']

AA Export (sites): 100%|██████████| 14/14 [02:11<00:00,  9.37s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_4_1_order_cvr_loginout_20260304_111524.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:02:11.248010
❌ 실패 site: 0
DONE: aa_exports\25_ny_4_1_order_cvr_loginout_20260304_111524.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),737.0,734.0,3.0,4.255650e+06,4.241626e+06,14024.0,1319.0,23884.0,33154.0,2742.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),3619.0,3565.0,54.0,3.351129e+09,3.339176e+09,11952400.0,73500.0,546405.0,81956.0,1709.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,1250001,2025 (Jan 1-Dec 31),0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,1250001,2025 (Jan 1-Dec 31),82.0,68.0,14.0,4.730620e+04,3.979340e+04,7512.8,928.0,10220.0,1630.0,250.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,1250001,2025 (Jan 1-Dec 31),0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [34]:
#### **Scom Order CVR Loginout**

In [35]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_4_1_scom_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:17:36
▶ Output: aa_exports\25_ny_4_1_scom_order_cvr_loginout_20260304_111736.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10']

AA Export (sites): 100%|██████████| 14/14 [01:20<00:00,  5.74s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_4_1_scom_order_cvr_loginout_20260304_111736.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:20.511441
❌ 실패 site: 0
DONE: aa_exports\25_ny_4_1_scom_order_cvr_loginout_20260304_111736.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),11983.0,11695.0,288.0,3.600886e+07,3.494312e+07,1.065741e+06,90830.0,15568577.0,807680.0,246622.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),127076.0,125218.0,1858.0,5.848669e+10,5.811453e+10,3.721645e+08,2005422.0,6479148.0,4609889.0,1104799.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,1250001,2025 (Jan 1-Dec 31),0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,1380.0,284986.0,0.0,3.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,1250001,2025 (Jan 1-Dec 31),5316.0,3598.0,1718.0,3.223818e+06,2.180507e+06,1.043311e+06,64554.0,1179212.0,253713.0,73084.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,1250001,2025 (Jan 1-Dec 31),1926.0,1126.0,800.0,8.790361e+07,5.433272e+07,3.357089e+07,22228.0,1431087.0,0.0,0.0,OK,NaN

In [36]:
## **5. Campaign Order CVR**

In [37]:
#### **Scom Campaign Order CVR**

In [38]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_5_1_scom_campaign_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:18:57
▶ Output: aa_exports\25_ny_5_1_scom_campaign_order_cvr_20260304_111857.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites): 100%|██████████| 14/14 [01:59<00:00,  8.51s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_5_1_scom_campaign_order_cvr_20260304_111857.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:59.324150
❌ 실패 site: 0
DONE: aa_exports\25_ny_5_1_scom_campaign_order_cvr_20260304_111857.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),15659407.0,1054302.0,11983.0,3.600886e+07,5851.0,650.0,737.0,1306.0,575.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),8484570.0,5714688.0,127076.0,5.848669e+10,10786.0,3169.0,3619.0,5439.0,451.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,1250001,2025 (Jan 1-Dec 31),286366.0,3.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,1250001,2025 (Jan 1-Dec 31),1243766.0,326797.0,5316.0,3.223818e+06,1313.0,67.0,82.0,147.0,19.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,1250001,2025 (Jan 1-Dec 31),1453315.0,0.0,1926.0,8.790361e+07,1131.0,0.0,0.0,0.0,0.0,OK,NaN

In [39]:
## **6. S.com Cross Sell Order**

In [40]:
#### **Multi Order Cross Sell**

In [41]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_6_1_multi_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:20:57
▶ Output: aa_exports\25_ny_6_1_multi_order_cross_sell_20260304_112057.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [03:01<00:00, 12.96s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_6_1_multi_order_cross_sell_20260304_112057.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:03:01.577596
❌ 실패 site: 0
DONE: aa_exports\25_ny_6_1_multi_order_cross_sell_20260304_112057.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,5851.0,3.369854e+07,...,392.0,3.856493e+06,33.0,3.147458e+05,125.0,8.155335e+05,33.0,3.147458e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,10786.0,8.401757e+09,...,82.0,1.336280e+08,206.0,1.051318e+09,82.0,1.051916e+08,18.0,1.272995e+08,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0,NaN,1313.0,1.307119e+06,...,31.0,2.834949e+04,27.0,6.460443e+04,0.0,0.000000e+00,0.0,0.000000e+00,OK,NaN
3,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,0,NaN,1131.0,5.323619e+07,...,0.0,0.000000e+00,2.0,1.245970e+05,0.0,0.000000e+00,0.0,0.000000e+00,OK,NaN
4,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-01-19,2025-02-26,0,NaN,3748.0,1.746365e+07,...,6.0,2.555655e+04,4.0,2.904855e+04,4.0,1.573217e+04,0.0,0.000000e+00,OK,NaN

In [42]:
#### **Total Order Cross Sell**

In [43]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_6_2_total_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:23:59
▶ Output: aa_exports\25_ny_6_2_total_order_cross_sell_20260304_112359.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [02:34<00:00, 11.01s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_6_2_total_order_cross_sell_20260304_112359.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:02:34.212803
❌ 실패 site: 0
DONE: aa_exports\25_ny_6_2_total_order_cross_sell_20260304_112359.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,0,NaN,11983.0,3.600886e+07,...,392.0,3.856493e+06,33.0,3.147458e+05,125.0,8.155335e+05,33.0,3.147458e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,0,NaN,127076.0,5.848669e+10,...,82.0,1.336280e+08,206.0,1.051318e+09,82.0,1.051916e+08,18.0,1.272995e+08,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,0,NaN,5316.0,3.223818e+06,...,31.0,2.834949e+04,27.0,6.460443e+04,0.0,0.000000e+00,0.0,0.000000e+00,OK,NaN
3,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,0,NaN,1926.0,8.790361e+07,...,0.0,0.000000e+00,2.0,1.245970e+05,0.0,0.000000e+00,0.0,0.000000e+00,OK,NaN
4,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-01-19,2025-02-26,0,NaN,7375.0,2.843834e+07,...,6.0,2.555655e+04,4.0,2.904855e+04,4.0,1.573217e+04,0.0,0.000000e+00,OK,NaN

In [44]:
#### **CMP Order Cross Sell**

In [45]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_6_3_cmp_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:26:34
▶ Output: aa_exports\25_ny_6_3_cmp_order_cross_sell_20260304_112634.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [02:30<00:00, 10.73s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_6_3_cmp_order_cross_sell_20260304_112634.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:02:30.320776
❌ 실패 site: 0
DONE: aa_exports\25_ny_6_3_cmp_order_cross_sell_20260304_112634.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1250001,2025 (Jan 1-Dec 31),737.0,4.255650e+06,...,89.0,863371.52,15.0,1.408701e+05,20.0,172683.25,15.0,140870.1,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2025-02-18,2025-03-17,1250001,2025 (Jan 1-Dec 31),3619.0,3.351129e+09,...,7.0,10393000.00,48.0,2.228598e+08,6.0,7928382.00,4.0,23194782.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2025-01-29,2025-02-11,1250001,2025 (Jan 1-Dec 31),0.0,0.000000e+00,...,0.0,0.00,0.0,0.000000e+00,0.0,0.00,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-02-17,2025-03-16,1250001,2025 (Jan 1-Dec 31),82.0,4.730620e+04,...,0.0,0.00,2.0,2.082120e+03,0.0,0.00,0.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-01-19,2025-02-10,1250001,2025 (Jan 1-Dec 31),0.0,0.000000e+00,...,0.0,0.00,0.0,0.000000e+00,0.0,0.00,0.0,0.0,OK,NaN

In [46]:
## **7. Order Conversion/Traffic by Channel**

In [47]:
#### **Order BY Channel CMP**

In [48]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2025_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_7_1_order_by_channel_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:29:05
▶ Output: aa_exports\25_ny_7_1_order_by_channel_cmp_20260304_112905.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3']

AA Export (sites): 100%|██████████| 14/14 [00:09<00:00,  1.47site/s, ok=1, rows=19, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_7_1_order_by_channel_cmp_20260304_112905.csv
총 데이터 row (FAILED row 제외, header 제외): 167
⏱ Elapsed: 0:00:09.660966
❌ 실패 site: 0
DONE: aa_exports\25_ny_7_1_order_by_channel_cmp_20260304_112905.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,5,Direct,28652.0,467.0,2459212.21,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,14,Push,17779.0,41.0,210750.97,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,15,Mobile Application,9329.0,16.0,23609.22,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1,Paid Search,2363.0,22.0,133418.46,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,11,Social Media Campaigns,686.0,10.0,42579.32,OK,NaN

In [49]:
## **Best Selling Product**

In [50]:
#### **Bestselling**

In [51]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "25_ny_bestselling.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="25_bl_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:29:15
▶ Output: aa_exports\25_ny_bestselling_20260304_112915.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 14/14 [00:14<00:00,  1.02s/site, ok=1, rows=772, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\25_ny_bestselling_20260304_112915.csv
총 데이터 row (FAILED row 제외, header 제외): 5,408
⏱ Elapsed: 0:00:14.557988
❌ 실패 site: 0
DONE: aa_exports\25_ny_bestselling_20260304_112915.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,2983901684,NaN,2541.0,0.00,311.0,0.00,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,3309145458,HUAFEI,1970.0,0.00,183.0,0.00,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1107069323,3WYGJFWQYZP,1168.0,0.00,120.0,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,1802553923,TRADE-IN,1036.0,0.00,204.0,0.00,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-02-24,2025-03-25,445878911,EF-US921,954.0,15441.03,13.0,119.99,OK,NaN

# **CSV to Excel Raw Sheet Format**

In [ ]:
  # ─────────────────────────────────────────────────────────────────
  # [셀 2] POST-PROCESSING: 매핑 + long 변환 + currency 환율 적용
  #        + channel: US 매핑 / dummy 0 / PAID_NONPAID
  #        + metric_col 키 분리 (J1~J7, J11)
  #        + 개별 _stacked_separate.csv + 전체 union 저장
  # ─────────────────────────────────────────────────────────────────
  import re
  from pathlib import Path
  from datetime import datetime
  import pandas as pd

  MAPPING_CSV  = Path.cwd() / "tb_column_name_mapping.csv"
  CURRENCY_CSV = Path.cwd() / "currency.csv"
  EXPORTS_DIR  = Path.cwd() / "aa_exports"

  # ── currency 로드 ─────────────────────────────────────────────────
  cur_df = pd.read_csv(CURRENCY_CSV)
  col_latest = cur_df.columns[2]
  col_prior  = cur_df.columns[3]
  year_latest = str(pd.to_datetime(col_latest).year)
  year_prior  = str(pd.to_datetime(col_prior).year)
  print(f"▶ 환율 컬럼: {col_latest}({year_latest}) / {col_prior}({year_prior})")

  cur_map = {
      str(r["site_code"]).strip().lower(): {
          year_latest: r[col_latest],
          year_prior:  r[col_prior],
      }
      for _, r in cur_df.iterrows()
  }

  # ── channel 매핑 정의 ─────────────────────────────────────────────
  us_mapping = {
      "US Channel":"Global Channel Mapping ",
      "Affiliate":"Affiliate Marketing",
      "Display":"Display",
      "Display Retargeting":"Display",
      "Other External Campaign":"Paid Others",
      "Other Paid Ecomm":"Paid Others",
      "Paid Search":"Paid Search",
      "Paid Search - eComm":"Paid Search",
      "PLA":"Pmax",
      "Social (Paid)":"Social Media Campaigns",
      "Vanity":"Paid Others",
      "Direct":"Direct",
      "Email - CRM":"Email",
      "Email - eComm":"Email",
      "Email - Upsell it":"Email",
      "Email (Retired)":"Email",
      "EPP":"EPP - US",
      "Natural Search":"Natural Search",
      "Other":"Other",
      "None":"Other",
      "Push Notifications":"Push",
      "Referring Domains":"Other",
      "Session Refresh":"Session Refresh",
      "Social (Free and Owned)":"Owned Social",
      "Social (Retired)":"Social Network Referrals",
      "Other External CampaignSegments":"Mobile Application",
      "Other External CampaignUS_Smartthings":"Mobile Application - Smartthings",
      "Other External CampaignUS_Samsung Members":"Mobile Application - Samsung Members",
      "SMS":"SMS",
      "Gen AI Search":"Gen AI (Organic)"
  }

  global_paid_mapping = {
      "Paid Search":"Paid",
      "Social Media Campaigns":"Paid",
      "Affiliate Marketing":"Paid",
      "Display":"Paid",
      "Other Campaigns":"Paid",
      "QR code (Paid)":"Paid",
      "Pmax":"Paid",
      "Demand Gen":"Paid",
      "Paid Others":"Paid",
      "Video":"Paid",
      "Gen AI (Paid)":"Paid",
      "Session Refresh":"Non-Paid",
      "Email":"Non-Paid",
      "Direct":"Non-Paid",
      "Natural Search":"Non-Paid",
      "Mobile Application":"Non-Paid",
      "Push":"Non-Paid",
      "Social Network Referrals":"Non-Paid",
      "Other":"Non-Paid",
      "SMS":"Non-Paid",
      "None":"Non-Paid",
      "Owned Social":"Non-Paid",
      "QR code (Owned)":"Non-Paid",
      "Samsung Web":"Non-Paid",
      "Gen AI (Organic)":"Non-Paid",
      "Owned Others":"Non-Paid"
  }

  # ── 최종 컬럼 정리 ────────────────────────────────────────────────
  def finalize_df(df: pd.DataFrame) -> pd.DataFrame:
      df = df.copy()
      if "PAID_NONPAID" not in df.columns:
          df["PAID_NONPAID"] = "-"
      df["TIER"]  = ""
      df["공란1"] = ""
      df["공란2"] = ""
      df["공란3"] = ""
      df["공란4"] = ""
      df = df.rename(columns={
          "Subsidiary":         "SUBS",
          "Country":            "COUNTRY",
          "Site_Code":          "SITE CODE",
          "J11":                "REPORT NO.",
          "J3":                 "DIVISION",
          "J4":                 "DATE",
          "J5":                 "DEVICE TYPE",
          "J6":                 "TYPE",
          "J7":                 "LOGIN/NON",
          "PAID_NONPAID":       "PAID/NONPAID",
          "value":              "ITEM",
          "metric_value_adj":   "VALUE",
          "metric_col":         "KEY",
          "metric_value_origin":"value_origin",
          "Start_Date":         "start_date",
          "End_Date":           "end_date",
      })
      final_cols = [
          "TIER", "SUBS", "COUNTRY", "SITE CODE",
          "REPORT NO.", "DIVISION", "DATE", "DEVICE TYPE", "TYPE", "LOGIN/NON",
          "PAID/NONPAID", "ITEM", "VALUE", "KEY",
          "공란1", "공란2", "공란3", "공란4",
          "value_origin", "start_date", "end_date"
      ]
      return df[[c for c in final_cols if c in df.columns]]


  # ── 캠페인 키 분리 유틸 (260109v3.py 참조) ───────────────────────
  report_no_mapping = {
      "1_1": "1_1~2. S.com Traffic by Division",
      "2_1": "2_1~4. Basic Traffic",
      "3_1": "3_1. Traffic by Channel (Internal)",
      "3_2": "3_2. Traffic by Channel (External)",
      "3_3": "3_3. Home KV & GNB to Campaign Page",
      "4_1": "4_1. Order Conversion with Login/Non_Login",
      "4_2": "4_2. Order Conversion with Login/Non_Login (Visit)",
      "5_1": "5_1. S.com Order Conversion",
      "6_1": "6_1. S.com Cross Sell Order (Multi Purchase)",
      "6_2": "6_2. S.com Cross Sell Order (Total)",
      "6_3": "6_3. Campaign Page Cross Sell Order",
      "7_1": "7_1~2. Order Conversion/Traffic by Channel"
  }

  def _split_by_number_pattern(parts):
      # metric_col이 X_Y_... 형태로 시작할 때 (예: 1_1_da_2025_scom_...)
      if len(parts) >= 2 and re.fullmatch(r"\d{1,2}", parts[0]) and re.fullmatch(r"\d{1,2}", parts[1]):
          return "", f"{parts[0]}_{parts[1]}", parts[2:]
      for i in (2, 3):
          if i + 1 < len(parts) and parts[i].isdigit() and parts[i+1].isdigit():
              return '_'.join(parts[:i]), f"{parts[i]}_{parts[i+1]}", parts[i+2:]
      return parts[0], f"{parts[1]}_{parts[2]}", parts[3:]

  def _find_report_key(values):
      for v in values:
          if isinstance(v, str) and re.fullmatch(r"\d+_\d+", v):
              return v
      return ''

  def split_metric_col(val: str) -> dict:
      """metric_col → J1~J7, J11"""
      parts = str(val).split('_')
      if len(parts) < 3:
          j1_to_j7 = (parts + [''] * 7)[:7]
          return {**{f"J{i+1}": j1_to_j7[i] for i in range(7)}, "J11": ""}

      first, second, remaining = _split_by_number_pattern(parts)
      processed = []
      i = 0
      while i < len(remaining):
          if remaining[i].isdigit() and remaining[i].startswith('202'):
              if i + 2 < len(remaining) and remaining[i+2].lower() == 'prior':
                  processed.append(f"{remaining[i]}_{remaining[i+1]}_{remaining[i+2]}")
                  i += 3
              elif i + 1 < len(remaining):
                  processed.append(f"{remaining[i]}_{remaining[i+1]}")
                  i += 2
              else:
                  processed.append(remaining[i])
                  i += 1
          else:
              processed.append(remaining[i])
              i += 1

      all_parts = [first, second] + processed
      j1_to_j7 = (all_parts + [''] * 7)[:7]
      report_key = _find_report_key(j1_to_j7)
      return {**{f"J{i+1}": j1_to_j7[i] for i in range(7)}, "J11": report_no_mapping.get(report_key, '')}

  def _apply_j_cols(df: pd.DataFrame) -> pd.DataFrame:
      j_df = pd.DataFrame(
          [split_metric_col(v) for v in df["metric_col"]],
          index=df.index
      )
      return pd.concat([df, j_df], axis=1)

  # ── 매핑 로드 ─────────────────────────────────────────────────────
  mapping_df = pd.read_csv(MAPPING_CSV)
  id_vars = ["Subsidiary", "Country", "Site_Code", "RSID",
             "Start_Date", "End_Date", "itemId", "value"]

  ok_list, skip_list = [], []
  channel_frames = {}
  all_frames = []  # union용

  csv_files = [f for f in EXPORTS_DIR.glob("*.csv") if "_long" not in f.name and "_stacked" not in f.name]
  print(f"▶ 처리 대상: {len(csv_files)}개 파일\n")

  for src_path in sorted(csv_files):
      stem   = src_path.stem
      tb_key = re.sub(r"_\d{8}_\d{6}$", "", stem)

      tb_mapping = mapping_df[mapping_df["tb"] == tb_key]
      if tb_mapping.empty:
          tb_mapping = mapping_df[mapping_df["tb"] == re.sub(r"_prior$", "", tb_key)]

      if tb_mapping.empty:
          skip_list.append(tb_key)
          continue

      rename_dict = dict(zip(tb_mapping["value_n"], tb_mapping["column"]))

      df = pd.read_csv(src_path, encoding="utf-8-sig")
      df = df.rename(columns=rename_dict)
      value_vars = [c for c in rename_dict.values() if c in df.columns]

      for v in value_vars:
          df[v] = pd.to_numeric(
              df[v].astype(str).str.strip().str.replace("'", "", regex=False),
              errors="coerce"
          )

      df_long = df.melt(
          id_vars=[c for c in id_vars if c in df.columns],
          value_vars=value_vars,
          var_name="metric_col",
          value_name="metric_value_origin"
      )

      # ── currency 환율 적용 ────────────────────────────────────────
      df_long["_year"] = pd.to_datetime(df_long["Start_Date"]).dt.year.astype(str)
      df_long["_site"] = df_long["Site_Code"].str.strip().str.lower()

      def calc_adj(row):
          if "revenue" not in str(row["metric_col"]).lower():
              return row["metric_value_origin"]
          rates = cur_map.get(row["_site"])
          if not rates:
              return row["metric_value_origin"]
          rate = rates.get(row["_year"])
          if rate is None:
              return row["metric_value_origin"]
          try:
              return float(row["metric_value_origin"]) * float(rate)
          except (TypeError, ValueError):
              return row["metric_value_origin"]

      df_long["metric_value_adj"] = df_long.apply(calc_adj, axis=1)
      df_long = df_long.drop(columns=["_year", "_site"])

      df_long["metric_value_origin"] = pd.to_numeric(
          df_long["metric_value_origin"].astype(str).str.replace("'", "", regex=False),
          errors="coerce"
      )
      df_long["metric_value_adj"] = pd.to_numeric(
          df_long["metric_value_adj"].astype(str).str.replace("'", "", regex=False),
          errors="coerce"
      )

      # ── metric_col 키 분리 ────────────────────────────────────────
      df_long = _apply_j_cols(df_long)

      # ── channel 파일이면 수집, 아니면 바로 저장 ───────────────────
      is_channel = "channel" in tb_key.lower()
      if is_channel:
          channel_frames[tb_key] = df_long
      else:
          out_path = EXPORTS_DIR / f"{tb_key}_stacked_separate.csv"
          df_long.to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          ok_list.append(tb_key)
          all_frames.append(df_long)

  # ── channel 후처리 (루프 종료 후) ────────────────────────────────
  if channel_frames:
      print(f"\n▶ channel 후처리: {list(channel_frames.keys())}")

      for tb_key, df_long in channel_frames.items():

          # 1. US value 치환
          is_us = df_long["Site_Code"].str.strip().str.lower() == "us"
          df_long.loc[is_us, "value"] = (
              df_long.loc[is_us, "value"].map(us_mapping).fillna(df_long.loc[is_us, "value"])
          )

          # 2. dummy 0 삽입
          all_sites   = df_long["Site_Code"].unique()
          all_values  = df_long["value"].unique()
          metric_cols = df_long["metric_col"].unique()

          meta_cols = [c for c in ["Subsidiary", "Country", "RSID"] if c in df_long.columns]
          meta_df = (
              df_long.groupby("Site_Code")[meta_cols]
              .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
              .reset_index()
          )
          date_cols = [c for c in ["Start_Date", "End_Date", "itemId"] if c in df_long.columns]
          date_meta = (
              df_long.groupby("Site_Code")[date_cols]
              .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
              .reset_index()
          )

          cross = pd.MultiIndex.from_product(
              [all_sites, all_values, metric_cols],
              names=["Site_Code", "value", "metric_col"]
          ).to_frame(index=False)

          existing = df_long[["Site_Code", "value", "metric_col"]].drop_duplicates()
          existing["_exists"] = True

          merged = cross.merge(existing, on=["Site_Code", "value", "metric_col"], how="left")
          dummy_rows = merged[merged["_exists"].isna()].drop(columns=["_exists"])

          if not dummy_rows.empty:
              dummy_rows = dummy_rows.merge(meta_df, on="Site_Code", how="left")
              dummy_rows = dummy_rows.merge(date_meta, on="Site_Code", how="left")
              dummy_rows["metric_value_origin"] = 0.0
              dummy_rows["metric_value_adj"]    = 0.0
              dummy_rows = _apply_j_cols(dummy_rows)
              df_long = pd.concat([df_long, dummy_rows], ignore_index=True)
              print(f"  {tb_key} → dummy {len(dummy_rows)}행 삽입")

          # 3. PAID_NONPAID 컬럼 추가 (value 왼쪽)
          df_long["PAID_NONPAID"] = df_long["value"].map(global_paid_mapping)
          val_idx = df_long.columns.get_loc("value")
          cols = list(df_long.columns)
          cols.remove("PAID_NONPAID")
          cols.insert(val_idx, "PAID_NONPAID")
          df_long = df_long[cols]

          out_path = EXPORTS_DIR / f"{tb_key}_stacked_separate.csv"
        #   df_long.to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          finalize_df(df_long).to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          ok_list.append(tb_key)
          all_frames.append(df_long)

  # ── union 생성 ────────────────────────────────────────────────────
  if all_frames:
      ts = datetime.now().strftime("%Y%m%d_%H%M%S")
      union_path = EXPORTS_DIR / f"union_{ts}.csv"
      union_df = pd.concat(all_frames, ignore_index=True)
      if "PAID_NONPAID" in union_df.columns:
          union_df["PAID_NONPAID"] = union_df["PAID_NONPAID"].fillna("-")
    #   union_df.to_csv(union_path, index=False, encoding="utf-8-sig", float_format="%.6f")
      finalize_df(union_df).to_csv(union_path, index=False, encoding="utf-8-sig", float_format="%.6f")
      print(f"\n▶ union 저장: {union_path} ({len(union_df):,}행)")

  # ── 결과 요약 ─────────────────────────────────────────────────────
  print(f"\n✅ 완료: {len(ok_list)}개")
  for t in ok_list: print(f"  - {t}")
  print(f"\n⚠️  매핑 없어서 skip: {len(skip_list)}개")
  for t in skip_list: print(f"  - {t}")

▶ 환율 컬럼: 2026-02-28(2026) / 2025-02-28(2025)
▶ 처리 대상: 62개 파일


▶ channel 후처리: ['25_ny_3_1_channel_internal', '25_ny_3_2_channel_traffic_external', '25_ny_7_1_order_by_channel_cmp', '26_ny_3_1_channel_internal', '26_ny_3_2_channel_external_cmp', '26_ny_3_2_channel_external_scom', '26_ny_3_2_channel_external_scom_prior', '26_ny_7_1_order_by_channel_cmp', '26_ny_7_1_order_by_channel_scom', '26_ny_7_1_order_by_channel_scom_prior']
  25_ny_3_1_channel_internal → dummy 210행 삽입
  25_ny_3_2_channel_traffic_external → dummy 132행 삽입
  25_ny_7_1_order_by_channel_cmp → dummy 129행 삽입
  26_ny_3_2_channel_external_cmp → dummy 642행 삽입
  26_ny_3_2_channel_external_scom → dummy 120행 삽입
  26_ny_3_2_channel_external_scom_prior → dummy 116행 삽입
  26_ny_7_1_order_by_channel_cmp → dummy 1200행 삽입
  26_ny_7_1_order_by_channel_scom → dummy 180행 삽입
  26_ny_7_1_order_by_channel_scom_prior → dummy 174행 삽입

▶ union 저장: c:\Users\CNXK\OneDrive - Concentrix Corporation\pjh\2.data\99.PY,SQL-250429\00.py_notebook\260224_AA_Exporter(jiwoo)\aa_exports\union_20260304_112951.csv (219,156행)

✅ 완료: 59개
  - 25_ny_1_1_scom_da_traffic_app
  - 25_ny_1_1_scom_da_traffic_web
  - 25_ny_1_1_scom_mx_traffic_app
  - 25_ny_1_1_scom_mx_traffic_web
  - 25_ny_1_1_scom_vd_traffic_app
  - 25_ny_1_1_scom_vd_traffic_web
  - 25_ny_2_1_basic_traffic_cmp
  - 25_ny_2_1_basic_traffic_scom
  - 25_ny_2_1_basic_traffic_time
  - 25_ny_3_3_homepage_kv_gnb_to_cmp
  - 25_ny_4_1_order_cvr_loginout
  - 25_ny_4_1_scom_order_cvr_loginout
  - 25_ny_5_1_scom_campaign_order_cvr
  - 25_ny_6_1_multi_order_cross_sell
  - 25_ny_6_2_total_order_cross_sell
  - 25_ny_6_3_cmp_order_cross_sell
  - 25_ny_bestselling
  - 26_ny_1_1_scom_da_traffic_app
  - 26_ny_1_1_scom_da_traffic_app_prior
  - 26_ny_1_1_scom_da_traffic_web
  - 26_ny_1_1_scom_da_traffic_web_prior
  - 26_ny_1_1_scom_mx_traffic_app
  - 26_ny_1_1_scom_mx_traffic_app_prior
  - 26_ny_1_1_scom_mx_traffic_web
  - 26_ny_1_1_scom_mx_traffic_web_prior
  - 26_ny_1_1_scom_vd_traffic_app
  - 26_ny_1_1_scom_vd_traffic_app_prior
  - 26_ny_1_1_scom_vd_traffic_web
  - 26_ny_1_1_scom_vd_traffic_web_prior
  - 26_ny_2_1_basic_traffic_cmp
  - 26_ny_2_1_basic_traffic_scom
  - 26_ny_2_1_basic_traffic_scom_prior
  - 26_ny_2_1_basic_traffic_time_cmp
  - 26_ny_2_1_basic_traffic_time_scom
  - 26_ny_2_1_basic_traffic_time_scom_prior
  - 26_ny_3_3_homepage_kv_gnb_to_cmp
  - 26_ny_4_1_order_cvr_loginout
  - 26_ny_4_2_order_cvr_visit_visitor
  - 26_ny_5_1_campaign_order_cvr
  - 26_ny_5_1_scom_order_cvr
  - 26_ny_6_1_multi_order_cross_sell
  - 26_ny_6_1_multi_order_cross_sell_prior
  - 26_ny_6_2_total_order_cross_sell
  - 26_ny_6_2_total_order_cross_sell_prior
  - 26_ny_6_3_cmp_order_cross_sell
  - 26_ny_bestselling
  - 26_ny_nextpage
  - 26_ny_raw_multi_purchase_v41
  - 26_ny_raw_multi_purchase_v41_prior
  - 25_ny_3_1_channel_internal
  - 25_ny_3_2_channel_traffic_external
  - 25_ny_7_1_order_by_channel_cmp
  - 26_ny_3_1_channel_internal
  - 26_ny_3_2_channel_external_cmp
  - 26_ny_3_2_channel_external_scom
  - 26_ny_3_2_channel_external_scom_prior
  - 26_ny_7_1_order_by_channel_cmp
  - 26_ny_7_1_order_by_channel_scom
  - 26_ny_7_1_order_by_channel_scom_prior

⚠️  매핑 없어서 skip: 3개
  - 25_ny_3_2_channel_external_scom
  - union
  - union