In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic APP**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_da_traffic_app_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-04 10:28:50
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260304_102850.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [09:24<00:00, 40.33s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260304_102850.csv
총 데이터 row (FAILED row 제외, header 제외): 12
⏱ Elapsed: 0:09:24.859796
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260304_102850.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,6640.0,6206.0,...,0.0,0.0,5.0,5.0,0.0,1.757322e+04,1.757322e+04,0.000000e+00,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,248678.0,230462.0,...,85433.0,1801.0,5288.0,4207.0,1081.0,5.983223e+09,4.533876e+09,1.449348e+09,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0,NaN,8184.0,5913.0,...,7.0,30.0,169.0,115.0,38.0,1.366592e+05,7.997478e+04,3.960476e+04,OK,NaN
3,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-12-11,2026-01-18,0,NaN,4997.0,3019.0,...,17.0,31.0,131.0,51.0,75.0,4.438895e+05,1.681937e+05,2.604393e+05,OK,NaN
4,SESAR,Saudi Arabia (en),SA_EN,sssamsung4saen,2025-12-11,2026-01-18,0,NaN,1997.0,1388.0,...,5.0,10.0,39.0,25.0,12.0,1.450462e+05,1.162563e+05,2.549204e+04,OK,NaN

In [5]:
#### **Scom DA Traffic WEB**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_da_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:38:16
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260304_103816.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [01:40<00:00,  7.20s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260304_103816.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:40.864514
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260304_103816.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,31081.0,73130.0,...,24924.0,28944.0,12214.0,27511.0,5.0,5.0,5.470790e+04,3.362691e+04,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,505249.0,1153449.0,...,370329.0,985623.0,233998.0,569390.0,4811.0,9164.0,5.122399e+09,4.012197e+09,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-15,2026-01-28,0,NaN,679.0,1833.0,...,494.0,1339.0,230.0,538.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0,NaN,35690.0,81597.0,...,23568.0,57928.0,4385.0,19179.0,198.0,171.0,1.484835e+05,1.025749e+05,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-12-27,2026-01-18,0,NaN,11943.0,32181.0,...,9233.0,26475.0,3848.0,11346.0,98.0,124.0,2.311800e+06,2.645563e+06,OK,NaN

In [7]:
#### **Scom MX Traffic APP**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_mx_traffic_app_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:39:57
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260304_103957.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [05:18<00:00, 22.72s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260304_103957.csv
총 데이터 row (FAILED row 제외, header 제외): 11
⏱ Elapsed: 0:05:18.202396
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260304_103957.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0.0,NaN,228205.0,209298.0,...,11.0,12.0,1802.0,1645.0,154.0,5.824285e+06,4.732494e+06,1.085026e+06,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0.0,NaN,620313.0,597074.0,...,89233.0,2526.0,13083.0,12045.0,1038.0,1.303434e+10,1.169493e+10,1.339406e+09,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0.0,NaN,51199.0,42254.0,...,8.0,2.0,915.0,766.0,58.0,4.409710e+05,3.545020e+05,4.502686e+04,OK,NaN
3,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-12-11,2026-01-18,0.0,NaN,75379.0,57698.0,...,142.0,4.0,6933.0,5883.0,572.0,7.255677e+06,5.541588e+06,1.281803e+06,OK,NaN
4,SESAR,Saudi Arabia (en),SA_EN,sssamsung4saen,2025-12-11,2026-01-18,0.0,NaN,43975.0,35172.0,...,20.0,3.0,1315.0,1044.0,148.0,2.250104e+06,1.700693e+06,3.490384e+05,OK,NaN

In [9]:
#### **Scom MX Traffic WEB**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_mx_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:45:16
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260304_104516.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [03:05<00:00, 13.26s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260304_104516.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:03:05.789369
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260304_104516.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0.0,NaN,244843.0,1240479.0,...,157360.0,1100578.0,72534.0,833119.0,603.0,374.0,6.679554e+06,1.997633e+06,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0.0,NaN,836860.0,2176655.0,...,590226.0,1906856.0,210781.0,772711.0,8498.0,8512.0,1.152842e+10,6.096868e+09,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-15,2026-01-28,0.0,NaN,6523.0,167671.0,...,5581.0,160836.0,1948.0,98206.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0.0,NaN,91015.0,355114.0,...,60198.0,292172.0,14134.0,141721.0,467.0,683.0,3.009825e+05,4.305032e+05,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-12-27,2026-01-18,0.0,NaN,25803.0,111314.0,...,19596.0,87339.0,7168.0,32184.0,195.0,269.0,4.026696e+06,6.305856e+06,OK,NaN

In [11]:
#### **Scom VD Traffic APP**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_vd_traffic_app_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:48:22
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260304_104822.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [04:45<00:00, 20.39s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260304_104822.csv
총 데이터 row (FAILED row 제외, header 제외): 11
⏱ Elapsed: 0:04:45.617123
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260304_104822.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0.0,NaN,17138.0,14859.0,...,0.0,3.0,111.0,74.0,37.0,5.493859e+05,3.448743e+05,2.045117e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0.0,NaN,123099.0,115004.0,...,43180.0,954.0,1695.0,1391.0,304.0,2.940910e+09,2.436801e+09,5.041085e+08,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0.0,NaN,11641.0,8145.0,...,11.0,59.0,249.0,162.0,62.0,2.177745e+05,1.282208e+05,6.702281e+04,OK,NaN
3,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-12-11,2026-01-18,0.0,NaN,9137.0,5421.0,...,73.0,80.0,153.0,58.0,89.0,4.667175e+05,1.499329e+05,2.983865e+05,OK,NaN
4,SESAR,Saudi Arabia (en),SA_EN,sssamsung4saen,2025-12-11,2026-01-18,0.0,NaN,3923.0,2612.0,...,11.0,15.0,103.0,64.0,32.0,3.039390e+05,1.986809e+05,9.200265e+04,OK,NaN

In [13]:
#### **Scom VD Traffic WEB**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_vd_traffic_web_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:53:08
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260304_105308.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [01:37<00:00,  7.00s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260304_105308.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:38.084282
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260304_105308.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,88651.0,82889.0,...,60979.0,13237.0,29684.0,6551.0,39.0,19.0,1.874974e+05,1.369515e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,252360.0,340710.0,...,169659.0,260974.0,100804.0,122380.0,1840.0,2052.0,3.026781e+09,1.648715e+09,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-15,2026-01-28,0,NaN,1022.0,2937.0,...,730.0,2135.0,295.0,847.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0,NaN,39443.0,87611.0,...,25325.0,69122.0,5458.0,26778.0,208.0,183.0,2.001038e+05,1.342497e+05,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-12-27,2026-01-18,0,NaN,18983.0,97282.0,...,15197.0,90997.0,7175.0,61378.0,85.0,111.0,2.663693e+06,3.627956e+06,OK,NaN

In [15]:
## **2_1~4. Basic Traffic**

In [16]:
#### **Basic Traffic Scom**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:54:47
▶ Output: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260304_105447.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites): 100%|██████████| 14/14 [03:55<00:00, 16.81s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260304_105447.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:03:55.513244
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260304_105447.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,891083.0,3614111.0,...,8324729.0,243116.0,788954.0,747883.0,41044.0,241386.0,224208.0,17155.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,2225713.0,7290586.0,...,18959332.0,463911.0,8165195.0,8078081.0,87112.0,6117814.0,6086674.0,31140.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-15,2026-01-28,0,NaN,12580.0,237701.0,...,2.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0,NaN,213036.0,790861.0,...,3064499.0,148090.0,264797.0,216088.0,23088.0,83953.0,62538.0,14436.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2025-12-27,2026-01-18,0,NaN,81079.0,604036.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [18]:
#### **Basic Traffic Time Scom**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_time_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:58:43
▶ Output: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260304_105843.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [02:10<00:00,  9.35s/site, ok=1, rows=2, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260304_105843.csv
총 데이터 row (FAILED row 제외, header 제외): 24
⏱ Elapsed: 0:02:11.092395
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260304_105843.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,1250001,2025 (Jan 1-Dec 31),203.668942,279.608378,150.689386,213.224511,204.343388,348.020167,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,1260001,2026 (Jan 1-Dec 31),179.383934,295.537482,133.782136,172.809986,164.920096,338.753815,OK,NaN
2,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,1260001,2026 (Jan 1-Dec 31),230.072080,413.136550,249.418230,177.238258,174.351408,405.034542,OK,NaN
3,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-15,2026-01-28,1260001,2026 (Jan 1-Dec 31),161.520903,199.604196,157.515974,19.000000,19.000000,0.000000,OK,NaN
4,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,1250001,2025 (Jan 1-Dec 31),294.395573,413.958690,272.528368,267.241119,257.243258,357.319987,OK,NaN

In [20]:
## **3. Traffic by Channel**

In [21]:
#### **Channel External Scom**

In [22]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_2_channel_external_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:00:55
▶ Output: aa_exports\26_ny_3_2_channel_external_scom_prior_20260304_110055.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 14/14 [00:17<00:00,  1.22s/site, ok=1, rows=24, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_2_channel_external_scom_prior_20260304_110055.csv
총 데이터 row (FAILED row 제외, header 제외): 307
⏱ Elapsed: 0:00:17.189844
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_2_channel_external_scom_prior_20260304_110055.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,16,Affiliate Marketing,1302359.0,1157193.0,15.0,4.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,5,Direct,1219471.0,944517.0,720073.0,227725.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,20,Display,416523.0,368778.0,12.0,7.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,15,Mobile Application,407616.0,259064.0,14791.0,2793.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,1,Paid Search,278543.0,130526.0,5072.0,571.0,OK,NaN

In [23]:
## **6. S.com Cross Sell Order**

In [24]:
#### **Multi Order Cross Sell**

In [25]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_1_multi_order_cross_sell_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:01:12
▶ Output: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260304_110112.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [03:38<00:00, 15.61s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260304_110112.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:03:41.182980
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260304_110112.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,1202.0,9.543053e+06,...,1.0,9.177760e+03,0.0,0.000000e+00,1.0,9135.20,0.0,0.00,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,7977.0,1.053722e+10,...,62.0,1.888882e+08,191.0,9.919776e+08,76.0,88103513.00,22.0,95561548.00,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0,NaN,744.0,7.549488e+05,...,7.0,8.139460e+03,39.0,7.189629e+04,4.0,1088.66,2.0,5544.60,OK,NaN
3,SEUC,Ukraine,UA,sssamsung4ua,2025-12-27,2026-01-18,0,NaN,713.0,1.902690e+07,...,0.0,0.000000e+00,3.0,2.068037e+05,2.0,40650.75,0.0,0.00,OK,NaN
4,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-12-11,2026-01-18,0,NaN,513.0,1.427039e+06,...,1.0,5.593250e+03,5.0,2.759807e+04,2.0,5545.35,1.0,6591.97,OK,NaN

In [26]:
#### **Total Order Cross Sell**

In [27]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_2_total_order_cross_sell_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:04:55
▶ Output: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260304_110455.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [02:45<00:00, 11.84s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260304_110455.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:02:46.905895
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260304_110455.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,0,NaN,3338.0,1.594378e+07,...,1.0,9.177760e+03,0.0,0.000000e+00,1.0,9135.20,0.0,0.00,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-01-04,2026-01-31,0,NaN,76771.0,5.318667e+10,...,62.0,1.888882e+08,191.0,9.919776e+08,76.0,88103513.00,22.0,95561548.00,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2025-12-24,2026-01-20,0,NaN,3289.0,2.032942e+06,...,7.0,8.139460e+03,39.0,7.189629e+04,4.0,1088.66,2.0,5544.60,OK,NaN
3,SEUC,Ukraine,UA,sssamsung4ua,2025-12-27,2026-01-18,0,NaN,883.0,2.135490e+07,...,0.0,0.000000e+00,3.0,2.068037e+05,2.0,40650.75,0.0,0.00,OK,NaN
4,SESAR,Saudi Arabia,SA,sssamsung4sa,2025-12-11,2026-01-18,0,NaN,8691.0,9.625522e+06,...,1.0,5.593250e+03,5.0,2.759807e+04,2.0,5545.35,1.0,6591.97,OK,NaN

In [28]:
## **7. Order Conversion/Traffic by Channel**

In [29]:
#### **Order BY Channel Scom**

In [30]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_7_1_order_by_channel_scom_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:07:43
▶ Output: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260304_110743.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [00:24<00:00,  1.76s/site, ok=1, rows=24, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260304_110743.csv
총 데이터 row (FAILED row 제외, header 제외): 307
⏱ Elapsed: 0:00:25.442661
❌ 실패 site: 0
DONE: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260304_110743.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,16,Affiliate Marketing,1302359.0,15.0,178.0,0.0,1510412.69,0.00,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,5,Direct,1219471.0,720075.0,309.0,1828.0,3297999.96,5947850.75,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,20,Display,416523.0,12.0,0.0,0.0,0.00,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,15,Mobile Application,407616.0,14791.0,72.0,47.0,159592.08,166388.21,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,1,Paid Search,278543.0,5072.0,300.0,8.0,2476932.53,9917.60,OK,NaN

In [31]:
## **Multi Purchase**

In [32]:
#### **RAW Multi Purchase V41**

In [33]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_raw_multi_purchase_v41_prior.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code_prior.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:08:10
▶ Output: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260304_110810.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [00:45<00:00,  3.24s/site, ok=1, rows=2027, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260304_110810.csv
총 데이터 row (FAILED row 제외, header 제외): 12,379
⏱ Elapsed: 0:00:48.903633
❌ 실패 site: 0
DONE: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260304_110810.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,190103735,SM-S9280ZTGCHC,0.0,0.0,0.0,119.0,59.0,303176.99,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,4002195195,"SM-S9380ZKDCHC,EP-T4511XBCMCN",74.0,28.0,212171.1,116.0,40.0,303456.82,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,3876492148,"SM-W9026DRDCHC,P-GT-NUXPS6HC-BUNDLE",6.0,3.0,50996.7,108.0,54.0,917936.16,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,3667055378,"SM-S9380ZSDCHC,EP-T4511XBCMCN",30.0,10.0,75789.3,69.0,20.0,151879.10,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2025-12-17,2026-01-15,2014262008,"SM-W9026AKDCHC,P-GT-NUXPS6HC-BUNDLE",0.0,0.0,0.0,68.0,34.0,577932.92,OK,NaN

# **CSV to Excel Raw Sheet Format**

In [ ]:
  # ─────────────────────────────────────────────────────────────────
  # [셀 2] POST-PROCESSING: 매핑 + long 변환 + currency 환율 적용
  #        + channel: US 매핑 / dummy 0 / PAID_NONPAID
  #        + metric_col 키 분리 (J1~J7, J11)
  #        + 개별 _stacked_separate.csv + 전체 union 저장
  # ─────────────────────────────────────────────────────────────────
  import re
  from pathlib import Path
  from datetime import datetime
  import pandas as pd

  MAPPING_CSV  = Path.cwd() / "tb_column_name_mapping.csv"
  CURRENCY_CSV = Path.cwd() / "currency.csv"
  EXPORTS_DIR  = Path.cwd() / "aa_exports"

  # ── currency 로드 ─────────────────────────────────────────────────
  cur_df = pd.read_csv(CURRENCY_CSV)
  col_latest = cur_df.columns[2]
  col_prior  = cur_df.columns[3]
  year_latest = str(pd.to_datetime(col_latest).year)
  year_prior  = str(pd.to_datetime(col_prior).year)
  print(f"▶ 환율 컬럼: {col_latest}({year_latest}) / {col_prior}({year_prior})")

  cur_map = {
      str(r["site_code"]).strip().lower(): {
          year_latest: r[col_latest],
          year_prior:  r[col_prior],
      }
      for _, r in cur_df.iterrows()
  }

  # ── channel 매핑 정의 ─────────────────────────────────────────────
  us_mapping = {
      "US Channel":"Global Channel Mapping ",
      "Affiliate":"Affiliate Marketing",
      "Display":"Display",
      "Display Retargeting":"Display",
      "Other External Campaign":"Paid Others",
      "Other Paid Ecomm":"Paid Others",
      "Paid Search":"Paid Search",
      "Paid Search - eComm":"Paid Search",
      "PLA":"Pmax",
      "Social (Paid)":"Social Media Campaigns",
      "Vanity":"Paid Others",
      "Direct":"Direct",
      "Email - CRM":"Email",
      "Email - eComm":"Email",
      "Email - Upsell it":"Email",
      "Email (Retired)":"Email",
      "EPP":"EPP - US",
      "Natural Search":"Natural Search",
      "Other":"Other",
      "None":"Other",
      "Push Notifications":"Push",
      "Referring Domains":"Other",
      "Session Refresh":"Session Refresh",
      "Social (Free and Owned)":"Owned Social",
      "Social (Retired)":"Social Network Referrals",
      "Other External CampaignSegments":"Mobile Application",
      "Other External CampaignUS_Smartthings":"Mobile Application - Smartthings",
      "Other External CampaignUS_Samsung Members":"Mobile Application - Samsung Members",
      "SMS":"SMS",
      "Gen AI Search":"Gen AI (Organic)"
  }

  global_paid_mapping = {
      "Paid Search":"Paid",
      "Social Media Campaigns":"Paid",
      "Affiliate Marketing":"Paid",
      "Display":"Paid",
      "Other Campaigns":"Paid",
      "QR code (Paid)":"Paid",
      "Pmax":"Paid",
      "Demand Gen":"Paid",
      "Paid Others":"Paid",
      "Video":"Paid",
      "Gen AI (Paid)":"Paid",
      "Session Refresh":"Non-Paid",
      "Email":"Non-Paid",
      "Direct":"Non-Paid",
      "Natural Search":"Non-Paid",
      "Mobile Application":"Non-Paid",
      "Push":"Non-Paid",
      "Social Network Referrals":"Non-Paid",
      "Other":"Non-Paid",
      "SMS":"Non-Paid",
      "None":"Non-Paid",
      "Owned Social":"Non-Paid",
      "QR code (Owned)":"Non-Paid",
      "Samsung Web":"Non-Paid",
      "Gen AI (Organic)":"Non-Paid",
      "Owned Others":"Non-Paid"
  }

  # ── 최종 컬럼 정리 ────────────────────────────────────────────────
  def finalize_df(df: pd.DataFrame) -> pd.DataFrame:
      df = df.copy()
      if "PAID_NONPAID" not in df.columns:
          df["PAID_NONPAID"] = "-"
      df["TIER"]  = ""
      df["공란1"] = ""
      df["공란2"] = ""
      df["공란3"] = ""
      df["공란4"] = ""
      df = df.rename(columns={
          "Subsidiary":         "SUBS",
          "Country":            "COUNTRY",
          "Site_Code":          "SITE CODE",
          "J11":                "REPORT NO.",
          "J3":                 "DIVISION",
          "J4":                 "DATE",
          "J5":                 "DEVICE TYPE",
          "J6":                 "TYPE",
          "J7":                 "LOGIN/NON",
          "PAID_NONPAID":       "PAID/NONPAID",
          "value":              "ITEM",
          "metric_value_adj":   "VALUE",
          "metric_col":         "KEY",
          "metric_value_origin":"value_origin",
          "Start_Date":         "start_date",
          "End_Date":           "end_date",
      })
      final_cols = [
          "TIER", "SUBS", "COUNTRY", "SITE CODE",
          "REPORT NO.", "DIVISION", "DATE", "DEVICE TYPE", "TYPE", "LOGIN/NON",
          "PAID/NONPAID", "ITEM", "VALUE", "KEY",
          "공란1", "공란2", "공란3", "공란4",
          "value_origin", "start_date", "end_date"
      ]
      return df[[c for c in final_cols if c in df.columns]]


  # ── 캠페인 키 분리 유틸 (260109v3.py 참조) ───────────────────────
  report_no_mapping = {
      "1_1": "1_1~2. S.com Traffic by Division",
      "2_1": "2_1~4. Basic Traffic",
      "3_1": "3_1. Traffic by Channel (Internal)",
      "3_2": "3_2. Traffic by Channel (External)",
      "3_3": "3_3. Home KV & GNB to Campaign Page",
      "4_1": "4_1. Order Conversion with Login/Non_Login",
      "4_2": "4_2. Order Conversion with Login/Non_Login (Visit)",
      "5_1": "5_1. S.com Order Conversion",
      "6_1": "6_1. S.com Cross Sell Order (Multi Purchase)",
      "6_2": "6_2. S.com Cross Sell Order (Total)",
      "6_3": "6_3. Campaign Page Cross Sell Order",
      "7_1": "7_1~2. Order Conversion/Traffic by Channel"
  }

  def _split_by_number_pattern(parts):
      # metric_col이 X_Y_... 형태로 시작할 때 (예: 1_1_da_2025_scom_...)
      if len(parts) >= 2 and re.fullmatch(r"\d{1,2}", parts[0]) and re.fullmatch(r"\d{1,2}", parts[1]):
          return "", f"{parts[0]}_{parts[1]}", parts[2:]
      for i in (2, 3):
          if i + 1 < len(parts) and parts[i].isdigit() and parts[i+1].isdigit():
              return '_'.join(parts[:i]), f"{parts[i]}_{parts[i+1]}", parts[i+2:]
      return parts[0], f"{parts[1]}_{parts[2]}", parts[3:]

  def _find_report_key(values):
      for v in values:
          if isinstance(v, str) and re.fullmatch(r"\d+_\d+", v):
              return v
      return ''

  def split_metric_col(val: str) -> dict:
      """metric_col → J1~J7, J11"""
      parts = str(val).split('_')
      if len(parts) < 3:
          j1_to_j7 = (parts + [''] * 7)[:7]
          return {**{f"J{i+1}": j1_to_j7[i] for i in range(7)}, "J11": "", "metric_name": ""}

      first, second, remaining = _split_by_number_pattern(parts)
      processed = []
      i = 0
      while i < len(remaining):
          if remaining[i].isdigit() and remaining[i].startswith('202'):
              if i + 2 < len(remaining) and remaining[i+2].lower() == 'prior':
                  processed.append(f"{remaining[i]}_{remaining[i+1]}_{remaining[i+2]}")
                  i += 3
              elif i + 1 < len(remaining):
                  processed.append(f"{remaining[i]}_{remaining[i+1]}")
                  i += 2
              else:
                  processed.append(remaining[i])
                  i += 1
          else:
              processed.append(remaining[i])
              i += 1

      all_parts = [first, second] + processed
      j1_to_j7 = (all_parts + [''] * 7)[:7]
      metric_name = '_'.join(all_parts[7:]) if len(all_parts) > 7 else ''
      report_key = _find_report_key(j1_to_j7)
      return {**{f"J{i+1}": j1_to_j7[i] for i in range(7)}, "J11": report_no_mapping.get(report_key, ''), "metric_name": metric_name}

  def _apply_j_cols(df: pd.DataFrame) -> pd.DataFrame:
      j_df = pd.DataFrame(
          [split_metric_col(v) for v in df["metric_col"]],
          index=df.index
      )
      return pd.concat([df, j_df], axis=1)

  # ── 매핑 로드 ─────────────────────────────────────────────────────
  mapping_df = pd.read_csv(MAPPING_CSV)
  id_vars = ["Subsidiary", "Country", "Site_Code", "RSID",
             "Start_Date", "End_Date", "itemId", "value"]

  ok_list, skip_list = [], []
  channel_frames = {}
  all_frames = []  # union용

  csv_files = [f for f in EXPORTS_DIR.glob("*.csv") if "_long" not in f.name and "_stacked" not in f.name]
  print(f"▶ 처리 대상: {len(csv_files)}개 파일\n")

  for src_path in sorted(csv_files):
      stem   = src_path.stem
      tb_key = re.sub(r"_\d{8}_\d{6}$", "", stem)

      tb_mapping = mapping_df[mapping_df["tb"] == tb_key]
      if tb_mapping.empty:
          tb_mapping = mapping_df[mapping_df["tb"] == re.sub(r"_prior$", "", tb_key)]

      if tb_mapping.empty:
          skip_list.append(tb_key)
          continue

      rename_dict = dict(zip(tb_mapping["value_n"], tb_mapping["column"]))

      df = pd.read_csv(src_path, encoding="utf-8-sig")
      df = df.rename(columns=rename_dict)
      value_vars = [c for c in rename_dict.values() if c in df.columns]

      for v in value_vars:
          df[v] = pd.to_numeric(
              df[v].astype(str).str.strip().str.replace("'", "", regex=False),
              errors="coerce"
          )

      df_long = df.melt(
          id_vars=[c for c in id_vars if c in df.columns],
          value_vars=value_vars,
          var_name="metric_col",
          value_name="metric_value_origin"
      )

      # ── currency 환율 적용 ────────────────────────────────────────
      df_long["_year"] = pd.to_datetime(df_long["Start_Date"]).dt.year.astype(str)
      df_long["_site"] = df_long["Site_Code"].str.strip().str.lower()

      def calc_adj(row):
          if "revenue" not in str(row["metric_col"]).lower():
              return row["metric_value_origin"]
          rates = cur_map.get(row["_site"])
          if not rates:
              return row["metric_value_origin"]
          rate = rates.get(row["_year"])
          if rate is None:
              return row["metric_value_origin"]
          try:
              return float(row["metric_value_origin"]) * float(rate)
          except (TypeError, ValueError):
              return row["metric_value_origin"]

      df_long["metric_value_adj"] = df_long.apply(calc_adj, axis=1)
      df_long = df_long.drop(columns=["_year", "_site"])

      df_long["metric_value_origin"] = pd.to_numeric(
          df_long["metric_value_origin"].astype(str).str.replace("'", "", regex=False),
          errors="coerce"
      )
      df_long["metric_value_adj"] = pd.to_numeric(
          df_long["metric_value_adj"].astype(str).str.replace("'", "", regex=False),
          errors="coerce"
      )

      # ── metric_col 키 분리 ────────────────────────────────────────
      df_long = _apply_j_cols(df_long)

      # ── channel 파일이면 수집, 아니면 바로 저장 ───────────────────
      is_channel = "channel" in tb_key.lower()
      if is_channel:
          channel_frames[tb_key] = df_long
      else:
          df_long["value"] = df_long["metric_name"]
          out_path = EXPORTS_DIR / f"{tb_key}_stacked_separate.csv"
          df_long.to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          ok_list.append(tb_key)
          if re.search(r'_\d{1,2}_\d{1,2}(?:_|$)', tb_key):
              all_frames.append(df_long)

  # ── channel 후처리 (루프 종료 후) ────────────────────────────────
  if channel_frames:
      print(f"\n▶ channel 후처리: {list(channel_frames.keys())}")

      for tb_key, df_long in channel_frames.items():

          # 1. US value 치환
          is_us = df_long["Site_Code"].str.strip().str.lower() == "us"
          df_long.loc[is_us, "value"] = (
              df_long.loc[is_us, "value"].map(us_mapping).fillna(df_long.loc[is_us, "value"])
          )

          # 2. dummy 0 삽입
          all_sites   = df_long["Site_Code"].unique()
          all_values  = df_long["value"].unique()
          metric_cols = df_long["metric_col"].unique()

          meta_cols = [c for c in ["Subsidiary", "Country", "RSID"] if c in df_long.columns]
          meta_df = (
              df_long.groupby("Site_Code")[meta_cols]
              .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
              .reset_index()
          )
          date_cols = [c for c in ["Start_Date", "End_Date", "itemId"] if c in df_long.columns]
          date_meta = (
              df_long.groupby("Site_Code")[date_cols]
              .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
              .reset_index()
          )

          cross = pd.MultiIndex.from_product(
              [all_sites, all_values, metric_cols],
              names=["Site_Code", "value", "metric_col"]
          ).to_frame(index=False)

          existing = df_long[["Site_Code", "value", "metric_col"]].drop_duplicates()
          existing["_exists"] = True

          merged = cross.merge(existing, on=["Site_Code", "value", "metric_col"], how="left")
          dummy_rows = merged[merged["_exists"].isna()].drop(columns=["_exists"])

          if not dummy_rows.empty:
              dummy_rows = dummy_rows.merge(meta_df, on="Site_Code", how="left")
              dummy_rows = dummy_rows.merge(date_meta, on="Site_Code", how="left")
              dummy_rows["metric_value_origin"] = 0.0
              dummy_rows["metric_value_adj"]    = 0.0
              dummy_rows = _apply_j_cols(dummy_rows)
              df_long = pd.concat([df_long, dummy_rows], ignore_index=True)
              print(f"  {tb_key} → dummy {len(dummy_rows)}행 삽입")

          # 3. PAID_NONPAID 컬럼 추가 (value 왼쪽)
          df_long["PAID_NONPAID"] = df_long["value"].map(global_paid_mapping)
          val_idx = df_long.columns.get_loc("value")
          cols = list(df_long.columns)
          cols.remove("PAID_NONPAID")
          cols.insert(val_idx, "PAID_NONPAID")
          df_long = df_long[cols]

          out_path = EXPORTS_DIR / f"{tb_key}_stacked_separate.csv"
        #   df_long.to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          finalize_df(df_long).to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          ok_list.append(tb_key)
          if re.search(r'_\d{1,2}_\d{1,2}(?:_|$)', tb_key):
              all_frames.append(df_long)

  # ── union 생성 ────────────────────────────────────────────────────
  if all_frames:
      ts = datetime.now().strftime("%Y%m%d_%H%M%S")
      union_path = EXPORTS_DIR / f"union_{ts}.csv"
      union_df = pd.concat(all_frames, ignore_index=True)
      if "PAID_NONPAID" in union_df.columns:
          union_df["PAID_NONPAID"] = union_df["PAID_NONPAID"].fillna("-")
    #   union_df.to_csv(union_path, index=False, encoding="utf-8-sig", float_format="%.6f")
      finalize_df(union_df).to_csv(union_path, index=False, encoding="utf-8-sig", float_format="%.6f")
      print(f"\n▶ union 저장: {union_path} ({len(union_df):,}행)")

  # ── 결과 요약 ─────────────────────────────────────────────────────
  print(f"\n✅ 완료: {len(ok_list)}개")
  for t in ok_list: print(f"  - {t}")
  print(f"\n⚠️  매핑 없어서 skip: {len(skip_list)}개")
  for t in skip_list: print(f"  - {t}")

▶ 환율 컬럼: 2026-02-28(2026) / 2025-02-28(2025)
▶ 처리 대상: 63개 파일


▶ channel 후처리: ['25_ny_3_1_channel_internal', '25_ny_3_2_channel_traffic_external', '25_ny_7_1_order_by_channel_cmp', '26_ny_3_1_channel_internal', '26_ny_3_2_channel_external_cmp', '26_ny_3_2_channel_external_scom', '26_ny_3_2_channel_external_scom_prior', '26_ny_7_1_order_by_channel_cmp', '26_ny_7_1_order_by_channel_scom', '26_ny_7_1_order_by_channel_scom_prior']
  25_ny_3_1_channel_internal → dummy 210행 삽입
  25_ny_3_2_channel_traffic_external → dummy 132행 삽입
  25_ny_7_1_order_by_channel_cmp → dummy 129행 삽입
  26_ny_3_2_channel_external_cmp → dummy 642행 삽입
  26_ny_3_2_channel_external_scom → dummy 120행 삽입
  26_ny_3_2_channel_external_scom_prior → dummy 116행 삽입
  26_ny_7_1_order_by_channel_cmp → dummy 1200행 삽입
  26_ny_7_1_order_by_channel_scom → dummy 180행 삽입
  26_ny_7_1_order_by_channel_scom_prior → dummy 174행 삽입

▶ union 저장: c:\Users\CNXK\OneDrive - Concentrix Corporation\pjh\2.data\99.PY,SQL-250429\00.py_notebook\260224_AA_Exporter(jiwoo)\aa_exports\union_20260304_131433.csv (219,156행)

✅ 완료: 59개
  - 25_ny_1_1_scom_da_traffic_app
  - 25_ny_1_1_scom_da_traffic_web
  - 25_ny_1_1_scom_mx_traffic_app
  - 25_ny_1_1_scom_mx_traffic_web
  - 25_ny_1_1_scom_vd_traffic_app
  - 25_ny_1_1_scom_vd_traffic_web
  - 25_ny_2_1_basic_traffic_cmp
  - 25_ny_2_1_basic_traffic_scom
  - 25_ny_2_1_basic_traffic_time
  - 25_ny_3_3_homepage_kv_gnb_to_cmp
  - 25_ny_4_1_order_cvr_loginout
  - 25_ny_4_1_scom_order_cvr_loginout
  - 25_ny_5_1_scom_campaign_order_cvr
  - 25_ny_6_1_multi_order_cross_sell
  - 25_ny_6_2_total_order_cross_sell
  - 25_ny_6_3_cmp_order_cross_sell
  - 25_ny_bestselling
  - 26_ny_1_1_scom_da_traffic_app
  - 26_ny_1_1_scom_da_traffic_app_prior
  - 26_ny_1_1_scom_da_traffic_web
  - 26_ny_1_1_scom_da_traffic_web_prior
  - 26_ny_1_1_scom_mx_traffic_app
  - 26_ny_1_1_scom_mx_traffic_app_prior
  - 26_ny_1_1_scom_mx_traffic_web
  - 26_ny_1_1_scom_mx_traffic_web_prior
  - 26_ny_1_1_scom_vd_traffic_app
  - 26_ny_1_1_scom_vd_traffic_app_prior
  - 26_ny_1_1_scom_vd_traffic_web
  - 26_ny_1_1_scom_vd_traffic_web_prior
  - 26_ny_2_1_basic_traffic_cmp
  - 26_ny_2_1_basic_traffic_scom
  - 26_ny_2_1_basic_traffic_scom_prior
  - 26_ny_2_1_basic_traffic_time_cmp
  - 26_ny_2_1_basic_traffic_time_scom
  - 26_ny_2_1_basic_traffic_time_scom_prior
  - 26_ny_3_3_homepage_kv_gnb_to_cmp
  - 26_ny_4_1_order_cvr_loginout
  - 26_ny_4_2_order_cvr_visit_visitor
  - 26_ny_5_1_campaign_order_cvr
  - 26_ny_5_1_scom_order_cvr
  - 26_ny_6_1_multi_order_cross_sell
  - 26_ny_6_1_multi_order_cross_sell_prior
  - 26_ny_6_2_total_order_cross_sell
  - 26_ny_6_2_total_order_cross_sell_prior
  - 26_ny_6_3_cmp_order_cross_sell
  - 26_ny_bestselling
  - 26_ny_nextpage
  - 26_ny_raw_multi_purchase_v41
  - 26_ny_raw_multi_purchase_v41_prior
  - 25_ny_3_1_channel_internal
  - 25_ny_3_2_channel_traffic_external
  - 25_ny_7_1_order_by_channel_cmp
  - 26_ny_3_1_channel_internal
  - 26_ny_3_2_channel_external_cmp
  - 26_ny_3_2_channel_external_scom
  - 26_ny_3_2_channel_external_scom_prior
  - 26_ny_7_1_order_by_channel_cmp
  - 26_ny_7_1_order_by_channel_scom
  - 26_ny_7_1_order_by_channel_scom_prior

⚠️  매핑 없어서 skip: 4개
  - 25_ny_3_2_channel_external_scom
  - union
  - union
  - union