In [1]:
# !pip install tqdm

In [2]:
## **1_1~2. S.com Traffic by Division**

In [3]:
#### **Scom DA Traffic APP**

In [4]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_da_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

c:\Users\CNXK\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

▶ Start time: 2026-03-04 10:28:02
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_app_20260304_102802.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [02:22<00:00, 10.20s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_app_20260304_102802.csv
총 데이터 row (FAILED row 제외, header 제외): 12
⏱ Elapsed: 0:02:22.965057
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_app_20260304_102802.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,5772.0,5456.0,...,1.0,1.0,5.0,5.0,0.0,4.087300e+04,4.087300e+04,0.000000e+00,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,243763.0,226255.0,...,89419.0,2377.0,4972.0,4000.0,972.0,5.518781e+09,4.319906e+09,1.198875e+09,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0,NaN,7672.0,5809.0,...,6.0,21.0,138.0,93.0,36.0,1.200229e+05,7.797360e+04,3.577040e+04,OK,NaN
3,SESAR,Saudi Arabia,SA,sssamsung4sa,2026-01-19,2026-02-26,0,NaN,4770.0,3251.0,...,17.0,33.0,82.0,37.0,41.0,2.676781e+05,1.039122e+05,1.490505e+05,OK,NaN
4,SESAR,Saudi Arabia (en),SA_EN,sssamsung4saen,2026-01-19,2026-02-26,0,NaN,2050.0,1500.0,...,17.0,10.0,36.0,20.0,16.0,1.334211e+05,7.323391e+04,6.018720e+04,OK,NaN

In [5]:
#### **Scom DA Traffic WEB**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_da_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:30:25
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_web_20260304_103025.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [01:02<00:00,  4.49s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_web_20260304_103025.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:03.047766
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_web_20260304_103025.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,19982.0,20116.0,...,14778.0,4018.0,7470.0,2510.0,9.0,8.0,1.342658e+05,1.213861e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,460664.0,898680.0,...,346013.0,753241.0,209149.0,377517.0,4685.0,11862.0,5.423614e+09,1.341480e+10,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,0,NaN,644.0,1629.0,...,461.0,1048.0,136.0,350.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0,NaN,41506.0,75584.0,...,28610.0,55872.0,6177.0,20084.0,187.0,138.0,1.438857e+05,7.504399e+04,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,0,NaN,12492.0,31301.0,...,9588.0,26387.0,3459.0,10990.0,94.0,106.0,2.400616e+06,2.066506e+06,OK,NaN

In [7]:
#### **Scom MX Traffic APP**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_mx_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:31:29
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_app_20260304_103129.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [01:26<00:00,  6.18s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_app_20260304_103129.csv
총 데이터 row (FAILED row 제외, header 제외): 12
⏱ Elapsed: 0:01:26.712221
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_app_20260304_103129.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,192351.0,178249.0,...,4.0,22.0,1558.0,1395.0,161.0,4.609409e+06,3.699109e+06,9.059586e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,1497019.0,1461357.0,...,89858.0,2725.0,36582.0,34330.0,2252.0,4.711210e+10,4.375493e+10,3.357167e+09,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0,NaN,41096.0,35795.0,...,13.0,4.0,571.0,492.0,33.0,3.265292e+05,2.697558e+05,2.852822e+04,OK,NaN
3,SESAR,Saudi Arabia,SA,sssamsung4sa,2026-01-19,2026-02-26,0,NaN,57930.0,47867.0,...,51.0,10.0,1979.0,1656.0,229.0,5.637853e+06,4.430262e+06,8.208929e+05,OK,NaN
4,SESAR,Saudi Arabia (en),SA_EN,sssamsung4saen,2026-01-19,2026-02-26,0,NaN,37434.0,32184.0,...,40.0,3.0,608.0,509.0,63.0,2.672655e+06,2.213837e+06,2.930155e+05,OK,NaN

In [9]:
#### **Scom MX Traffic WEB**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_mx_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:32:56
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_web_20260304_103256.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [02:21<00:00, 10.13s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_web_20260304_103256.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:02:22.028712
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_web_20260304_103256.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0.0,NaN,194192.0,518313.0,...,117783.0,275770.0,52096.0,169639.0,920.0,828.0,6.520484e+06,4.120123e+06,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0.0,NaN,1084749.0,2252617.0,...,822301.0,1933339.0,231155.0,613340.0,21478.0,25934.0,3.158027e+10,3.491383e+10,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,0.0,NaN,5937.0,117594.0,...,5046.0,109412.0,1639.0,74482.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0.0,NaN,95285.0,242097.0,...,59908.0,181560.0,13311.0,73379.0,478.0,566.0,3.660845e+05,3.957382e+05,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,0.0,NaN,26174.0,94174.0,...,19344.0,75447.0,7077.0,29457.0,169.0,253.0,3.432134e+06,4.444694e+06,OK,NaN

In [11]:
#### **Scom VD Traffic APP**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_vd_traffic_app.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:35:19
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_app_20260304_103519.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24']

AA Export (sites): 100%|██████████| 14/14 [02:45<00:00, 11.84s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_app_20260304_103519.csv
총 데이터 row (FAILED row 제외, header 제외): 12
⏱ Elapsed: 0:02:45.945339
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_app_20260304_103519.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value17,value18,value19,value20,value21,value22,value23,value24,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,15578.0,13663.0,...,0.0,6.0,51.0,34.0,17.0,2.517121e+05,1.508357e+05,1.008763e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,118651.0,111525.0,...,49538.0,975.0,1248.0,1012.0,236.0,2.274896e+09,1.842068e+09,4.328280e+08,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0,NaN,11471.0,8639.0,...,10.0,36.0,163.0,108.0,49.0,1.431675e+05,9.339368e+04,4.416000e+04,OK,NaN
3,SESAR,Saudi Arabia,SA,sssamsung4sa,2026-01-19,2026-02-26,0,NaN,8175.0,5345.0,...,34.0,62.0,121.0,55.0,55.0,4.085850e+05,1.669534e+05,2.026986e+05,OK,NaN
4,SESAR,Saudi Arabia (en),SA_EN,sssamsung4saen,2026-01-19,2026-02-26,0,NaN,3415.0,2502.0,...,0.0,9.0,45.0,29.0,15.0,1.113014e+05,6.875715e+04,3.894525e+04,OK,NaN

In [13]:
#### **Scom VD Traffic WEB**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_1_1_scom_vd_traffic_web.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:38:05
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_web_20260304_103805.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [01:08<00:00,  4.91s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_web_20260304_103805.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:08.899221
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_web_20260304_103805.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,68917.0,59818.0,...,43685.0,12506.0,19281.0,6249.0,40.0,46.0,2.572609e+05,4.978723e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,233770.0,290100.0,...,168992.0,226794.0,102905.0,116819.0,1400.0,1655.0,2.506184e+09,3.642071e+09,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,0,NaN,989.0,2577.0,...,697.0,1781.0,199.0,684.0,0.0,0.0,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0,NaN,48163.0,73932.0,...,33112.0,58237.0,6538.0,22298.0,258.0,219.0,2.334479e+05,1.805727e+05,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,0,NaN,17389.0,55088.0,...,14001.0,49985.0,6132.0,30060.0,80.0,98.0,3.507414e+06,3.230044e+06,OK,NaN

In [15]:
## **2_1~4. Basic Traffic**

In [16]:
#### **Basic Traffic CMP**

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:39:15
▶ Output: aa_exports\26_ny_2_1_basic_traffic_cmp_20260304_103915.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30', 'value31', 'value32', 'value33', 'value34', 'value35']

AA Export (sites): 100%|██████████| 14/14 [01:17<00:00,  5.55s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_cmp_20260304_103915.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:17.791464
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_cmp_20260304_103915.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value28,value29,value30,value31,value32,value33,value34,value35,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),60321.0,2434303.0,...,2027.0,4734.0,2112.0,271.0,1839.0,0.0,0.0,0.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),89426.0,655043.0,...,98986.0,1902.0,88003.0,87192.0,811.0,0.0,0.0,0.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001,2026 (Jan 1-Dec 31),84.0,40.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001,2026 (Jan 1-Dec 31),15521.0,26676.0,...,44.0,37.0,15.0,6.0,9.0,0.0,0.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001,2026 (Jan 1-Dec 31),1522.0,5005.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [18]:
#### **Basic Traffic Scom**

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:40:33
▶ Output: aa_exports\26_ny_2_1_basic_traffic_scom_20260304_104033.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18', 'value19', 'value20', 'value21', 'value22', 'value23', 'value24', 'value25', 'value26', 'value27', 'value28', 'value29', 'value30']

AA Export (sites): 100%|██████████| 14/14 [00:17<00:00,  1.27s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_scom_20260304_104033.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:00:17.848922
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_scom_20260304_104033.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value23,value24,value25,value26,value27,value28,value29,value30,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,632113.0,4546192.0,...,7788477.0,202718.0,723830.0,688570.0,35230.0,240382.0,223987.0,16370.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,2399258.0,7194107.0,...,18170680.0,515064.0,7155517.0,7052389.0,103124.0,4049660.0,4015077.0,34581.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,0,NaN,12380.0,206257.0,...,7.0,0.0,2.0,2.0,0.0,2.0,2.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0,NaN,255778.0,720696.0,...,2087062.0,102972.0,228569.0,195120.0,18959.0,79949.0,64142.0,11456.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,0,NaN,84736.0,421903.0,...,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,OK,NaN

In [20]:
#### **Basic Traffic Time CMP**

In [21]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_time_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:40:51
▶ Output: aa_exports\26_ny_2_1_basic_traffic_time_cmp_20260304_104051.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [00:14<00:00,  1.04s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_time_cmp_20260304_104051.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:00:14.725608
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_time_cmp_20260304_104051.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),210.757880,313.729185,177.347415,194.744887,186.595454,351.321972,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),255.702038,424.784837,244.006818,217.335013,214.564222,380.786812,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001,2026 (Jan 1-Dec 31),164.493386,189.776095,161.587499,16.500000,16.500000,0.000000,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001,2026 (Jan 1-Dec 31),297.486379,382.140108,270.640981,266.697739,259.213421,352.295690,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001,2026 (Jan 1-Dec 31),227.247158,317.228344,204.779614,41.000000,41.000000,0.000000,OK,NaN

In [22]:
#### **Basic Traffic Time Scom**

In [23]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_2_1_basic_traffic_time_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:41:07
▶ Output: aa_exports\26_ny_2_1_basic_traffic_time_scom_20260304_104107.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [00:01<00:00, 10.23site/s, ok=1, rows=1, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_time_scom_20260304_104107.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:00:01.473152
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_time_scom_20260304_104107.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),210.757880,313.729185,177.347415,194.744887,186.595454,351.321972,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),255.702038,424.784837,244.006818,217.335013,214.564222,380.786812,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001,2026 (Jan 1-Dec 31),164.493386,189.776095,161.587499,16.500000,16.500000,0.000000,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001,2026 (Jan 1-Dec 31),297.486379,382.140108,270.640981,266.697739,259.213421,352.295690,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001,2026 (Jan 1-Dec 31),227.247158,317.228344,204.779614,41.000000,41.000000,0.000000,OK,NaN

In [24]:
## **3. Traffic by Channel**

In [25]:
#### **Channel Internal**

In [26]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_1_channel_internal.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:41:09
▶ Output: aa_exports\26_ny_3_1_channel_internal_20260304_104109.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites): 100%|██████████| 14/14 [00:32<00:00,  2.30s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_1_channel_internal_20260304_104109.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:00:32.308626
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_1_channel_internal_20260304_104109.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),221.0,116.0,...,0.0,0.0,172.0,6564.0,10843.0,0.0,0.0,172.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),585.0,3959.0,...,0.0,0.0,1.0,1859.0,44.0,0.0,0.0,0.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001,2026 (Jan 1-Dec 31),10.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001,2026 (Jan 1-Dec 31),22.0,175.0,...,2.0,0.0,0.0,694.0,0.0,0.0,0.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001,2026 (Jan 1-Dec 31),3.0,150.0,...,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [27]:
#### **Channel External CMP**

In [28]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_2_channel_external_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:41:42
▶ Output: aa_exports\26_ny_3_2_channel_external_cmp_20260304_104141.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [00:26<00:00,  1.87s/site, ok=1, rows=18, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_2_channel_external_cmp_20260304_104141.csv
총 데이터 row (FAILED row 제외, header 제외): 229
⏱ Elapsed: 0:00:26.239066
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_2_channel_external_cmp_20260304_104141.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1,Paid Search,42143.0,12248.0,78813.0,55081.0,32.0,6.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,11,Social Media Campaigns,2894.0,2268.0,591706.0,590968.0,0.0,0.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,5,Direct,2002.0,451.0,11663.0,5896.0,5957.0,1916.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,15,Mobile Application,1533.0,1134.0,81175.0,66576.0,134.0,52.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,16,Affiliate Marketing,1382.0,915.0,1611888.0,1405319.0,48.0,36.0,OK,NaN

In [29]:
#### **Channel External Scom**

In [30]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_2_channel_external_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:42:08
▶ Output: aa_exports\26_ny_3_2_channel_external_scom_20260304_104208.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 14/14 [00:41<00:00,  2.96s/site, ok=1, rows=24, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_2_channel_external_scom_20260304_104208.csv
총 데이터 row (FAILED row 제외, header 제외): 306
⏱ Elapsed: 0:00:41.563744
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_2_channel_external_scom_20260304_104208.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,16,Affiliate Marketing,1614838.0,1406601.0,114.0,78.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,5,Direct,809174.0,578688.0,663252.0,228007.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,20,Display,770934.0,707365.0,83.0,26.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,11,Social Media Campaigns,600209.0,598223.0,59.0,9.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,14,Push,356835.0,299925.0,44418.0,8938.0,OK,NaN

In [31]:
#### **Homepage KV GNB TO CMP**

In [32]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_3_3_homepage_kv_gnb_to_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:42:50
▶ Output: aa_exports\26_ny_3_3_homepage_kv_gnb_to_cmp_20260304_104250.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9']

AA Export (sites): 100%|██████████| 14/14 [02:19<00:00,  9.99s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_3_homepage_kv_gnb_to_cmp_20260304_104250.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:02:20.036255
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_3_3_homepage_kv_gnb_to_cmp_20260304_104250.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,value7,value8,value9,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001.0,2026 (Jan 1-Dec 31),143999.0,147841.0,426663.0,116.0,301.0,6564.0,122.0,10.0,172.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001.0,2026 (Jan 1-Dec 31),497838.0,909932.0,4434688.0,3959.0,7135.0,1859.0,162.0,97.0,0.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001.0,2026 (Jan 1-Dec 31),2546.0,13550.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001.0,2026 (Jan 1-Dec 31),43871.0,109301.0,154307.0,175.0,522.0,694.0,13.0,1.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001.0,2026 (Jan 1-Dec 31),16679.0,88539.0,0.0,150.0,1407.0,0.0,0.0,2.0,0.0,OK,NaN

In [33]:
## **4. Order CVR**

In [34]:
#### **Order CVR Loginout**

In [35]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_4_1_order_cvr_loginout.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:45:11
▶ Output: aa_exports\26_ny_4_1_order_cvr_loginout_20260304_104511.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16', 'value17', 'value18']

AA Export (sites): 100%|██████████| 14/14 [03:59<00:00, 17.08s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_4_1_order_cvr_loginout_20260304_104511.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:03:59.284641
❌ 실패 site: 0
DONE: aa_exports\26_ny_4_1_order_cvr_loginout_20260304_104511.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value11,value12,value13,value14,value15,value16,value17,value18,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),282256.0,8676.0,...,1.099395e+07,47830.20,3701.0,3584.0,117.0,1.671588e+07,1.630323e+07,4.126448e+05,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),52808.0,9072.0,...,3.526659e+09,660900.00,122997.0,121721.0,1276.0,1.468690e+11,1.462702e+11,5.988030e+08,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001,2026 (Jan 1-Dec 31),18.0,0.0,...,0.000000e+00,0.00,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001,2026 (Jan 1-Dec 31),22526.0,2466.0,...,1.526396e+05,63336.68,2796.0,2180.0,616.0,1.932763e+06,1.486247e+06,4.465159e+05,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001,2026 (Jan 1-Dec 31),2077.0,122.0,...,5.707695e+05,182895.20,809.0,509.0,300.0,1.906657e+07,1.275374e+07,6.312829e+06,OK,NaN

In [36]:
#### **Order CVR Visit Visitor**

In [37]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_4_2_order_cvr_visit_visitor.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:49:11
▶ Output: aa_exports\26_ny_4_2_order_cvr_visit_visitor_20260304_104911.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 14/14 [03:42<00:00, 15.88s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_4_2_order_cvr_visit_visitor_20260304_104911.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:03:42.449804
❌ 실패 site: 0
DONE: aa_exports\26_ny_4_2_order_cvr_visit_visitor_20260304_104911.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),5799.0,2488825.0,...,59196.0,11478.0,41490.0,7855.0,29701.0,5148604.0,402229.0,321603.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),146133.0,598336.0,...,121783.0,6081.0,106384.0,3950.0,3097552.0,6495813.0,6320315.0,835202.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001,2026 (Jan 1-Dec 31),17.0,107.0,...,0.0,0.0,0.0,0.0,2044.0,216593.0,2.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001,2026 (Jan 1-Dec 31),5265.0,36932.0,...,843.0,152.0,800.0,142.0,69488.0,906986.0,150379.0,78190.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001,2026 (Jan 1-Dec 31),461.0,6066.0,...,0.0,0.0,0.0,0.0,12947.0,493692.0,1.0,0.0,OK,NaN

In [38]:
## **5. Campaign Order CVR**

In [39]:
#### **Campaign Order CVR**

In [40]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_5_1_campaign_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:52:54
▶ Output: aa_exports\26_ny_5_1_campaign_order_cvr_20260304_105254.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12']

AA Export (sites): 100%|██████████| 14/14 [01:17<00:00,  5.52s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_5_1_campaign_order_cvr_20260304_105254.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:01:17.434369
❌ 실패 site: 0
DONE: aa_exports\26_ny_5_1_campaign_order_cvr_20260304_105254.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value5,value6,value7,value8,value9,value10,value11,value12,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),3701.0,1.671588e+07,...,1532.0,212.0,5.213019e+06,4.069522e+06,1.139155e+06,391.0,315.0,75.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),122997.0,1.468690e+11,...,41636.0,3731.0,5.462788e+10,4.967051e+10,4.957371e+09,2694.0,2378.0,316.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001,2026 (Jan 1-Dec 31),0.0,0.000000e+00,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001,2026 (Jan 1-Dec 31),2796.0,1.932763e+06,...,692.0,121.0,5.634027e+05,4.212380e+05,1.040579e+05,188.0,158.0,23.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001,2026 (Jan 1-Dec 31),809.0,1.906657e+07,...,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,OK,NaN

In [ ]:
#### **Scom Order CVR**

In [43]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_5_1_scom_order_cvr.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:55:20
▶ Output: aa_exports\26_ny_5_1_scom_order_cvr_20260304_105520.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [00:41<00:00,  3.00s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_5_1_scom_order_cvr_20260304_105520.csv
총 데이터 row (FAILED row 제외, header 제외): 14
⏱ Elapsed: 0:00:42.052416
❌ 실패 site: 0
DONE: aa_exports\26_ny_5_1_scom_order_cvr_20260304_105520.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001,2026 (Jan 1-Dec 31),1796.0,1846.0,...,343.0,81.0,461.0,370.0,90.0,133.0,107.0,26.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001,2026 (Jan 1-Dec 31),1789.0,2091.0,...,816.0,167.0,1164.0,812.0,352.0,151.0,125.0,26.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001,2026 (Jan 1-Dec 31),0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001,2026 (Jan 1-Dec 31),256.0,269.0,...,12.0,3.0,45.0,37.0,5.0,3.0,3.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001,2026 (Jan 1-Dec 31),16.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [ ]:
## **6. S.com Cross Sell Order**

In [ ]:
#### **Multi Order Cross Sell**

In [44]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_1_multi_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 10:56:02
▶ Output: aa_exports\26_ny_6_1_multi_order_cross_sell_20260304_105602.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [04:07<00:00, 17.65s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_1_multi_order_cross_sell_20260304_105602.csv
총 데이터 row (FAILED row 제외, header 제외): 12
⏱ Elapsed: 0:04:07.314993
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_6_1_multi_order_cross_sell_20260304_105602.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0.0,NaN,1364.0,1.022199e+07,...,9.0,2.549130e+05,0.0,0.000000e+00,7.0,1.297253e+05,0.0,0.00,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0.0,NaN,7563.0,1.240615e+10,...,155.0,2.711655e+08,216.0,1.687022e+09,762.0,8.445645e+08,13.0,61161500.00,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0.0,NaN,530.0,5.679180e+05,...,14.0,1.158452e+04,19.0,4.343429e+04,2.0,3.775950e+03,1.0,3334.64,OK,NaN
3,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,0.0,NaN,649.0,1.671647e+07,...,1.0,5.689796e+04,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.00,OK,NaN
4,SESAR,Saudi Arabia,SA,sssamsung4sa,2026-01-19,2026-02-26,0.0,NaN,1741.0,5.718942e+06,...,3.0,1.684273e+04,1.0,6.828000e+03,2.0,1.285660e+03,0.0,0.00,OK,NaN

In [ ]:
#### **Total Order Cross Sell**

In [45]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_2_total_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:00:10
▶ Output: aa_exports\26_ny_6_2_total_order_cross_sell_20260304_110010.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [01:33<00:00,  6.70s/site, ok=1, rows=1, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_2_total_order_cross_sell_20260304_110010.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:01:33.934562
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_2_total_order_cross_sell_20260304_110010.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,0,NaN,3701.0,1.671588e+07,...,9.0,2.549130e+05,0.0,0.000000e+00,7.0,1.297253e+05,0.0,0.00,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,0,NaN,122997.0,1.468690e+11,...,155.0,2.711655e+08,216.0,1.687022e+09,762.0,8.445645e+08,13.0,61161500.00,OK,NaN
2,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,0,NaN,2796.0,1.932763e+06,...,14.0,1.158452e+04,19.0,4.343429e+04,2.0,3.775950e+03,1.0,3334.64,OK,NaN
3,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,0,NaN,809.0,1.906657e+07,...,1.0,5.689796e+04,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.00,OK,NaN
4,SESAR,Saudi Arabia,SA,sssamsung4sa,2026-01-19,2026-02-26,0,NaN,3508.0,1.086702e+07,...,3.0,1.684273e+04,1.0,6.828000e+03,2.0,1.285660e+03,0.0,0.00,OK,NaN

In [ ]:
#### **CMP Order Cross Sell**

In [46]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_6_3_cmp_order_cross_sell.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:01:45
▶ Output: aa_exports\26_ny_6_3_cmp_order_cross_sell_20260304_110145.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15', 'value16']

AA Export (sites): 100%|██████████| 14/14 [03:17<00:00, 14.08s/site, ok=0, rows=0, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_3_cmp_order_cross_sell_20260304_110145.csv
총 데이터 row (FAILED row 제외, header 제외): 13
⏱ Elapsed: 0:03:17.781893
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 408 Client Error: Request Timeout for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_6_3_cmp_order_cross_sell_20260304_110145.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value9,value10,value11,value12,value13,value14,value15,value16,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1260001.0,2026 (Jan 1-Dec 31),1846.0,1.104178e+07,...,6.0,179503.04,0.0,0.000000e+00,6.0,111066.34,0.0,0.0,OK,NaN
1,SEC,Korea,SEC,sssamsung4sec,2026-02-01,2026-02-28,1260001.0,2026 (Jan 1-Dec 31),2091.0,3.527320e+09,...,8.0,16577800.00,36.0,2.637011e+08,10.0,20063045.00,0.0,0.0,OK,NaN
2,SCA,Africa Pan (fr),AFRICA_FR,sssamsung4africafr,2026-01-29,2026-02-11,1260001.0,2026 (Jan 1-Dec 31),0.0,0.000000e+00,...,0.0,0.00,0.0,0.000000e+00,0.0,0.00,0.0,0.0,OK,NaN
3,SEI,Italy,IT,sssamsung4it,2026-01-21,2026-02-17,1260001.0,2026 (Jan 1-Dec 31),269.0,2.159763e+05,...,0.0,0.00,3.0,9.967040e+03,0.0,0.00,0.0,0.0,OK,NaN
4,SEUC,Ukraine,UA,sssamsung4ua,2026-01-19,2026-02-10,1260001.0,2026 (Jan 1-Dec 31),19.0,7.536647e+05,...,0.0,0.00,0.0,0.000000e+00,0.0,0.00,0.0,0.0,OK,NaN

In [ ]:
## **7. Order Conversion/Traffic by Channel**

In [ ]:
#### **Order BY Channel CMP**

In [47]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_7_1_order_by_channel_cmp.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:05:04
▶ Output: aa_exports\26_ny_7_1_order_by_channel_cmp_20260304_110504.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6', 'value7', 'value8', 'value9', 'value10', 'value11', 'value12', 'value13', 'value14', 'value15']

AA Export (sites): 100%|██████████| 14/14 [02:35<00:00, 11.10s/site, ok=1, rows=19, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_7_1_order_by_channel_cmp_20260304_110504.csv
총 데이터 row (FAILED row 제외, header 제외): 256
⏱ Elapsed: 0:02:36.099221
❌ 실패 site: 0
DONE: aa_exports\26_ny_7_1_order_by_channel_cmp_20260304_110504.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,...,value8,value9,value10,value11,value12,value13,value14,value15,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1,Paid Search,43446.0,80317.0,...,1.0,0.0,1.0,1275544.12,233844.79,8862.98,0.00,8862.98,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,5,Direct,3440.0,26389.0,...,355.0,281.0,74.0,388302.04,0.00,1337647.89,944719.27,392928.62,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,11,Social Media Campaigns,2953.0,591718.0,...,0.0,0.0,0.0,1978901.04,803336.14,0.00,0.00,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2,Natural Search,2743.0,1306.0,...,0.0,0.0,0.0,71864.83,34570.14,0.00,0.00,0.00,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,15,Mobile Application,1625.0,83176.0,...,23.0,23.0,0.0,0.00,46071.19,60845.68,60845.68,0.00,OK,NaN

In [ ]:
#### **Order BY Channel Scom**

In [48]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_7_1_order_by_channel_scom.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:07:41
▶ Output: aa_exports\26_ny_7_1_order_by_channel_scom_20260304_110741.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [01:06<00:00,  4.77s/site, ok=1, rows=22, site=PH]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_7_1_order_by_channel_scom_20260304_110741.csv
총 데이터 row (FAILED row 제외, header 제외): 306
⏱ Elapsed: 0:01:07.888091
❌ 실패 site: 0
DONE: aa_exports\26_ny_7_1_order_by_channel_scom_20260304_110741.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,16,Affiliate Marketing,1614838.0,114.0,538.0,9.0,4418482.18,44056.62,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,5,Direct,809174.0,663256.0,228.0,1546.0,1081443.20,4616092.43,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,20,Display,770934.0,83.0,0.0,0.0,0.00,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,11,Social Media Campaigns,600209.0,59.0,368.0,0.0,2848938.04,0.00,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,14,Push,356835.0,44418.0,11.0,133.0,64406.36,375296.31,OK,NaN

In [ ]:
## **Multi Purchase**

In [ ]:
#### **RAW Multi Purchase V41**

In [49]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_raw_multi_purchase_v41.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:08:50
▶ Output: aa_exports\26_ny_raw_multi_purchase_v41_20260304_110850.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4', 'value5', 'value6']

AA Export (sites): 100%|██████████| 14/14 [00:29<00:00,  2.08s/site, ok=1, rows=1868, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_raw_multi_purchase_v41_20260304_110850.csv
총 데이터 row (FAILED row 제외, header 제외): 12,526
⏱ Elapsed: 0:00:29.899177
❌ 실패 site: 0
DONE: aa_exports\26_ny_raw_multi_purchase_v41_20260304_110850.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,value5,value6,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3667055378,"SM-S9380ZSDCHC,EP-T4511XBCMCN",217.0,85.0,645911.2,219.0,86.0,653510.2,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,4002195195,"SM-S9380ZKDCHC,EP-T4511XBCMCN",158.0,66.0,501532.2,189.0,78.0,592720.2,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3360070075,"SM-S9380ZBDCHC,EP-T4511XBCMCN",122.0,42.0,319154.4,122.0,42.0,319154.4,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2459278122,"SM-S9380ZSGCHC,EP-T4511XBCMCN",113.0,44.0,377854.0,113.0,44.0,377854.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,459863883,"SM-S9380ZTGCHC,EP-T4511XBCMCN",103.0,39.0,335359.2,103.0,39.0,335359.2,OK,NaN

In [ ]:
## **Best Selling Product**

In [ ]:
#### **Bestselling**

In [50]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_bestselling.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:09:21
▶ Output: aa_exports\26_ny_bestselling_20260304_110921.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 14/14 [00:24<00:00,  1.72s/site, ok=1, rows=697, site=UK]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_bestselling_20260304_110921.csv
총 데이터 row (FAILED row 제외, header 제외): 4,954
⏱ Elapsed: 0:00:24.348362
❌ 실패 site: 0
DONE: aa_exports\26_ny_bestselling_20260304_110921.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3340441902,EP-T4511,768.0,23653.33,646.0,4403.90,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2597718718,SM-S9380,707.0,5700459.18,645.0,5198299.73,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2983901684,NaN,577.0,0.00,485.0,0.00,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,163391546,SM-S9280,442.0,2444128.39,219.0,1208394.32,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,1525368397,SM-F9660,236.0,3136018.64,177.0,2317336.65,OK,NaN

In [ ]:
## **Next Page**

In [ ]:
#### **Nextpage**

In [51]:
from pathlib import Path
import importlib
import utils.aa_exporter_jh2
importlib.reload(utils.aa_exporter_jh2)

from utils.aa_exporter_jh2 import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 형태 맞게 설정
tb_cols = make_tb_columns(base)

json_file_name = "26_ny_nextpage.json"

json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path),
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,
    tb_columns=None,
    parallel_sites=True,
    max_workers=6,
    log_each_page=False,
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-03-04 11:09:46
▶ Output: aa_exports\26_ny_nextpage_20260304_110946.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000
▶ Metric columns: ['value1', 'value2', 'value3', 'value4']

AA Export (sites): 100%|██████████| 14/14 [05:38<00:00, 24.15s/site, ok=1, rows=57, site=SG]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_nextpage_20260304_110946.csv
총 데이터 row (FAILED row 제외, header 제외): 610
⏱ Elapsed: 0:05:38.292762
❌ 실패 site: 1
실패 목록 (앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_nextpage_20260304_110946.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,value1,value2,value3,value4,status,error
0,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3.457728e+09,flagship pdp,131723.0,131651.0,0.0,0.0,OK,NaN
1,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,2.067554e+09,product detail,117238.0,61457.0,40968.0,13598.0,OK,NaN
2,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,3.543974e+09,product finder,14609.0,11942.0,1932.0,239.0,OK,NaN
3,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,9.147071e+08,shop event,36311.0,9550.0,910.0,1.0,OK,NaN
4,SCIC,China,CN,sssamsung4cn,2026-01-16,2026-02-14,8.041200e+08,product category detail,917.0,198.0,8.0,0.0,OK,NaN

In [ ]:
## **CC (Contents)**

In [ ]:
#### **CC Order**

In [ ]:
#### **CC Revenue**

In [ ]:
#### **CC Visit**

# **CSV to Excel Raw Sheet Format**

In [ ]:
  # ─────────────────────────────────────────────────────────────────
  # [셀 2] POST-PROCESSING: 매핑 + long 변환 + currency 환율 적용
  #        + channel: US 매핑 / dummy 0 / PAID_NONPAID
  #        + metric_col 키 분리 (J1~J7, J11)
  #        + 개별 _stacked_separate.csv + 전체 union 저장
  # ─────────────────────────────────────────────────────────────────
  import re
  from pathlib import Path
  from datetime import datetime
  import pandas as pd

  MAPPING_CSV  = Path.cwd() / "tb_column_name_mapping.csv"
  CURRENCY_CSV = Path.cwd() / "currency.csv"
  EXPORTS_DIR  = Path.cwd() / "aa_exports"

  # ── currency 로드 ─────────────────────────────────────────────────
  cur_df = pd.read_csv(CURRENCY_CSV)
  col_latest = cur_df.columns[2]
  col_prior  = cur_df.columns[3]
  year_latest = str(pd.to_datetime(col_latest).year)
  year_prior  = str(pd.to_datetime(col_prior).year)
  print(f"▶ 환율 컬럼: {col_latest}({year_latest}) / {col_prior}({year_prior})")

  cur_map = {
      str(r["site_code"]).strip().lower(): {
          year_latest: r[col_latest],
          year_prior:  r[col_prior],
      }
      for _, r in cur_df.iterrows()
  }

  # ── channel 매핑 정의 ─────────────────────────────────────────────
  us_mapping = {
      "US Channel":"Global Channel Mapping ",
      "Affiliate":"Affiliate Marketing",
      "Display":"Display",
      "Display Retargeting":"Display",
      "Other External Campaign":"Paid Others",
      "Other Paid Ecomm":"Paid Others",
      "Paid Search":"Paid Search",
      "Paid Search - eComm":"Paid Search",
      "PLA":"Pmax",
      "Social (Paid)":"Social Media Campaigns",
      "Vanity":"Paid Others",
      "Direct":"Direct",
      "Email - CRM":"Email",
      "Email - eComm":"Email",
      "Email - Upsell it":"Email",
      "Email (Retired)":"Email",
      "EPP":"EPP - US",
      "Natural Search":"Natural Search",
      "Other":"Other",
      "None":"Other",
      "Push Notifications":"Push",
      "Referring Domains":"Other",
      "Session Refresh":"Session Refresh",
      "Social (Free and Owned)":"Owned Social",
      "Social (Retired)":"Social Network Referrals",
      "Other External CampaignSegments":"Mobile Application",
      "Other External CampaignUS_Smartthings":"Mobile Application - Smartthings",
      "Other External CampaignUS_Samsung Members":"Mobile Application - Samsung Members",
      "SMS":"SMS",
      "Gen AI Search":"Gen AI (Organic)"
  }

  global_paid_mapping = {
      "Paid Search":"Paid",
      "Social Media Campaigns":"Paid",
      "Affiliate Marketing":"Paid",
      "Display":"Paid",
      "Other Campaigns":"Paid",
      "QR code (Paid)":"Paid",
      "Pmax":"Paid",
      "Demand Gen":"Paid",
      "Paid Others":"Paid",
      "Video":"Paid",
      "Gen AI (Paid)":"Paid",
      "Session Refresh":"Non-Paid",
      "Email":"Non-Paid",
      "Direct":"Non-Paid",
      "Natural Search":"Non-Paid",
      "Mobile Application":"Non-Paid",
      "Push":"Non-Paid",
      "Social Network Referrals":"Non-Paid",
      "Other":"Non-Paid",
      "SMS":"Non-Paid",
      "None":"Non-Paid",
      "Owned Social":"Non-Paid",
      "QR code (Owned)":"Non-Paid",
      "Samsung Web":"Non-Paid",
      "Gen AI (Organic)":"Non-Paid",
      "Owned Others":"Non-Paid"
  }

  # ── 최종 컬럼 정리 ────────────────────────────────────────────────
  def finalize_df(df: pd.DataFrame) -> pd.DataFrame:
      df = df.copy()
      if "PAID_NONPAID" not in df.columns:
          df["PAID_NONPAID"] = "-"
      df["TIER"]  = ""
      df["공란1"] = ""
      df["공란2"] = ""
      df["공란3"] = ""
      df["공란4"] = ""
      df = df.rename(columns={
          "Subsidiary":         "SUBS",
          "Country":            "COUNTRY",
          "Site_Code":          "SITE CODE",
          "J11":                "REPORT NO.",
          "J3":                 "DIVISION",
          "J4":                 "DATE",
          "J5":                 "DEVICE TYPE",
          "J6":                 "TYPE",
          "J7":                 "LOGIN/NON",
          "PAID_NONPAID":       "PAID/NONPAID",
          "value":              "ITEM",
          "metric_value_adj":   "VALUE",
          "metric_col":         "KEY",
          "metric_value_origin":"value_origin",
          "Start_Date":         "start_date",
          "End_Date":           "end_date",
      })
      final_cols = [
          "TIER", "SUBS", "COUNTRY", "SITE CODE",
          "REPORT NO.", "DIVISION", "DATE", "DEVICE TYPE", "TYPE", "LOGIN/NON",
          "PAID/NONPAID", "ITEM", "VALUE", "KEY",
          "공란1", "공란2", "공란3", "공란4",
          "value_origin", "start_date", "end_date"
      ]
      return df[[c for c in final_cols if c in df.columns]]


  # ── 캠페인 키 분리 유틸 (260109v3.py 참조) ───────────────────────
  report_no_mapping = {
      "1_1": "1_1~2. S.com Traffic by Division",
      "2_1": "2_1~4. Basic Traffic",
      "3_1": "3_1. Traffic by Channel (Internal)",
      "3_2": "3_2. Traffic by Channel (External)",
      "3_3": "3_3. Home KV & GNB to Campaign Page",
      "4_1": "4_1. Order Conversion with Login/Non_Login",
      "4_2": "4_2. Order Conversion with Login/Non_Login (Visit)",
      "5_1": "5_1. S.com Order Conversion",
      "6_1": "6_1. S.com Cross Sell Order (Multi Purchase)",
      "6_2": "6_2. S.com Cross Sell Order (Total)",
      "6_3": "6_3. Campaign Page Cross Sell Order",
      "7_1": "7_1~2. Order Conversion/Traffic by Channel"
  }

  def _split_by_number_pattern(parts):
      # metric_col이 X_Y_... 형태로 시작할 때 (예: 1_1_da_2025_scom_...)
      if len(parts) >= 2 and re.fullmatch(r"\d{1,2}", parts[0]) and re.fullmatch(r"\d{1,2}", parts[1]):
          return "", f"{parts[0]}_{parts[1]}", parts[2:]
      for i in (2, 3):
          if i + 1 < len(parts) and parts[i].isdigit() and parts[i+1].isdigit():
              return '_'.join(parts[:i]), f"{parts[i]}_{parts[i+1]}", parts[i+2:]
      return parts[0], f"{parts[1]}_{parts[2]}", parts[3:]

  def _find_report_key(values):
      for v in values:
          if isinstance(v, str) and re.fullmatch(r"\d+_\d+", v):
              return v
      return ''

  def split_metric_col(val: str) -> dict:
      """metric_col → J1~J7, J11"""
      parts = str(val).split('_')
      if len(parts) < 3:
          j1_to_j7 = (parts + [''] * 7)[:7]
          return {**{f"J{i+1}": j1_to_j7[i] for i in range(7)}, "J11": "", "metric_name": ""}

      first, second, remaining = _split_by_number_pattern(parts)
      processed = []
      i = 0
      while i < len(remaining):
          if remaining[i].isdigit() and remaining[i].startswith('202'):
              if i + 2 < len(remaining) and remaining[i+2].lower() == 'prior':
                  processed.append(f"{remaining[i]}_{remaining[i+1]}_{remaining[i+2]}")
                  i += 3
              elif i + 1 < len(remaining):
                  processed.append(f"{remaining[i]}_{remaining[i+1]}")
                  i += 2
              else:
                  processed.append(remaining[i])
                  i += 1
          else:
              processed.append(remaining[i])
              i += 1

      all_parts = [first, second] + processed
      j1_to_j7 = (all_parts + [''] * 7)[:7]
      metric_name = '_'.join(all_parts[7:]) if len(all_parts) > 7 else ''
      report_key = _find_report_key(j1_to_j7)
      return {**{f"J{i+1}": j1_to_j7[i] for i in range(7)}, "J11": report_no_mapping.get(report_key, ''), "metric_name": metric_name}

  def _apply_j_cols(df: pd.DataFrame) -> pd.DataFrame:
      j_df = pd.DataFrame(
          [split_metric_col(v) for v in df["metric_col"]],
          index=df.index
      )
      return pd.concat([df, j_df], axis=1)

  # ── 매핑 로드 ─────────────────────────────────────────────────────
  mapping_df = pd.read_csv(MAPPING_CSV)
  id_vars = ["Subsidiary", "Country", "Site_Code", "RSID",
             "Start_Date", "End_Date", "itemId", "value"]

  ok_list, skip_list = [], []
  channel_frames = {}
  all_frames = []  # union용

  csv_files = [f for f in EXPORTS_DIR.glob("*.csv") if "_long" not in f.name and "_stacked" not in f.name]
  print(f"▶ 처리 대상: {len(csv_files)}개 파일\n")

  for src_path in sorted(csv_files):
      stem   = src_path.stem
      tb_key = re.sub(r"_\d{8}_\d{6}$", "", stem)

      tb_mapping = mapping_df[mapping_df["tb"] == tb_key]
      if tb_mapping.empty:
          tb_mapping = mapping_df[mapping_df["tb"] == re.sub(r"_prior$", "", tb_key)]

      if tb_mapping.empty:
          skip_list.append(tb_key)
          continue

      rename_dict = dict(zip(tb_mapping["value_n"], tb_mapping["column"]))

      df = pd.read_csv(src_path, encoding="utf-8-sig")
      df = df.rename(columns=rename_dict)
      value_vars = [c for c in rename_dict.values() if c in df.columns]

      for v in value_vars:
          df[v] = pd.to_numeric(
              df[v].astype(str).str.strip().str.replace("'", "", regex=False),
              errors="coerce"
          )

      df_long = df.melt(
          id_vars=[c for c in id_vars if c in df.columns],
          value_vars=value_vars,
          var_name="metric_col",
          value_name="metric_value_origin"
      )

      # ── currency 환율 적용 ────────────────────────────────────────
      df_long["_year"] = pd.to_datetime(df_long["Start_Date"]).dt.year.astype(str)
      df_long["_site"] = df_long["Site_Code"].str.strip().str.lower()

      def calc_adj(row):
          if "revenue" not in str(row["metric_col"]).lower():
              return row["metric_value_origin"]
          rates = cur_map.get(row["_site"])
          if not rates:
              return row["metric_value_origin"]
          rate = rates.get(row["_year"])
          if rate is None:
              return row["metric_value_origin"]
          try:
              return float(row["metric_value_origin"]) * float(rate)
          except (TypeError, ValueError):
              return row["metric_value_origin"]

      df_long["metric_value_adj"] = df_long.apply(calc_adj, axis=1)
      df_long = df_long.drop(columns=["_year", "_site"])

      df_long["metric_value_origin"] = pd.to_numeric(
          df_long["metric_value_origin"].astype(str).str.replace("'", "", regex=False),
          errors="coerce"
      )
      df_long["metric_value_adj"] = pd.to_numeric(
          df_long["metric_value_adj"].astype(str).str.replace("'", "", regex=False),
          errors="coerce"
      )

      # ── metric_col 키 분리 ────────────────────────────────────────
      df_long = _apply_j_cols(df_long)

      # ── channel 파일이면 수집, 아니면 바로 저장 ───────────────────
      is_channel = "channel" in tb_key.lower()
      if is_channel:
          channel_frames[tb_key] = df_long
      else:
          df_long["value"] = df_long["metric_name"]
          out_path = EXPORTS_DIR / f"{tb_key}_stacked_separate.csv"
          df_long.to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          ok_list.append(tb_key)
          if re.search(r'_\d{1,2}_\d{1,2}(?:_|$)', tb_key):
              all_frames.append(df_long)

  # ── channel 후처리 (루프 종료 후) ────────────────────────────────
  if channel_frames:
      print(f"\n▶ channel 후처리: {list(channel_frames.keys())}")

      for tb_key, df_long in channel_frames.items():

          # 1. US value 치환
          is_us = df_long["Site_Code"].str.strip().str.lower() == "us"
          df_long.loc[is_us, "value"] = (
              df_long.loc[is_us, "value"].map(us_mapping).fillna(df_long.loc[is_us, "value"])
          )

          # 2. dummy 0 삽입
          all_sites   = df_long["Site_Code"].unique()
          all_values  = df_long["value"].unique()
          metric_cols = df_long["metric_col"].unique()

          meta_cols = [c for c in ["Subsidiary", "Country", "RSID"] if c in df_long.columns]
          meta_df = (
              df_long.groupby("Site_Code")[meta_cols]
              .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
              .reset_index()
          )
          date_cols = [c for c in ["Start_Date", "End_Date", "itemId"] if c in df_long.columns]
          date_meta = (
              df_long.groupby("Site_Code")[date_cols]
              .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)
              .reset_index()
          )

          cross = pd.MultiIndex.from_product(
              [all_sites, all_values, metric_cols],
              names=["Site_Code", "value", "metric_col"]
          ).to_frame(index=False)

          existing = df_long[["Site_Code", "value", "metric_col"]].drop_duplicates()
          existing["_exists"] = True

          merged = cross.merge(existing, on=["Site_Code", "value", "metric_col"], how="left")
          dummy_rows = merged[merged["_exists"].isna()].drop(columns=["_exists"])

          if not dummy_rows.empty:
              dummy_rows = dummy_rows.merge(meta_df, on="Site_Code", how="left")
              dummy_rows = dummy_rows.merge(date_meta, on="Site_Code", how="left")
              dummy_rows["metric_value_origin"] = 0.0
              dummy_rows["metric_value_adj"]    = 0.0
              dummy_rows = _apply_j_cols(dummy_rows)
              df_long = pd.concat([df_long, dummy_rows], ignore_index=True)
              print(f"  {tb_key} → dummy {len(dummy_rows)}행 삽입")

          # 3. PAID_NONPAID 컬럼 추가 (value 왼쪽)
          df_long["PAID_NONPAID"] = df_long["value"].map(global_paid_mapping)
          val_idx = df_long.columns.get_loc("value")
          cols = list(df_long.columns)
          cols.remove("PAID_NONPAID")
          cols.insert(val_idx, "PAID_NONPAID")
          df_long = df_long[cols]

          out_path = EXPORTS_DIR / f"{tb_key}_stacked_separate.csv"
        #   df_long.to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          finalize_df(df_long).to_csv(out_path, index=False, encoding="utf-8-sig", float_format="%.6f")
          ok_list.append(tb_key)
          if re.search(r'_\d{1,2}_\d{1,2}(?:_|$)', tb_key):
              all_frames.append(df_long)

  # ── union 생성 ────────────────────────────────────────────────────
  if all_frames:
      ts = datetime.now().strftime("%Y%m%d_%H%M%S")
      union_path = EXPORTS_DIR / f"union_{ts}.csv"
      union_df = pd.concat(all_frames, ignore_index=True)
      if "PAID_NONPAID" in union_df.columns:
          union_df["PAID_NONPAID"] = union_df["PAID_NONPAID"].fillna("-")
    #   union_df.to_csv(union_path, index=False, encoding="utf-8-sig", float_format="%.6f")
      finalize_df(union_df).to_csv(union_path, index=False, encoding="utf-8-sig", float_format="%.6f")
      print(f"\n▶ union 저장: {union_path} ({len(union_df):,}행)")

  # ── 결과 요약 ─────────────────────────────────────────────────────
  print(f"\n✅ 완료: {len(ok_list)}개")
  for t in ok_list: print(f"  - {t}")
  print(f"\n⚠️  매핑 없어서 skip: {len(skip_list)}개")
  for t in skip_list: print(f"  - {t}")

▶ 환율 컬럼: 2026-02-28(2026) / 2025-02-28(2025)
▶ 처리 대상: 66개 파일


▶ channel 후처리: ['25_ny_3_1_channel_internal', '25_ny_3_2_channel_traffic_external', '25_ny_7_1_order_by_channel_cmp', '26_ny_3_1_channel_internal', '26_ny_3_2_channel_external_cmp', '26_ny_3_2_channel_external_scom', '26_ny_3_2_channel_external_scom_prior', '26_ny_7_1_order_by_channel_cmp', '26_ny_7_1_order_by_channel_scom', '26_ny_7_1_order_by_channel_scom_prior']
  25_ny_3_2_channel_traffic_external → dummy 132행 삽입
  25_ny_7_1_order_by_channel_cmp → dummy 129행 삽입
  26_ny_3_2_channel_external_cmp → dummy 642행 삽입
  26_ny_3_2_channel_external_scom → dummy 120행 삽입
  26_ny_3_2_channel_external_scom_prior → dummy 116행 삽입
  26_ny_7_1_order_by_channel_cmp → dummy 1200행 삽입
  26_ny_7_1_order_by_channel_scom → dummy 180행 삽입
  26_ny_7_1_order_by_channel_scom_prior → dummy 174행 삽입

▶ union 저장: c:\Users\CNXK\OneDrive - Concentrix Corporation\pjh\2.data\99.PY,SQL-250429\00.py_notebook\260224_AA_Exporter(jiwoo)\aa_exports\union_20260304_141937.csv (25,624행)

✅ 완료: 59개
  - 25_ny_1_1_scom_da_traffic_app
  - 25_ny_1_1_scom_da_traffic_web
  - 25_ny_1_1_scom_mx_traffic_app
  - 25_ny_1_1_scom_mx_traffic_web
  - 25_ny_1_1_scom_vd_traffic_app
  - 25_ny_1_1_scom_vd_traffic_web
  - 25_ny_2_1_basic_traffic_cmp
  - 25_ny_2_1_basic_traffic_scom
  - 25_ny_2_1_basic_traffic_time
  - 25_ny_3_3_homepage_kv_gnb_to_cmp
  - 25_ny_4_1_order_cvr_loginout
  - 25_ny_4_1_scom_order_cvr_loginout
  - 25_ny_5_1_scom_campaign_order_cvr
  - 25_ny_6_1_multi_order_cross_sell
  - 25_ny_6_2_total_order_cross_sell
  - 25_ny_6_3_cmp_order_cross_sell
  - 25_ny_bestselling
  - 26_ny_1_1_scom_da_traffic_app
  - 26_ny_1_1_scom_da_traffic_app_prior
  - 26_ny_1_1_scom_da_traffic_web
  - 26_ny_1_1_scom_da_traffic_web_prior
  - 26_ny_1_1_scom_mx_traffic_app
  - 26_ny_1_1_scom_mx_traffic_app_prior
  - 26_ny_1_1_scom_mx_traffic_web
  - 26_ny_1_1_scom_mx_traffic_web_prior
  - 26_ny_1_1_scom_vd_traffic_app
  - 26_ny_1_1_scom_vd_traffic_app_prior
  - 26_ny_1_1_scom_vd_traffic_web
  - 26_ny_1_1_scom_vd_traffic_web_prior
  - 26_ny_2_1_basic_traffic_cmp
  - 26_ny_2_1_basic_traffic_scom
  - 26_ny_2_1_basic_traffic_scom_prior
  - 26_ny_2_1_basic_traffic_time_cmp
  - 26_ny_2_1_basic_traffic_time_scom
  - 26_ny_2_1_basic_traffic_time_scom_prior
  - 26_ny_3_3_homepage_kv_gnb_to_cmp
  - 26_ny_4_1_order_cvr_loginout
  - 26_ny_4_2_order_cvr_visit_visitor
  - 26_ny_5_1_campaign_order_cvr
  - 26_ny_5_1_scom_order_cvr
  - 26_ny_6_1_multi_order_cross_sell
  - 26_ny_6_1_multi_order_cross_sell_prior
  - 26_ny_6_2_total_order_cross_sell
  - 26_ny_6_2_total_order_cross_sell_prior
  - 26_ny_6_3_cmp_order_cross_sell
  - 26_ny_bestselling
  - 26_ny_nextpage
  - 26_ny_raw_multi_purchase_v41
  - 26_ny_raw_multi_purchase_v41_prior
  - 25_ny_3_1_channel_internal
  - 25_ny_3_2_channel_traffic_external
  - 25_ny_7_1_order_by_channel_cmp
  - 26_ny_3_1_channel_internal
  - 26_ny_3_2_channel_external_cmp
  - 26_ny_3_2_channel_external_scom
  - 26_ny_3_2_channel_external_scom_prior
  - 26_ny_7_1_order_by_channel_cmp
  - 26_ny_7_1_order_by_channel_scom
  - 26_ny_7_1_order_by_channel_scom_prior

⚠️  매핑 없어서 skip: 7개
  - 25_ny_3_2_channel_external_scom
  - union
  - union
  - union
  - union
  - union
  - union