In [ ]:
!pip install tqdm

In [ ]:
## **1_1~2. S.com Traffic by Division**

In [ ]:
#### **S.com DA Traffic & Order (App)**

In [7]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_1_1_scom_da_traffic_app_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:05:18
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260224_090518.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260224_090518.csv
총 데이터 row(FAILED row 제외, header 제외): 28
⏱ Elapsed: 0:07:54.617943
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_app_prior_20260224_090518.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_4,visits_5,...,cm200001591_680982137431683723d70110_27,cm200001591_680982137431683723d70110_28,orders_31,orders_32,orders_33,revenue_35,revenue_36,revenue_37,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0,NaN,2820.0,2234.0,...,6.0,0.0,23.0,14.0,9.0,25041.53,13669.77,11371.76,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0,NaN,837.0,625.0,...,0.0,0.0,8.0,5.0,3.0,7946.89,6249.92,1696.97,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,0,NaN,7112.0,5840.0,...,0.0,5.0,142.0,103.0,26.0,122058.06,89373.70,24262.37,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,5061.0,3839.0,...,2.0,0.0,172.0,124.0,31.0,153066.08,109130.41,24220.29,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,4775.0,3308.0,...,3.0,14.0,189.0,116.0,56.0,167144.79,114230.91,44951.05,OK,NaN

In [ ]:
#### **S.com DA Traffic & Order (Web)**

In [8]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_1_1_scom_da_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:13:31
▶ Output: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260224_091331.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260224_091331.csv
총 데이터 row(FAILED row 제외, header 제외): 44
⏱ Elapsed: 0:00:31.966850
❌ 실패 site: 0
DONE: aa_exports\26_ny_1_1_scom_da_traffic_web_prior_20260224_091331.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_4,visits_5,...,entries_18,entries_19,bounces_21,bounces_22,orders_25,orders_26,revenue_28,revenue_29,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0,NaN,114201.0,85710.0,...,100477.0,71271.0,68163.0,42291.0,135.0,137.0,103405.22,89694.66,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0,NaN,6279.0,10985.0,...,3736.0,8631.0,1127.0,5340.0,7.0,17.0,6094.91,10352.36,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,0,NaN,32540.0,47195.0,...,22229.0,34351.0,9080.0,12095.0,324.0,334.0,284085.07,277197.04,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,21727.0,44542.0,...,13439.0,31761.0,1603.0,6706.0,230.0,353.0,198541.25,305282.80,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,17955.0,26937.0,...,13082.0,20263.0,4201.0,7352.0,213.0,152.0,176442.93,123353.52,OK,NaN

In [ ]:
#### **S.com MX Traffic & Order (App)**

In [9]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_1_1_scom_mx_traffic_app_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:14:07
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260224_091407.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260224_091407.csv
총 데이터 row(FAILED row 제외, header 제외): 28
⏱ Elapsed: 0:03:38.032765
❌ 실패 site: 3
실패 목록(앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_app_prior_20260224_091407.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_4,visits_5,...,cm200001591_680982137431683723d70110_27,cm200001591_680982137431683723d70110_28,orders_31,orders_32,orders_33,revenue_35,revenue_36,revenue_37,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0.0,NaN,48124.0,39211.0,...,16.0,19.0,556.0,486.0,37.0,387352.46,318469.74,44237.68,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0.0,NaN,6616.0,5549.0,...,5.0,2.0,115.0,95.0,6.0,65189.59,50183.81,4652.94,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...

In [ ]:
#### **S.com MX Traffic & Order (Web)**

In [10]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_1_1_scom_mx_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:18:08
▶ Output: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260224_091808.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260224_091808.csv
총 데이터 row(FAILED row 제외, header 제외): 44
⏱ Elapsed: 0:00:34.928739
❌ 실패 site: 1
실패 목록(앞 50개):
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_mx_traffic_web_prior_20260224_091808.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_4,visits_5,...,entries_18,entries_19,bounces_21,bounces_22,orders_25,orders_26,revenue_28,revenue_29,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0.0,NaN,154911.0,519911.0,...,102252.0,443588.0,30659.0,273969.0,1470.0,1548.0,1485172.56,1151902.09,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0.0,NaN,15788.0,49031.0,...,10137.0,41395.0,2728.0,24712.0,147.0,146.0,101785.48,90872.34,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,0.0,NaN,123589.0,393456.0,...,87711.0,319870.0,25280.0,128829.0,1603.0,2508.0,1253079.36,1706928.54,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0.0,NaN,116776.0,363635.0,...,76190.0,295761.0,11942.0,70631.0,801.0,1241.0,652116.59,903309.59,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...

In [ ]:
#### **S.com VD Traffic & Order (App)**

In [11]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_1_1_scom_vd_traffic_app_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:19:00
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260224_091900.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260224_091900.csv
총 데이터 row(FAILED row 제외, header 제외): 25
⏱ Elapsed: 0:04:46.431816
❌ 실패 site: 3
실패 목록(앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_app_prior_20260224_091900.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_4,visits_5,...,cm200001591_680982137431683723d70110_27,cm200001591_680982137431683723d70110_28,orders_31,orders_32,orders_33,revenue_35,revenue_36,revenue_37,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0.0,NaN,11282.0,8284.0,...,74.0,76.0,92.0,72.0,19.0,102615.30,83596.59,18218.72,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0.0,NaN,2116.0,1498.0,...,27.0,19.0,22.0,16.0,5.0,26074.34,17958.82,7115.53,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...

In [ ]:
#### **S.com VD Traffic & Order (Web)**

In [12]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_1_1_scom_vd_traffic_web_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:25:30
▶ Output: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260224_092530.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260224_092530.csv
총 데이터 row(FAILED row 제외, header 제외): 42
⏱ Elapsed: 0:00:40.334906
❌ 실패 site: 3
실패 목록(앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_1_1_scom_vd_traffic_web_prior_20260224_092530.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_4,visits_5,...,entries_18,entries_19,bounces_21,bounces_22,orders_25,orders_26,revenue_28,revenue_29,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0.0,NaN,198029.0,349956.0,...,174349.0,325914.0,124915.0,198715.0,387.0,258.0,479096.80,301335.19,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0.0,NaN,9533.0,17542.0,...,6502.0,14886.0,2266.0,8394.0,33.0,23.0,40979.08,23201.40,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,FAILED,422 Client Error: Unprocessable Entity for url...

In [ ]:
## **2_1~4. Basic Traffic**

In [ ]:
#### **Basic Traffic - S.com (Web & App)**

In [13]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_2_1_basic_traffic_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:27:07
▶ Output: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260224_092707.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260224_092707.csv
총 데이터 row(FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:00:43.761999
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_scom_prior_20260224_092707.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_3,visits_4,...,pageviews_35,pageviews_36,entries_38,entries_39,entries_40,cm200001591_680982137431683723d70110_42,cm200001591_680982137431683723d70110_43,cm200001591_680982137431683723d70110_44,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0,NaN,632070.0,1669452.0,...,1901273.0,62605.0,190718.0,160399.0,11858.0,69259.0,57139.0,6040.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0,NaN,50933.0,137588.0,...,345118.0,17651.0,49181.0,42844.0,1786.0,25783.0,22643.0,890.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,0,NaN,276471.0,795457.0,...,4387583.0,145183.0,244847.0,212531.0,18489.0,78909.0,65307.0,12059.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,286601.0,830751.0,...,2171360.0,82517.0,216903.0,187219.0,11565.0,72262.0,62992.0,7172.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,147083.0,417143.0,...,2635080.0,101449.0,170925.0,137140.0,18995.0,61523.0,47075.0,12417.0,OK,NaN

In [ ]:
#### **Basic Traffic  - S.com Time Spent per Visit (Web & App)**

In [14]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_2_1_basic_traffic_time_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:29:10
▶ Output: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260224_092910.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260224_092910.csv
총 데이터 row(FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:00:31.534008
❌ 실패 site: 0
DONE: aa_exports\26_ny_2_1_basic_traffic_time_scom_prior_20260224_092910.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,timespentvisit_0,timespentvisit_3,timespentvisit_4,timespentvisit_6,timespentvisit_7,timespentvisit_8,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1260001,2026 (Jan 1-Dec 31),258.431517,269.990987,261.576804,208.537258,207.837747,283.650411,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,1260001,2026 (Jan 1-Dec 31),209.738887,248.024982,184.600890,229.714326,208.849612,335.214693,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,1260001,2026 (Jan 1-Dec 31),297.909465,403.731461,263.348328,275.414178,264.083323,409.131326,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),293.040904,337.640947,292.218945,224.293369,215.871798,368.507953,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),284.545298,363.268746,251.575423,283.898822,265.982206,421.462910,OK,NaN

In [ ]:
## **3. Traffic by Channel**

In [ ]:
#### **External Traffic by Channel - S.com (Web & App)**

In [15]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_3_2_channel_external_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:29:56
▶ Output: aa_exports\26_ny_3_2_channel_external_scom_prior_20260224_092956.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_3_2_channel_external_scom_prior_20260224_092956.csv
총 데이터 row(FAILED row 제외, header 제외): 930
⏱ Elapsed: 0:00:28.043411
❌ 실패 site: 0
DONE: aa_exports\26_ny_3_2_channel_external_scom_prior_20260224_092956.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,cm200001591_56c1679b04f4860205c9f511_2,bounces_3,entries_5,cm200001591_680982137431683723d70110_6,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,11,Social Media Campaigns,606640.0,453695.0,728.0,190.0,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,2,Natural Search,526323.0,116388.0,9495.0,1769.0,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,5,Direct,481405.0,322823.0,120532.0,49775.0,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1,Paid Search,212113.0,97108.0,3464.0,894.0,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,14,Push,116828.0,91890.0,23232.0,6026.0,OK,NaN

In [ ]:
## **6. S.com Cross Sell Order**

In [ ]:
#### **6-1. Multi Order Cross-Sell (Total)**

In [16]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_6_1_multi_order_cross_sell_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:30:34
▶ Output: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260224_093034.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260224_093034.csv
총 데이터 row(FAILED row 제외, header 제외): 39
⏱ Elapsed: 0:00:33.310005
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_1_multi_order_cross_sell_prior_20260224_093034.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,orders_1,revenue_2,...,orders_18,revenue_19,orders_22,revenue_23,orders_26,revenue_27,orders_31,revenue_32,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0,NaN,1400.0,1877185.08,...,8.0,7958.17,0.0,0.00,0.0,0.00,0.0,0.00,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0,NaN,149.0,148459.90,...,2.0,4018.96,0.0,0.00,0.0,0.00,0.0,0.00,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,0,NaN,1849.0,1979049.12,...,12.0,15230.33,8.0,16004.52,6.0,12306.51,0.0,0.00,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,1297.0,1562062.78,...,3.0,9839.18,30.0,61613.41,48.0,121025.28,0.0,0.00,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,1106.0,1588598.91,...,9.0,14716.17,12.0,22661.78,9.0,21310.08,3.0,9530.23,OK,NaN

In [ ]:
#### **6-2. All Order Cross-Sell (Total)**

In [6]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_6_2_total_order_cross_sell_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:00:12
▶ Output: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260224_090012.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260224_090012.csv
총 데이터 row(FAILED row 제외, header 제외): 39
⏱ Elapsed: 0:04:23.781507
❌ 실패 site: 0
DONE: aa_exports\26_ny_6_2_total_order_cross_sell_prior_20260224_090012.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,orders_0,revenue_1,...,orders_17,revenue_18,orders_21,revenue_22,orders_25,revenue_26,orders_30,revenue_31,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,0,NaN,4901.0,4287366.77,...,8.0,7958.17,0.0,0.00,0.0,0.00,0.0,0.00,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,0,NaN,536.0,376753.79,...,2.0,4018.96,0.0,0.00,0.0,0.00,0.0,0.00,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,0,NaN,7346.0,5531474.94,...,12.0,15230.33,8.0,16004.52,6.0,12306.51,0.0,0.00,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,0,NaN,4478.0,3555668.99,...,3.0,9839.18,30.0,61613.41,48.0,121025.28,0.0,0.00,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,0,NaN,3347.0,3503271.21,...,9.0,14716.17,12.0,22661.78,9.0,21310.08,3.0,9530.23,OK,NaN

In [ ]:
## **7_1~2. Order Conversion/Traffic by Channel**

In [ ]:
#### **Order Conversion by Channel - S.com (Web & App)**

In [5]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_7_1_order_by_channel_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 08:54:42
▶ Output: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260224_085442.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260224_085442.csv
총 데이터 row(FAILED row 제외, header 제외): 930
⏱ Elapsed: 0:04:51.679939
❌ 실패 site: 0
DONE: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260224_085442.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,cm200001591_56c1679b04f4860205c9f511_2,cm200001591_56c1679b04f4860205c9f511_3,orders_5,orders_6,revenue_8,revenue_9,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,11,Social Media Campaigns,606640.0,728.0,4.0,4.0,6722.01,2087.97,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,2,Natural Search,526323.0,9495.0,1747.0,65.0,1439431.94,46877.07,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,5,Direct,481405.0,120530.0,693.0,362.0,675524.59,261558.73,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1,Paid Search,212113.0,3464.0,644.0,10.0,644848.05,6298.28,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,14,Push,116828.0,23232.0,7.0,98.0,5986.94,76324.70,OK,NaN

In [5]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = "2_1_all_2026_scom"  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_7_1_order_by_channel_scom_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 08:54:42
▶ Output: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260224_085442.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260224_085442.csv
총 데이터 row(FAILED row 제외, header 제외): 930
⏱ Elapsed: 0:04:51.679939
❌ 실패 site: 0
DONE: aa_exports\26_ny_7_1_order_by_channel_scom_prior_20260224_085442.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,cm200001591_56c1679b04f4860205c9f511_2,cm200001591_56c1679b04f4860205c9f511_3,orders_5,orders_6,revenue_8,revenue_9,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,11,Social Media Campaigns,606640.0,728.0,4.0,4.0,6722.01,2087.97,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,2,Natural Search,526323.0,9495.0,1747.0,65.0,1439431.94,46877.07,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,5,Direct,481405.0,120530.0,693.0,362.0,675524.59,261558.73,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1,Paid Search,212113.0,3464.0,644.0,10.0,644848.05,6298.28,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,14,Push,116828.0,23232.0,7.0,98.0,5986.94,76324.70,OK,NaN

In [ ]:
## **Multi Purchase**

In [ ]:
#### **Campaign Multi Order (Total)**

In [25]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_raw_multi_purchase_v41_prior.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 11:27:12
▶ Output: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260224_112712.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260224_112712.csv
총 데이터 row(FAILED row 제외, header 제외): 15,508
⏱ Elapsed: 0:01:14.237319
❌ 실패 site: 0
DONE: aa_exports\26_ny_raw_multi_purchase_v41_prior_20260224_112712.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,units_2,orders_3,revenue_4,units_5,orders_6,revenue_7,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,2732371547,HAF-QIN/EXP,0.0,0.0,0.00,154.0,66.0,6792.60,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,4161418187,HAF-CIN/EXP,0.0,0.0,0.00,47.0,18.0,2052.50,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,2825269610,MZ-V9S1T0B/AM,0.0,0.0,0.00,29.0,6.0,6234.71,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,3323044592,"SM-R630NZAAXAC,P-GT-AXXCW0MC",2.0,1.0,278.99,24.0,12.0,3368.99,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,537663737,"SM-Q5KAPH,ET-YQ510KBEGCA",0.0,0.0,0.00,24.0,12.0,5399.88,OK,NaN

In [ ]:
## Best Selling Product

In [23]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_bestselling.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=tb_cols,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 10:39:21
▶ Output: aa_exports\26_ny_bestselling_20260224_103921.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_bestselling_20260224_103921.csv
총 데이터 row(FAILED row 제외, header 제외): 11,162
⏱ Elapsed: 0:10:52.908976
❌ 실패 site: 1
실패 목록(앞 50개):
 - ZA | HTTPSConnectionPool(host='analytics.adobe.io', port=443): Read timed out. (read timeout=600)
DONE: aa_exports\26_ny_bestselling_20260224_103921.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,orders_0,revenue_1,orders_3,revenue_4,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,3.312047e+09,SMC-CA-STANDALONE,366.0,69403.58,1.0,89.00,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,8.336329e+08,SM-S938W,350.0,722314.63,6.0,9656.94,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,2.977328e+09,SMC-CA,342.0,40997.07,3.0,194.08,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1.802554e+09,TRADE-IN,290.0,0.00,6.0,0.00,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,2.466829e+09,SM-R630,234.0,56491.15,1.0,229.99,OK,NaN

In [ ]:
## Next page

In [17]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_nextpage.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:38:03
▶ Output: aa_exports\26_ny_nextpage_20260224_093803.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_nextpage_20260224_093803.csv
총 데이터 row(FAILED row 제외, header 제외): 1,719
⏱ Elapsed: 0:02:57.268151
❌ 실패 site: 3
실패 목록(앞 50개):
 - UK | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - DE | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
 - ES | 422 Client Error: Unprocessable Entity for url: https://analytics.adobe.io/api/samsun0/reports
DONE: aa_exports\26_ny_nextpage_20260224_093803.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_2,visits_3,visits_4,visits_5,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,3.457728e+09,flagship pdp,2786.0,2785.0,0.0,0.0,OK,NaN
1,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,3.543974e+09,product finder,2096.0,1679.0,303.0,121.0,OK,NaN
2,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,2.067554e+09,product detail,1206.0,283.0,545.0,442.0,OK,NaN
3,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1.231280e+09,microsite,403.0,215.0,22.0,13.0,OK,NaN
4,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,8.041200e+08,product category detail,201.0,113.0,25.0,15.0,OK,NaN

In [ ]:
## Contents visit

In [18]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_cc_visit.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:41:25
▶ Output: aa_exports\26_ny_cc_visit_20260224_094125.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_cc_visit_20260224_094125.csv
총 데이터 row(FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:00:38.714372
❌ 실패 site: 0
DONE: aa_exports\26_ny_cc_visit_20260224_094125.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,visits_3,visits_5,...,visits_23,visits_24,visits_25,visits_26,visits_27,visits_28,visits_29,visits_30,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1260001,2026 (Jan 1-Dec 31),4258.0,460.0,...,4.0,7.0,7.0,6.0,65.0,0.0,56.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,1260001,2026 (Jan 1-Dec 31),995.0,80.0,...,0.0,0.0,1.0,2.0,14.0,0.0,10.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,1260001,2026 (Jan 1-Dec 31),2137.0,369.0,...,4.0,19.0,8.0,4.0,21.0,29.0,30.0,18.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),25304.0,13707.0,...,0.0,0.0,0.0,0.0,2.0,1361.0,3.0,2.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),9899.0,1036.0,...,0.0,0.0,1.0,0.0,3.0,43.0,2.0,1.0,OK,NaN

In [ ]:
## Contents order

In [1]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_cc_order.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 08:42:52
▶ Output: aa_exports\26_ny_cc_order_20260224_084252.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_cc_order_20260224_084252.csv
총 데이터 row(FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:08:35.178193
❌ 실패 site: 0
DONE: aa_exports\26_ny_cc_order_20260224_084252.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,orders_4,orders_5,...,orders_23,orders_24,orders_25,orders_26,orders_27,orders_28,orders_29,orders_30,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1260001,2026 (Jan 1-Dec 31),17.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,1260001,2026 (Jan 1-Dec 31),1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,1260001,2026 (Jan 1-Dec 31),24.0,3.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),219.0,133.0,...,0.0,0.0,0.0,0.0,0.0,19.0,0.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),170.0,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,OK,NaN

In [ ]:
## Contents revenue

In [19]:
from pathlib import Path
import importlib
import utils.aa_exporter
importlib.reload(utils.aa_exporter)

from utils.aa_exporter import ExportConfig, AAExporter
from utils.tb_columns import make_tb_columns
import pandas as pd

base = ""  # 테이블 명에 맞게 수정
tb_cols = make_tb_columns(base) 

json_file_name = "26_ny_cc_revenue.json"

# JSON 파일이 json/ 폴더에 있으면 그걸 우선으로 찾고, 없으면 현재 폴더에서 찾음
json_path = Path.cwd() / "json" / json_file_name

cfg = ExportConfig(
    data_csv="26_ny_site_code.csv",
    json_file=str(json_path), 
    out_dir="aa_exports",
    out_prefix=json_path.stem,
    limit=10000,          # 요청 횟수
    tb_columns=None,   # 테이블 명 추가해서 쓰고 싶으면 tb_cols로 수정
    parallel_sites=True,  # 국가(site) 단위 병렬
    max_workers=6,        #  5~8 추천 (429 많으면 낮춰)
    log_each_page=False,  # 프린트 False로 바꾸면 속도 높아짐
)

out_path = AAExporter(cfg).run()
print("DONE:", out_path)

# 생성된 CSV 바로 불러오기
df = pd.read_csv(out_path, encoding="utf-8-sig")
df.head()

▶ Start time: 2026-02-24 09:43:56
▶ Output: aa_exports\26_ny_cc_revenue_20260224_094356.csv
▶ Parallel sites: True (max_workers=6)
▶ limit(page size): 10,000

AA Export (sites):   0%|          | 0/45 [00:00<?, ?site/s]

*****Data Extraction Completed*****
✅ Saved CSV: aa_exports\26_ny_cc_revenue_20260224_094356.csv
총 데이터 row(FAILED row 제외, header 제외): 45
⏱ Elapsed: 0:04:23.929734
❌ 실패 site: 0
DONE: aa_exports\26_ny_cc_revenue_20260224_094356.csv

,Subsidiary,Country,Site_Code,RSID,Start_Date,End_Date,itemId,value,revenue_4,revenue_5,...,revenue_23,revenue_24,revenue_25,revenue_26,revenue_27,revenue_28,revenue_29,revenue_30,status,error
0,SECA,Canada,CA,sssamsung4ca,2026-01-02,2026-01-29,1260001,2026 (Jan 1-Dec 31),18962.99,2249.99,...,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0,OK,NaN
1,SECA,Canada(FR),CA_FR,sssamsung4cafr,2026-01-02,2026-01-29,1260001,2026 (Jan 1-Dec 31),269.99,0.00,...,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0,OK,NaN
2,SEUK,United Kingdom,UK,vrs_samsun0_p6webmstukcopy,2026-01-19,2026-02-03,1260001,2026 (Jan 1-Dec 31),17756.91,3011.44,...,0.0,0.0,92.54,0.0,1983.68,0.00,0.0,0.0,OK,NaN
3,SEG,Germany,DE,vrs_samsun0_p6webmstgermanyestor_0,2026-01-20,2026-02-05,1260001,2026 (Jan 1-Dec 31),202710.97,142261.39,...,0.0,0.0,0.00,0.0,0.00,19022.73,0.0,0.0,OK,NaN
4,SEIB,Spain,ES,vrs_samsun0_p6webmstspainestoreb,2026-01-19,2026-02-04,1260001,2026 (Jan 1-Dec 31),190260.42,22525.88,...,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0,OK,NaN